/* Edexcel IAL Physics (YPH11) — syllabus content & revision notes (current spec, Issue 3) */
var SUBJECT_PHYSICS = {
id:"physics", name:"Physics", icon:"⚛️", color:"#22d3ee", qual:"YPH11",
desc:"Mechanics, materials, waves, electricity, fields, thermodynamics, oscillations & cosmology — WPH11 to WPH16.",
hubs:[
 {name:"📄 Save My Exams — IAL Physics past papers", url:"https://www.savemyexams.com/international-a-level/physics/edexcel/past-papers/", desc:"Every unit, QP + MS, Jan / Jun / Oct sessions. The fastest full-paper archive."},
 {name:"🏛️ Pearson Edexcel past paper finder", url:"https://qualifications.pearson.com/en/support/support-topics/exams/past-papers.html", desc:"Official source for all WPH papers, mark schemes & examiner reports."},
 {name:"📚 Physics & Maths Tutor", url:"https://www.physicsandmathstutor.com/", desc:"Notes, flashcards & questions by topic (UK + International sections)."},
 {name:"📊 IAL Physics papers & grade boundaries hub", url:"https://www.kingsbridgeeducation.co.uk/post/edexcel-ial-physics-past-papers-mark-schemes-yph11-updated-2026", desc:"Unit-by-unit paper index with A-grade thresholds per session."}
],
units:[
{id:"U1", code:"WPH11", short:"Unit 1", title:"Mechanics & Materials", level:"AS", time:"1 h 30 min", marks:80, weight:"20% of IAL",
topics:[
{id:"U1T1", name:"Motion, Kinematics & Projectiles", tags:"suvat velocity acceleration displacement graphs projectile motion stopping distance",
notes:{lede:"How things move: displacement, velocity and acceleration, suvat equations, motion graphs and projectile motion. The foundation of all mechanics.",
points:[
"<b>Displacement</b> = distance in a stated direction (vector). <b>Distance</b> is scalar — total path length.",
"<b>Velocity</b> = rate of change of displacement (vector, m s<sup>−1</sup>). <b>Speed</b> is scalar.",
"<b>Acceleration</b> = rate of change of velocity: <b>a = Δv / Δt</b> (vector, m s<sup>−2</sup>).",
"<b>suvat</b> (constant acceleration only): v = u + at • s = ut + ½at² • v² = u² + 2as • s = ½(u+v)t.",
"<b>Displacement–time graph:</b> gradient = velocity. Curved = accelerating.",
"<b>Velocity–time graph:</b> gradient = acceleration, <b>area under graph = displacement</b>.",
"<b>Projectiles:</b> horizontal and vertical motions are <b>independent</b>. Horizontal velocity stays constant (ignore air resistance); vertical accelerates at g = 9.81 m s<sup>−2</sup> downwards.",
"For projectiles: resolve initial velocity into u<sub>x</sub> = u cosθ, u<sub>y</sub> = u sinθ, then use suvat separately for x and y.",
"<b>Stopping distance = thinking distance + braking distance.</b> Thinking ∝ speed; braking ∝ speed² (from v² = u² + 2as).",
"Free-fall: all objects accelerate at g if air resistance is negligible (vacuum)."],
formulas:[{e:"v = u + at",w:"velocity after time t"},{e:"s = ut + ½at²",w:"displacement"},{e:"v² = u² + 2as",w:"no time involved"},{e:"a = Δv / Δt",w:"acceleration definition"}],
defs:[{t:"Displacement",d:"Distance moved in a stated direction — a vector quantity."},{t:"Instantaneous velocity",d:"Gradient of the tangent to a displacement–time graph at that instant."}],
worked:{q:"A ball is thrown horizontally at 12 m s⁻¹ from a cliff 45 m high. How far from the base does it land?",steps:["Vertical: u = 0, s = 45 m, a = 9.81. Use s = ut + ½at² → 45 = 4.905t² → t = 3.03 s.","Horizontal: no acceleration, so s = vt = 12 × 3.03 = 36.4 m.","Answer ≈ 36 m. Note both motions share the same time t."]},
mistakes:["Using suvat when acceleration is not constant (e.g. with air resistance / springs).","Mixing up displacement (vector) with distance (scalar) — signs matter.","Forgetting that at the top of a projectile path, vertical velocity = 0 but horizontal velocity is NOT 0."],
tips:["Always draw the v–t or s–t sketch first — half the marks are reading gradients/areas.","Choose up or down as positive and stick to it for the whole question.","Show substitution into every equation: method marks are awarded even if arithmetic slips."],
oos:"<b>Beyond syllabus (fun only):</b> real projectiles suffer quadratic air drag (F ∝ v²), which is why golf balls have dimples and why maximum range is actually below 45°. IAL ignores air resistance unless told otherwise."}},
{id:"U1T2", name:"Forces, Newton's Laws & Momentum", tags:"newton forces friction drag terminal velocity momentum free body",
notes:{lede:"Why things move: Newton's three laws, free-body diagrams, friction and drag, terminal velocity and linear momentum.",
points:[
"<b>Newton 1:</b> a body stays at rest / constant velocity unless a <b>resultant force</b> acts (inertia).",
"<b>Newton 2: F = ma</b> — resultant force = mass × acceleration. Force and acceleration are in the same direction.",
"<b>Newton 3:</b> if A exerts a force on B, B exerts an <b>equal, opposite force on A</b> — same type, acting on different bodies.",
"<b>Weight W = mg</b> (N). Mass (kg) is inertia/resistance to acceleration — weight varies with g.",
"<b>Free-body diagrams:</b> draw ALL forces as arrows from the centre: weight down, normal/contact, friction (opposes motion), tension, drag (opposes velocity).",
"<b>Friction:</b> opposes relative motion/slipping between surfaces. <b>Drag</b> (fluid resistance) opposes motion through a fluid and <b>increases with speed</b>.",
"<b>Terminal velocity:</b> when drag + upthrust = weight, resultant force = 0, so acceleration = 0 and velocity is constant (max).",
"<b>Momentum p = mv</b> (kg m s⁻¹, vector). <b>Impulse = FΔt = Δp</b> — the area under an F–t graph.",
"<b>Conservation of momentum:</b> total momentum stays constant if no external resultant force (e.g. collisions, recoil).",
"<b>Principle of moments:</b> for equilibrium, clockwise moments = anticlockwise moments about any point. Resultant force = 0 AND resultant moment = 0."],
formulas:[{e:"F = ma",w:"Newton's 2nd law"},{e:"W = mg",w:"weight"},{e:"p = mv",w:"momentum"},{e:"FΔt = Δp",w:"impulse"},{e:"moment = F × d⊥",w:"force × perpendicular distance"}],
defs:[{t:"Resultant force",d:"The single force with the same effect as all forces combined (vector sum)."},{t:"Terminal velocity",d:"Constant maximum velocity when drag equals driving force so resultant force is zero."}],
worked:{q:"A 0.15 kg tennis ball hits a wall at 20 m s⁻¹ and rebounds at 15 m s⁻¹. Contact time is 0.010 s. Find the average force.",steps:["Take rebound direction as positive: Δp = mv − mu = 0.15×15 − 0.15×(−20) = 2.25 + 3.00 = 5.25 kg m s⁻¹.","F = Δp/Δt = 5.25 / 0.010 = 525 N.","Force on ball is 525 N away from the wall (on the wall, 525 N into it — Newton 3)."]},
mistakes:["Newton 3 pairs act on DIFFERENT bodies — weight and normal on the same book are NOT a Newton 3 pair.","Forgetting drag acts opposite to velocity (a parachutist's drag acts upwards).","Sign errors in Δp: rebound means velocity changes sign — draw the arrows."],
tips:["'Explain terminal velocity' is a guaranteed 3–4 marker: as speed ↑, drag ↑, resultant ↓, acceleration ↓, until drag = weight → constant velocity.","For equilibrium questions always state BOTH conditions (forces and moments)."],
oos:"<b>Beyond syllabus:</b> F = ma is the special case of F = dp/dt. Rockets need the full form because their mass changes as fuel burns — see the Tsiolkovsky rocket equation."}},
{id:"U1T3", name:"Energy, Work & Power", tags:"energy work power efficiency kinetic gravitational potential sankey",
notes:{lede:"Energy never disappears — only transfers. Work, kinetic and gravitational energy, conservation, power and efficiency.",
points:[
"<b>Work done = force × distance in the direction of the force: W = FΔs cosθ</b> (J). No movement → no work.",
"<b>Kinetic energy: E<sub>k</sub> = ½mv².</b> <b>Gravitational potential: ΔE<sub>p</sub> = mgΔh.</b>",
"<b>Conservation of energy:</b> total energy of a closed system is constant — energy transfers between stores, never created/destroyed.",
"<b>Work–energy principle:</b> work done by resultant force = gain in kinetic energy.",
"<b>Power = rate of energy transfer: P = W/t = Fv</b> (W). 1 W = 1 J s⁻¹.",
"<b>Efficiency = useful output / total input</b> (×100%). Sankey diagrams show proportional energy flows — arrow widths ∝ energy.",
"Energy is <b>dissipated</b> (spread out as heat/sound) by friction and drag — wasted because it cannot be usefully recovered.",
"On slopes: component of weight down slope = mg sinθ; normal = mg cosθ."],
formulas:[{e:"W = FΔs",w:"work done (force ∥ displacement)"},{e:"Eₖ = ½mv²",w:"kinetic energy"},{e:"ΔEₚ = mgΔh",w:"gravitational potential"},{e:"P = W/t = Fv",w:"power"},{e:"eff = useful ÷ total",w:"efficiency"}],
defs:[{t:"Work done",d:"Energy transferred when a force moves its point of application: W = FΔs."},{t:"Power",d:"Rate of doing work / transferring energy, measured in watts."}],
worked:{q:"A 1200 kg car accelerates from 10 to 26 m s⁻¹. Engine efficiency is 25% and petrol gives 44 MJ kg⁻¹. What mass of petrol is used?",steps:["ΔEₖ = ½m(v²−u²) = ½×1200×(676−100) = 345,600 J ≈ 0.346 MJ.","Input energy = 0.346 / 0.25 = 1.38 MJ.","Mass = 1.38 / 44 = 0.031 kg ≈ 31 g."]},
mistakes:["Using total input energy as the answer instead of multiplying/dividing by efficiency.","v² means (26² − 10²), NOT (26−10)² — a classic error.","Forgetting g = 9.81 (not 10) — IAL mark schemes expect 9.81."],
tips:["Energy methods beat suvat whenever time is unknown and forces vary.","Always convert MJ/kWh to J before substituting: 1 kWh = 3.6 MJ."],
oos:"<b>Beyond syllabus:</b> at speeds near light, E = mc² and kinetic energy needs relativity. Everyday IAL speeds are safely Newtonian."}},
{id:"U1T4", name:"Materials: Stress, Strain & Young Modulus", tags:"hooke young modulus stress strain elastic plastic deformation",
notes:{lede:"How materials stretch and break: Hooke's law, stress–strain graphs, Young modulus and elastic strain energy.",
points:[
"<b>Hooke's law: F = kΔx</b> — extension ∝ force, up to the <b>limit of proportionality</b>. k = stiffness (N m⁻¹).",
"<b>Stress σ = F/A</b> (Pa). <b>Strain ε = Δx/x</b> (no units). Stress–strain graphs are material properties; F–x graphs depend on sample size.",
"<b>Young modulus E = stress/strain = F x / (A Δx)</b> (Pa) — measures stiffness of a material. Bigger E = stiffer.",
"<b>Elastic deformation:</b> returns to original shape (obeys Hooke up to limit). <b>Plastic:</b> permanent deformation beyond the <b>elastic limit / yield point</b>.",
"Stress–strain graph features: straight line (Hooke) → limit of proportionality → elastic limit → <b>yield point</b> (plastic flow) → <b>ultimate tensile stress</b> (max) → breaking point.",
"<b>Brittle</b> materials (glass, cast iron) snap with almost no plastic region. <b>Ductile</b> (copper) draw into wires; <b>malleable</b> hammer into sheets. <b>Polymers</b> (rubber, polythene) have curved graphs from the start.",
"<b>Elastic strain energy = area under F–x graph = ½FΔx = ½k(Δx)²</b> (while elastic).",
"<b>Core practical:</b> determine E of a wire — long thin wire, measure diameter with micrometer in several places, add masses, measure extension with travelling microscope/marker, plot F vs Δx, E = gradient⁻¹ × … (E = (F/Δx)·(x/A))."],
formulas:[{e:"F = kΔx",w:"Hooke's law"},{e:"σ = F/A",w:"stress (Pa)"},{e:"ε = Δx/x",w:"strain"},{e:"E = σ/ε",w:"Young modulus"},{e:"E_el = ½FΔx",w:"elastic energy"}],
defs:[{t:"Limit of proportionality",d:"Maximum stress for which extension is proportional to force."},{t:"Yield point",d:"Stress at which a material begins to deform plastically (permanent stretch)."}],
worked:{q:"A 2.0 m steel wire of diameter 0.60 mm extends 1.2 mm under 80 N. Find E.",steps:["A = π(0.30×10⁻³)² = 2.83×10⁻⁷ m².","σ = 80/2.83×10⁻⁷ = 2.83×10⁸ Pa; ε = 1.2×10⁻³/2.0 = 6.0×10⁻⁴.","E = σ/ε = 4.7×10¹¹ Pa ≈ 470 GPa (steel ≈ 200 GPa — sample numbers illustrative)."]},
mistakes:["Confusing limit of proportionality (graph stops straight) with elastic limit (stops springing back).","Using diameter instead of radius in A = πr² — or forgetting to square.","Reading energy as F×Δx (rectangle) instead of the triangle area ½FΔx."],
tips:["Learn to sketch + label brittle vs ductile vs polymer curves — appears almost every year.","For the E core practical, the micrometer zero-error and repeat readings are favourite 1-mark questions."],
oos:"<b>Beyond syllabus:</b> Young's modulus comes from stretching atomic bonds; rubber's elasticity is entropic (chains uncoil) — that's why a stretched rubber band warms up."}}
]},
{id:"U2", code:"WPH12", short:"Unit 2", title:"Waves & Electricity", level:"AS", time:"1 h 30 min", marks:80, weight:"20% of IAL",
topics:[
{id:"U2T1", name:"Progressive & Stationary Waves", tags:"waves wavelength frequency standing stationary harmonics superposition",
notes:{lede:"Wave behaviour: progressive waves, the wave equation, superposition, stationary waves and harmonics on strings and pipes.",
points:[
"<b>Progressive wave:</b> transfers energy without transferring matter — particles oscillate about fixed positions.",
"<b>Transverse:</b> oscillation ⊥ travel (light, water surface, S-waves). <b>Longitudinal:</b> oscillation ∥ travel (sound, P-waves) — compressions and rarefactions.",
"<b>Wave equation: v = fλ.</b> f = 1/T. Amplitude, wavelength, phase: <b>phase difference = 2πx/λ</b>.",
"<b>Superposition:</b> when waves meet, displacements add. <b>Constructive</b> (in phase, path difference = nλ) vs <b>destructive</b> (antiphase, path diff = (n+½)λ).",
"<b>Stationary wave:</b> formed when two identical waves travel in opposite directions and superpose — e.g. wave + reflection. <b>Nodes</b> (zero amplitude) and <b>antinodes</b> (max amplitude).",
"String fixed both ends: <b>L = nλ/2</b> → harmonics f<sub>n</sub> = n·(v/2L). Fundamental (n=1) has 2 nodes, 1 antinode.",
"<b>Core practical:</b> string + vibrator + masses — measure λ from loop length, f from signal generator, v = fλ; or investigate f ∝ 1/L, f ∝ √T.",
"Sound in air columns: closed pipe L = nλ/4 (odd harmonics only); open pipe L = nλ/2."],
formulas:[{e:"v = fλ",w:"wave equation"},{e:"f = 1/T",w:"frequency–period"},{e:"Δφ = 2πx/λ",w:"phase difference"},{e:"L = nλ/2",w:"string harmonics"}],
defs:[{t:"Node",d:"Point on a stationary wave of zero displacement/amplitude at all times."},{t:"Coherence",d:"Waves with constant phase difference (and same frequency) — needed for stable interference."}],
worked:{q:"A 0.80 m string fixed at both ends vibrates at 120 Hz with 4 loops. Find the wave speed.",steps:["4 loops → L = 4(λ/2) → λ = 2L/4 = 0.40 m.","v = fλ = 120 × 0.40 = 48 m s⁻¹.","This is the 4th harmonic (n = 4)."]},
mistakes:["Counting loops as wavelengths — one loop = λ/2, not λ.","Saying particles in a stationary wave 'don't move' — nodes don't; antinodes oscillate with max amplitude.","Mixing path difference (distance) with phase difference (angle)."],
tips:["Draw the stationary wave and count nodes: nodes = n+1 for a string.","For 'explain how a stationary wave forms', always mention: reflection → same f, λ, speed, opposite direction → superposition."],
oos:"<b>Beyond syllabus:</b> musical timbre is the mix of harmonics; noise-cancelling headphones use destructive superposition in real time."}},
{id:"U2T2", name:"Interference, Diffraction & Polarisation", tags:"young double slit diffraction grating polarisation coherence",
notes:{lede:"The wave proofs: Young's double slit, diffraction gratings, single-slit diffraction and polarisation — light must be a wave.",
points:[
"<b>Young's double slit:</b> laser → two slits (coherent sources) → fringe pattern on screen. Bright fringes where path difference = nλ.",
"<b>Fringe spacing: w = λD/s</b> — w = fringe width, D = slits-to-screen, s = slit separation. Measure across several fringes and divide.",
"<b>Diffraction:</b> spreading when waves pass a gap. Significant when gap ≈ λ. Narrower gap → more spreading.",
"<b>Diffraction grating: d sinθ<sub>n</sub> = nλ</b> — d = grating spacing (1 / lines-per-metre). More lines/mm → wider-spaced, sharper orders. Max order when sinθ ≤ 1.",
"<b>Single slit:</b> central maximum (twice as wide, brightest) + faint fringes; central width ∝ λD/a.",
"<b>Polarisation:</b> only <b>transverse</b> waves can be polarised — proves light is transverse. Polaroid absorbs all planes except its transmission axis.",
"<b>Crossed polaroids</b> (axes 90°) transmit nothing. Reflected light / scattered skylight is partially polarised — sunglasses and stress analysis use this.",
"<b>Core practical:</b> determine λ with a grating — measure θ for n = 1, 2…, λ = d sinθ/n; repeat and average."],
formulas:[{e:"w = λD/s",w:"Young fringe spacing"},{e:"d sinθ = nλ",w:"grating equation"},{e:"d = 1/N",w:"grating spacing from lines/m"}],
defs:[{t:"Coherent sources",d:"Sources emitting waves of the same frequency with a constant phase difference."},{t:"Order n",d:"The nth bright fringe/maximum from the centre (path difference nλ)."}],
worked:{q:"A grating with 500 lines/mm gives 2nd-order maximum at 34.2°. Find λ.",steps:["d = 1/(500×10³) = 2.0×10⁻⁶ m.","λ = d sinθ/n = 2.0×10⁻⁶ × sin34.2°/2 = 5.6×10⁻⁷ m = 560 nm.","Green light — sensible answer."]},
mistakes:["Using lines/cm instead of lines/m in d = 1/N — convert to per metre first.","Forgetting that zero order (n=0) is the central maximum.","Claiming sound can be polarised — longitudinal waves cannot."],
tips:["Increasing s (slit separation) makes fringes NARROWER — inverse relation trips everyone.","Grating beats double-slit for λ: brighter, sharper maxima, easy angle measurement."],
oos:"<b>Beyond syllabus:</b> X-ray crystallography is diffraction with λ ≈ atomic spacing — how DNA's helix was confirmed."}},
{id:"U2T3", name:"Particle Nature of Light & Spectra", tags:"photoelectric photons planck threshold spectra quantum",
notes:{lede:"Light is also a particle: photons, the photoelectric effect, Planck's constant and line spectra — wave–particle duality begins.",
points:[
"<b>Photon:</b> packet of light energy <b>E = hf = hc/λ</b>. h = 6.63×10⁻³⁴ J s, c = 3.00×10⁸ m s⁻¹.",
"<b>Photoelectric effect:</b> electrons (photoelectrons) emitted from a metal surface only if f > <b>threshold frequency f₀</b> — one photon ejects one electron, instantly, however dim the light.",
"<b>Einstein: hf = Φ + E<sub>k,max</sub></b> — photon energy = work function + max electron KE. Φ = hf₀.",
"<b>Stopping potential V<sub>s</sub>:</b> E<sub>k,max</sub> = eV<sub>s</sub>. Graph of E<sub>k,max</sub> vs f: gradient = h, x-intercept = f₀, y-intercept = −Φ.",
"<b>Wave theory fails:</b> it predicts any frequency works if bright enough, plus a time delay — neither observed. Quantum theory explains threshold + instant emission.",
"<b>Line spectra:</b> hot gas emits discrete lines (emission spectrum); cool gas absorbs the same lines from white light (absorption spectrum) — each element's fingerprint.",
"<b>Electrons in atoms</b> occupy discrete energy levels; photons emitted/absorbed when electrons jump: <b>ΔE = hf</b>. Bigger jump = higher f (bluer).",
"<b>Core practical:</b> LED threshold voltages — eV = hf per colour; plot V vs f, gradient = h/e → finds h."],
formulas:[{e:"E = hf = hc/λ",w:"photon energy"},{e:"hf = Φ + Eₖₘₐₓ",w:"photoelectric equation"},{e:"Eₖₘₐₓ = eVₛ",w:"stopping potential"}],
defs:[{t:"Work function Φ",d:"Minimum energy needed to release an electron from a metal surface."},{t:"Threshold frequency",d:"Minimum light frequency that can eject photoelectrons (Φ = hf₀)."}],
worked:{q:"Light of 6.0×10¹⁴ Hz hits metal (Φ = 2.3 eV). Max KE of electrons?",steps:["hf = 6.63×10⁻³⁴ × 6.0×10¹⁴ = 3.98×10⁻¹⁹ J = 2.48 eV.","Eₖ = 2.48 − 2.30 = 0.18 eV = 2.9×10⁻²⁰ J.","Just above threshold — slow electrons."]},
mistakes:["Mixing eV and J: always convert (1 eV = 1.60×10⁻¹⁹ J) before adding to hf in joules.","Thinking brighter light ejects faster electrons — brightness = MORE electrons, frequency = FASTER electrons.","Forgetting one photon ↔ one electron in explanations."],
tips:["The Eₖ vs f graph question is asked constantly: gradient = h always.","'Explain using quantum theory' → mention photons, one-to-one interaction, threshold."],
oos:"<b>Beyond syllabus:</b> de Broglie gave matter waves too (λ = h/mv) — electrons diffract, which is why electron microscopes resolve atoms."}},
{id:"U2T4", name:"Electric Circuits", tags:"circuits ohm resistance emf internal potential divider series parallel",
notes:{lede:"Current, voltage and resistance: Ohm's law, IV characteristics, series/parallel, emf, internal resistance and potential dividers.",
points:[
"<b>Current I = ΔQ/Δt</b> — charge per second (A). 1 A = 1 C s⁻¹. Conventional current flows + to −; electrons drift − to +.",
"<b>Potential difference</b> = energy per unit charge: <b>V = W/Q</b>. <b>Resistance R = V/I</b> (Ω).",
"<b>Ohm's law:</b> V ∝ I at constant temperature (metallic conductor). <b>Ohmic</b> = straight IV through origin.",
"<b>IV characteristics:</b> filament lamp — curve flattens (resistance ↑ as hotter); diode — conducts one way only after ~0.6 V; thermistor — resistance FALLS as temperature rises (NTC); LDR — resistance falls with light intensity.",
"<b>Series:</b> same current, pd splits, R<sub>total</sub> = R₁ + R₂. <b>Parallel:</b> same pd, current splits, 1/R = 1/R₁ + 1/R₂.",
"<b>Power: P = VI = I²R = V²/R</b>. Energy: E = Pt = VIt.",
"<b>emf ℰ:</b> energy per charge supplied by the source. <b>Terminal pd V = ℰ − Ir</b> — some voltage 'lost' across internal resistance r.",
"<b>Core practical:</b> ℰ and r — vary R, record V and I, plot V vs I: gradient = −r, intercept = ℰ.",
"<b>Potential divider: V<sub>out</sub> = V<sub>in</sub> × R₂/(R₁+R₂)</b> — voltage splits in proportion to resistance. Basis of sensor circuits (thermistor/LDR + fixed R).",
"<b>Kirchhoff:</b> current in = current out at a junction; sum of emfs = sum of pds round a loop."],
formulas:[{e:"I = ΔQ/Δt",w:"current"},{e:"R = V/I",w:"resistance"},{e:"P = VI = I²R",w:"electrical power"},{e:"V = ℰ − Ir",w:"terminal pd"},{e:"Vₒᵤₜ = Vᵢₙ·R₂/(R₁+R₂)",w:"potential divider"}],
defs:[{t:"Electromotive force",d:"Energy transferred per unit charge from chemical/other stores by the source (V)."},{t:"Internal resistance",d:"Resistance inside the source, causing lost volts Ir when current flows."}],
worked:{q:"A cell ℰ = 1.5 V, r = 0.4 Ω drives 0.50 A through a bulb. Find terminal pd and bulb resistance.",steps:["V = ℰ − Ir = 1.5 − 0.5×0.4 = 1.3 V.","R = V/I = 1.3/0.5 = 2.6 Ω.","Lost volts = 0.2 V warm the cell."]},
mistakes:["Using ℰ instead of terminal V for the external circuit — subtract Ir first.","Adding parallel resistors by R₁+R₂ — use reciprocals.","Confusing emf (source property) with terminal pd (depends on current)."],
tips:["Redraw messy circuits: identify series vs parallel branches first.","Sensor question? Write the divider equation, then state which R changes and which way Vout moves."],
oos:"<b>Beyond syllabus:</b> superconductors (r = 0 below critical T) make lossless magnets — MRI scanners and maglev use them."}}
]},
{id:"U3", code:"WPH13", short:"Unit 3", title:"Practical Skills in Physics I", level:"AS", time:"1 h 20 min", marks:50, weight:"10% of IAL",
topics:[
{id:"U3T1", name:"Planning, Errors & Uncertainties", tags:"practical uncertainty error percentage repeat measurements",
notes:{lede:"How to plan experiments and handle data: variables, errors, uncertainties and how they combine — the backbone of WPH13.",
points:[
"<b>Independent variable</b> (you change), <b>dependent</b> (you measure), <b>controls</b> (kept constant for a fair test).",
"<b>Random errors</b> scatter readings about the true value (reduce by repeats + average). <b>Systematic errors</b> shift all readings one way — e.g. zero error (fix by calibration).",
"<b>Uncertainty:</b> analogue scale ± half smallest division… IAL accepts ± smallest division or half — state your assumption. Digital: ±1 in last digit (sometimes ±1 digit either side).",
"<b>% uncertainty = (absolute uncertainty / reading) × 100.</b> Small readings have BIG % uncertainty — measure large quantities (time 20 oscillations!).",
"<b>Combining:</b> adding/subtracting → ADD absolute uncertainties. Multiplying/dividing → ADD % uncertainties. Powers: ×n the % (e.g. T² doubles the %).",
"<b>Precision</b> = scatter of repeats (small random error). <b>Accuracy</b> = closeness to true value (small systematic error). Don't confuse them!",
"<b>Validity:</b> controls + correct method measuring what you claim. <b>Reliability:</b> repeatable — repeats + consistent results.",
"Always: repeats (≥3), range of values (≥6), appropriate instrument (resolution matches), risk assessment, preliminary work."],
formulas:[{e:"%U = U/x × 100",w:"percentage uncertainty"},{e:"U(a+b)=Ua+Ub",w:"adding absolutes"},{e:"%(ab/c)=%a+%b+%c",w:"multiply/divide %"}],
defs:[{t:"Uncertainty",d:"Range within which the true value is expected to lie, from instrument limits and scatter."},{t:"Zero error",d:"Systematic error where an instrument reads non-zero with zero input."}],
worked:{q:"T = 1.24 ± 0.02 s for one oscillation (timed 20 in 24.8 ± 0.4 s). % uncertainty in T²?",steps:["%U in T = 0.02/1.24 × 100 = 1.6%.","Squaring → double: %U in T² = 3.2%.","Timing 20 swings cut %U by 20× — always time many oscillations."]},
mistakes:["Calling everything 'human error' — name the actual error (parallax, reaction time, zero error).","Adding % uncertainties when adding quantities — add ABSOLUTES for +/−.","Saying 'repeat to remove anomalies' — repeats IDENTIFY anomalies; you exclude them then average the rest."],
tips:["'Suggest improvements' → bigger sample/range, datalogger (removes reaction time), finer resolution, control a named variable.","'Justify choice of instrument' → compare % uncertainties of the options."],
oos:"<b>Beyond syllabus:</b> professional labs quote 'standard uncertainty' (1σ ≈ 68% confidence) and combine in quadrature (√(a²+b²)) — IAL uses simple addition."}},
{id:"U3T2", name:"Graphs, Gradients & Core Practicals I", tags:"graphs gradient intercept core practical linearise",
notes:{lede:"Turning data into physics: best-fit lines, gradients, intercepts, linearisation and the AS core practicals examiners love.",
points:[
"<b>Plot independent (x) vs dependent (y).</b> Label axes with quantity AND unit. Use sensible scales (1, 2, 5 ×10ⁿ) covering >half the paper.",
"<b>Best-fit line:</b> balance points above/below — straight only if relationship is linear; smooth curve otherwise. Error bars show uncertainty.",
"<b>Gradient = Δy/Δx</b> using a LARGE triangle (≥ half the line), read from the LINE not data points. Intercept read at x = 0.",
"<b>Linearise:</b> if y ∝ x², plot y vs x² → straight line, gradient = constant. Common: T² vs m (springs), T² vs L (pendulum), V vs I (ℰ, r).",
"<b>AS core practicals to know cold:</b> ① g by free-fall ② E of a wire ③ harmonics on a string ④ λ by grating/double-slit ⑤ h with LEDs ⑥ ℰ and r ⑦ thermistor calibration.",
"<b>Practical Q structure:</b> describe method (what varied/measured/how) → control variables → how data gives the answer (graph) → safety.",
"<b>Anomalous point:</b> circle it, ignore for the line, mention a likely cause (misreading, control slipped)."],
formulas:[{e:"y = mx + c",w:"gradient m, intercept c"},{e:"T = 2π√(m/k)",w:"spring → T² vs m"},{e:"T = 2π√(L/g)",w:"pendulum → T² vs L"}],
defs:[{t:"Linearisation",d:"Plotting transformed variables so a non-linear relation becomes a straight line."},{t:"Anomalous result",d:"Reading that does not fit the trend, likely from a measurement error."}],
worked:{q:"T² vs m for a spring gives gradient 3.9 s² kg⁻¹. Find k.",steps:["T = 2π√(m/k) → T² = (4π²/k)m, so gradient = 4π²/k.","k = 4π²/3.9 = 10.1 N m⁻¹.","Intercept ≈ 0 confirms no systematic offset."]},
mistakes:["Drawing dot-to-dot instead of a best-fit line.","Using data points (not the line) for gradient — loses the mark.","Forgetting units on gradient (e.g. s² kg⁻¹)."],
tips:["If asked to 'show the relationship is...' — linearise and argue the straight line through origin proves it.","Know ONE method for g (electromagnet + trapdoor/timer) in full detail."],
oos:"<b>Beyond syllabus:</b> log–log plots linearise power laws (y = kxⁿ): gradient = n — used across real research."}}
]},
{id:"U4", code:"WPH14", short:"Unit 4", title:"Further Mechanics, Fields & Particles", level:"A2", time:"1 h 45 min", marks:90, weight:"20% of IAL",
topics:[
{id:"U4T1", name:"Momentum, Circular Motion & Gravitation", tags:"momentum collisions circular centripetal gravitation orbits kepler",
notes:{lede:"A2 mechanics: momentum in 2D, circular motion and Newton's gravitation — from snooker balls to satellites.",
points:[
"<b>Momentum conservation in 2D:</b> resolve into perpendicular components — momentum conserved in EACH direction (no external impulse).",
"<b>Elastic collision:</b> momentum AND kinetic energy conserved (relative speed of approach = separation). <b>Inelastic:</b> momentum conserved, some KE → heat/sound. Totally inelastic = stick together.",
"<b>Circular motion:</b> velocity direction changes constantly → accelerating towards centre even at constant speed.",
"<b>Centripetal force F = mv²/r = mω²r</b>, acceleration <b>a = v²/r = ω²r</b> towards centre. ω = 2πf = 2π/T = v/r.",
"<b>Centripetal force is NOT a new force</b> — it's provided BY tension, friction, gravity, normal reaction etc. Never add it as an extra arrow.",
"<b>Newton's gravitation: F = Gm₁m₂/r²</b> (inverse square). <b>g = GM/r²</b>; at Earth's surface g = 9.81 N kg⁻¹.",
"<b>Orbits:</b> gravity provides centripetal force: GMm/r² = mv²/r → <b>v² = GM/r</b>, <b>T² ∝ r³</b> (Kepler's 3rd law).",
"<b>Geostationary orbit:</b> T = 24 h, above equator, same direction as Earth's spin, r ≈ 42,400 km — stays over one spot (comms/TV)."],
formulas:[{e:"F = mv²/r",w:"centripetal force"},{e:"ω = 2π/T",w:"angular velocity"},{e:"F = Gm₁m₂/r²",w:"Newton's gravitation"},{e:"T² = 4π²r³/GM",w:"orbital period"}],
defs:[{t:"Centripetal acceleration",d:"Acceleration towards the centre of circular motion, a = v²/r."},{t:"Geostationary satellite",d:"Satellite with 24 h period above the equator, fixed over one point on Earth."}],
worked:{q:"Show that a satellite at r = 4.24×10⁷ m has T = 24 h. (M_Earth = 5.97×10²⁴ kg)",steps:["T = 2π√(r³/GM) = 2π√((4.24×10⁷)³/(6.67×10⁻¹¹ × 5.97×10²⁴)).","r³ = 7.62×10²²; GM = 3.98×10¹⁴; ratio = 1.91×10⁸; √ = 1.38×10⁴.","T = 2π × 1.38×10⁴ = 86,800 s ≈ 24.1 h ✓"]},
mistakes:["Adding 'centripetal force' as an extra force in free-body diagrams.","Using Earth's radius instead of ORBITAL radius (r = R_earth + altitude).","Thinking astronauts float because 'no gravity' — gravity provides their centripetal acceleration (freefall)."],
tips:["Banked-track / roundabout Qs: always state which force provides the centripetal force.","Show-that questions: keep 3+ s.f. through working, compare at the end."],
oos:"<b>Beyond syllabus:</b> Einstein reframed gravity as curved spacetime; GPS satellites must correct for BOTH special and general relativity."}},
{id:"U4T2", name:"Electric Fields & Capacitors", tags:"electric field capacitance capacitors charging discharging",
notes:{lede:"Fields around charges and storing charge: field strength, uniform vs radial fields, and capacitor charge/discharge.",
points:[
"<b>Field strength E = F/Q</b> (N C⁻¹ or V m⁻¹) — force per unit positive charge. Field lines: + to −, never cross, closer = stronger.",
"<b>Uniform field (parallel plates): E = V/d</b> — parallel, equally spaced lines.",
"<b>Radial field (point charge): E = kQ/r²</b>, k = 1/4πε₀. Inverse-square, like gravity.",
"<b>Charged particles in fields:</b> F = EQ → a = EQ/m. Electron beams deflect parabolically (like projectiles!) — basis of oscilloscopes.",
"<b>Capacitance C = Q/V</b> (F). Parallel-plate: C = ε₀A/d — bigger area, smaller gap → bigger C.",
"<b>Energy stored: W = ½QV = ½CV² = ½Q²/C</b> = area under Q–V graph.",
"<b>Charging:</b> current/charge rise/fall exponentially. <b>Time constant τ = RC</b> — time to fall to 1/e (≈37%); ~5τ to fully charge/discharge.",
"<b>Discharge: Q = Q₀e^(−t/RC)</b>, I and V follow the same curve. Larger R or C → slower discharge (bigger τ)."],
formulas:[{e:"E = F/Q",w:"field strength"},{e:"E = V/d",w:"uniform field"},{e:"C = Q/V",w:"capacitance"},{e:"W = ½QV",w:"stored energy"},{e:"τ = RC",w:"time constant"}],
defs:[{t:"Electric field strength",d:"Force per unit positive charge at a point in the field."},{t:"Time constant",d:"RC — time for discharging Q/V/I to fall to 1/e of its initial value."}],
worked:{q:"A 470 µF capacitor charged to 12 V discharges through 10 kΩ. Initial current and time to reach ~37%?",steps:["Q₀ = CV = 470×10⁻⁶ × 12 = 5.64×10⁻³ C.","I₀ = V₀/R = 12/10,000 = 1.2 mA.","τ = RC = 10⁴ × 470×10⁻⁶ = 4.7 s — that's the 37% time."]},
mistakes:["µF/nF/pF conversions: 1 µF = 10⁻⁶ F — write it out every time.","Saying a capacitor 'blocks DC forever' — it charges then current stops; current flows DURING charging.","Confusing field strength E with energy — check units (V m⁻¹ vs J)."],
tips:["Discharge-graph Qs: tangent at t=0 gives I₀ (gradient = dQ/dt = I).","Compare τ values to rank discharge speeds — no full calculation needed."],
oos:"<b>Beyond syllabus:</b> supercapacitors (thousands of farads) now power buses and smooth renewable grids."}},
{id:"U4T3", name:"Magnetic Fields & EM Induction", tags:"magnetic fleming motor induction faraday lenz flux",
notes:{lede:"Magnetism and making electricity: Fleming's left-hand rule, the motor effect, then Faraday and Lenz for induction.",
points:[
"<b>Magnetic field:</b> region where magnetic materials / moving charges feel force. Direction: N to S outside a magnet.",
"<b>Motor effect: F = BIL sinθ</b> — force on current-carrying wire (max when ⊥). <b>Fleming's left-hand rule:</b> First finger = Field, seCond = Current, thuMb = Motion.",
"<b>Force on moving charge: F = BQv</b> (⊥) — deflects beams into circular paths; with F = mv²/r → <b>r = mv/BQ</b> (used in mass/velocity selectors).",
"<b>Magnetic flux Φ = BA cosθ</b> (Wb). <b>Flux linkage = NΦ</b> for a coil.",
"<b>Faraday's law: induced emf = rate of change of flux linkage: ℰ = −NΔΦ/Δt.</b> Change B, A, angle or N — any change induces emf.",
"<b>Lenz's law:</b> induced current opposes the CHANGE causing it (the minus sign) — conservation of energy. Push a magnet in → coil repels it.",
"<b>AC generator:</b> rotating coil in B field → sinusoidal emf, ℰ = BANω sin(ωt). Slip rings (AC) vs split-ring commutator (DC motor).",
"<b>Transformers (mutual induction):</b> AC in primary → changing flux → emf in secondary. <b>Vₛ/Vₚ = Nₛ/Nₚ</b>; ideal: P in = P out → <b>VₚIₚ = VₛIₛ</b>."],
formulas:[{e:"F = BIL",w:"motor effect (⊥)"},{e:"F = BQv",w:"force on moving charge"},{e:"ℰ = NΔΦ/Δt",w:"Faraday's law"},{e:"Vₛ/Vₚ = Nₛ/Nₚ",w:"transformer"}],
defs:[{t:"Magnetic flux linkage",d:"NΦ — flux × turns; its rate of change equals induced emf."},{t:"Lenz's law",d:"Induced effects oppose the change producing them."}],
worked:{q:"A 200-turn coil of area 5.0×10⁻³ m² has flux through it fall from 0.020 to 0 Wb in 0.10 s. Induced emf?",steps:["Δ(NΦ) = 200 × 0.020 = 4.0 Wb-turns.","ℰ = Δ(NΦ)/Δt = 4.0/0.10 = 40 V.","Direction: current tries to keep the flux up (Lenz)."]},
mistakes:["Forgetting the N (turns) in Faraday calculations.","Left hand (motor/force) vs right hand (generator/induced current) — pick by what's asked.","Saying induction needs movement — it needs CHANGING flux (AC transformer has no moving parts)."],
tips:["'Explain the shape of the emf graph' → link each feature to rate of change of flux (steep B–t = big emf).","National grid Q: high V → low I → low I²R losses; step-up then step-down."],
oos:"<b>Beyond syllabus:</b> induction hobs, Maglev braking and guitar pickups are all Faraday in disguise."}},
{id:"U4T4", name:"Nuclear & Particle Physics", tags:"nucleus alpha scattering quarks leptons standard model accelerators",
notes:{lede:"Inside the atom: Rutherford scattering, the nucleus, quarks and leptons — the Standard Model zoo.",
points:[
"<b>Rutherford alpha scattering:</b> most α pass through (atom mostly empty), few deflect, tiny fraction bounce back → <b>small, dense, positive nucleus</b> containing most mass.",
"<b>Closest approach:</b> α KE → electrostatic PE: r_min ≈ 2kZe²/(KE) ~ 10⁻¹⁴ m — upper limit on nuclear radius. Nuclei ~ 10⁻¹⁴ m, atoms ~ 10⁻¹⁰ m.",
"<b>Nuclear radius: R = r₀A^(1/3)</b>, r₀ ≈ 1.2 fm. Density is enormous and roughly constant (~10¹⁷ kg m⁻³).",
"<b>Fundamental particles:</b> <b>quarks</b> (up +2/3, down −1/3; make protons uud & neutrons udd) and <b>leptons</b> (electrons, neutrinos). Hadrons = quark combos (baryons qqq, mesons q-qbar).",
"<b>Forces:</b> strong (holds nucleus, very short range), weak (β decay), electromagnetic, gravity. Exchange particles: gluons, W/Z, photons, gravitons (hypothetical).",
"<b>Annihilation:</b> particle + antiparticle → photons (E = mc²). <b>Pair production:</b> photon → particle + antiparticle (needs ≥ 2mc²).",
"<b>Accelerators:</b> electric fields accelerate (LINAC), magnetic fields steer/bend (cyclotron, synchrotron); collide → E=mc² creates new particles; detectors track curvature (r = mv/BQ) to find momentum/charge."],
formulas:[{e:"E = mc²",w:"mass–energy"},{e:"R = r₀A¹ᐟ³",w:"nuclear radius"},{e:"r = mv/BQ",w:"curvature in B field"}],
defs:[{t:"Hadron",d:"Particle made of quarks, feeling the strong force (e.g. proton, neutron, pion)."},{t:"Lepton",d:"Fundamental particle not feeling the strong force (e.g. electron, neutrino)."}],
worked:{q:"Estimate nuclear density. (r₀ = 1.2 fm, m_nucleon = 1.67×10⁻²⁷ kg)",steps:["R = r₀A^⅓ → V = 4/3πr₀³A; mass = A×1.67×10⁻²⁷.","ρ = m/V = 1.67×10⁻²⁷/(4/3π(1.2×10⁻¹⁵)³) ≈ 2.3×10¹⁷ kg m⁻³.","Independent of A — all nuclei ~equally dense."]},
mistakes:["Saying the strong force 'overcomes repulsion between protons AND neutrons' — neutrons are neutral; it's p–p repulsion it beats.","Calling protons fundamental — they're hadrons (uud).","Forgetting antiparticles have opposite charge but same mass."],
tips:["Conservation laws in decays: charge, baryon number, lepton number, energy-momentum — check all four.","Rutherford conclusions: match EACH observation to its deduction explicitly."],
oos:"<b>Beyond syllabus:</b> the Higgs boson (found at CERN, 2012) explains how particles get mass — the last Standard Model piece."}}
]},
{id:"U5", code:"WPH15", short:"Unit 5", title:"Thermo, Radiation, Oscillations & Cosmology", level:"A2", time:"1 h 45 min", marks:90, weight:"20% of IAL",
topics:[
{id:"U5T1", name:"Thermodynamics & Ideal Gases", tags:"kinetic theory ideal gas internal energy shc slh boyle",
notes:{lede:"Heat and gases: temperature, internal energy, specific heats and the kinetic theory linking microscopic motion to pressure.",
points:[
"<b>Internal energy:</b> sum of random kinetic + potential energies of ALL molecules. Heating raises KE (temperature); melting/boiling raises PE (no T change).",
"<b>Specific heat capacity: E = mcΔT</b> — energy per kg per kelvin. <b>Specific latent heat: E = mL</b> — energy per kg to change state (fusion/vaporisation).",
"<b>Absolute zero:</b> 0 K = −273.15 °C — minimum internal (KE) energy. Always use kelvin in gas laws.",
"<b>Ideal gas: pV = NkT = nRT</b>. k = 1.38×10⁻²³ J K⁻¹, R = 8.31 J mol⁻¹ K⁻¹, N_A = 6.02×10²³. Boyle (pV = const), Charles (V/T), Pressure (p/T) are special cases.",
"<b>Kinetic theory assumptions:</b> large number of molecules • random motion • negligible volume • no intermolecular forces except collisions • elastic collisions • collision time negligible.",
"<b>Derivation result: pV = ⅓Nm⟨c²⟩</b> → average molecular KE: <b>½m⟨c²⟩ = 3kT/2</b> — temperature IS average molecular kinetic energy.",
"<b>Core practicals:</b> SHC of a metal block (heater + thermometer, E = VIt); SLH of ice/steam; thermistor calibration as thermostat.",
"Real gases deviate at high pressure / low temperature (molecular volume + attractions matter)."],
formulas:[{e:"E = mcΔT",w:"heating"},{e:"E = mL",w:"change of state"},{e:"pV = NkT",w:"ideal gas"},{e:"½m⟨c²⟩ = 3kT/2",w:"mean molecular KE"}],
defs:[{t:"Internal energy",d:"Total random kinetic + potential energy of a substance's particles."},{t:"Absolute zero",d:"0 K — temperature at which molecules have minimum kinetic energy."}],
worked:{q:"Find rms speed of N₂ at 300 K. (m = 4.65×10⁻²⁶ kg)",steps:["½m⟨c²⟩ = 3kT/2 → ⟨c²⟩ = 3kT/m = 3×1.38×10⁻²³×300/4.65×10⁻²⁶.","⟨c²⟩ = 2.67×10⁵ → c_rms = 517 m s⁻¹.","Faster than sound — molecules are quick but collide constantly."]},
mistakes:["Using °C in pV = NkT — convert to kelvin first (+273).","Using N (molecules) with R, or n (moles) with k — match the constant.","Saying temperature measures internal energy — it measures AVERAGE KE only."],
tips:["KE-temperature link (½m⟨c²⟩ = 3kT/2) is examined almost every session — memorise it.","For SHC method Qs: insulation, wait for max T (after heater off), repeat readings."],
oos:"<b>Beyond syllabus:</b> the Maxwell–Boltzmann speed distribution explains evaporation (fast tail escapes) and reaction rates (Chem T9!)."}},
{id:"U5T2", name:"Radioactivity & Nuclear Energy", tags:"radioactivity half life decay binding energy fission fusion",
notes:{lede:"Unstable nuclei: alpha/beta/gamma, half-life and exponential decay, binding energy, fission and fusion.",
points:[
"<b>α:</b> helium nucleus (2p+2n) — highly ionising, range ~cm in air, stopped by paper. <b>β⁻:</b> fast electron from neutron decay — medium, stopped by aluminium. <b>γ:</b> EM photon — weakly ionising, needs lead/concrete.",
"<b>Decay is spontaneous and random</b> — cannot predict which nucleus or when; only probabilities. Unaffected by temperature/pressure/chemistry.",
"<b>Activity A = λN</b> (Bq = decays s⁻¹). <b>N = N₀e^(−λt)</b>, A = A₀e^(−λt). <b>Half-life: λ = ln2 / t½.</b>",
"<b>Measure t½:</b> record corrected count rate vs time, find time to halve (repeat for reliability), or plot ln(A) vs t → gradient = −λ.",
"<b>Mass defect Δm:</b> nucleus lighter than its nucleons — missing mass = <b>binding energy E = Δmc²</b> holding it together.",
"<b>Binding energy per nucleon curve:</b> peaks at iron-56 (~8.8 MeV). Fission (heavy splits) and fusion (light joins) both move UP the curve → release energy.",
"<b>Fission:</b> U-235 + n → two daughters + 2–3 neutrons + energy; chain reaction controlled by moderator (slows neutrons) + control rods (absorb neutrons) in reactors.",
"<b>Fusion:</b> H → He in stars (needs extreme T + pressure to beat repulsion); releases more per kg than fission; clean fuel but hard to contain (tokamaks, lasers)."],
formulas:[{e:"A = λN",w:"activity"},{e:"λ = ln2/t½",w:"decay constant"},{e:"N = N₀e^(−λt)",w:"decay law"},{e:"E = Δmc²",w:"binding energy"}],
defs:[{t:"Half-life",d:"Mean time for half the undecayed nuclei in a sample to decay (also: time for activity to halve)."},{t:"Binding energy",d:"Energy needed to separate a nucleus into its individual nucleons (equivalently, released on formation)."}],
worked:{q:"A source has t½ = 6.0 h and initial activity 800 Bq (corrected). Activity after 24 h?",steps:["24 h = 4 half-lives → A = 800/2⁴ = 800/16 = 50 Bq.","Or λ = ln2/6 = 0.1155 h⁻¹; A = 800e^(−0.1155×24) = 50 Bq.","Always subtract background count first in real experiments."]},
mistakes:["Saying 'after 2 half-lives nothing is left' — ¼ remains; decay never reaches zero.","Using count rate without subtracting background.","Reading binding-energy Qs backwards: energy released = INCREASE in total BE (products more bound)."],
tips:["ln-graph Qs: gradient = −λ is a gift — then t½ = ln2/λ.","Fission vs fusion: state which nuclei, why energy releases (BE/nucleon rises), one pro/con each."],
oos:"<b>Beyond syllabus:</b> carbon-14 dating (t½ = 5730 y) and PET scans (β⁺ annihilation → two γ) are decay laws in action."}},
{id:"U5T3", name:"Oscillations (SHM, Damping & Resonance)", tags:"shm simple harmonic damping resonance frequency",
notes:{lede:"To-and-fro motion: simple harmonic motion, energy in oscillations, damping and the resonance that destroys bridges.",
points:[
"<b>SHM definition:</b> acceleration ∝ −displacement from equilibrium (a = −ω²x) — always towards equilibrium. Examples: spring, pendulum (small angles).",
"<b>Solutions: x = A sin(ωt)</b> (or cos), <b>v = ±ω√(A²−x²)</b>, v_max = Aω, a_max = Aω². ω = 2πf.",
"<b>Energy:</b> total = ½mω²A² = const (undamped), swapping between KE (max at equilibrium) and PE (max at extremes).",
"<b>Spring: T = 2π√(m/k).</b> <b>Pendulum: T = 2π√(L/g)</b> (small angles only).",
"<b>Damping:</b> removes energy (friction/drag) → amplitude decays exponentially. Light (slow decay), heavy, critical (fastest return, no overshoot — car suspension), overdamped (slow creep).",
"<b>Free oscillation</b> = at natural frequency. <b>Forced:</b> driver imposes its frequency. <b>Resonance:</b> driver f = natural f → MAX amplitude (driver feeds energy in phase each cycle).",
"<b>Resonance examples:</b> breaking glass with sound, Tacoma bridge, tuning circuits (radio), MRI. Damping WIDENS and LOWERS the resonance peak.",
"<b>Core practical:</b> mass on spring — time 20 oscillations for several m, T² vs m → k; or resonance with known masses to find unknown mass."],
formulas:[{e:"a = −ω²x",w:"SHM defining equation"},{e:"x = A sin(ωt)",w:"displacement"},{e:"T = 2π√(m/k)",w:"mass–spring"},{e:"T = 2π√(L/g)",w:"pendulum"}],
defs:[{t:"Simple harmonic motion",d:"Oscillation with acceleration proportional to and opposite to displacement from equilibrium."},{t:"Resonance",d:"Large-amplitude oscillation when driven at the system's natural frequency."}],
worked:{q:"A 0.20 kg mass on a spring oscillates with A = 3.0 cm, f = 2.5 Hz. Max speed and total energy?",steps:["ω = 2π×2.5 = 15.7 rad s⁻¹.","v_max = Aω = 0.030×15.7 = 0.47 m s⁻¹.","E = ½mv²_max = ½×0.20×0.47² = 0.022 J."]},
mistakes:["Using degrees in ωt — SHM maths needs radians.","Saying damping changes the frequency much — light damping barely changes f, it kills amplitude.","Confusing natural frequency with resonant frequency of the DRIVER."],
tips:["Sketch x–t, v–t, a–t together: v leads x by 90°, a is inverted x (antiphase).","'Show motion is SHM' → prove a ∝ −x with data or algebra."],
oos:"<b>Beyond syllabus:</b> resonance makes quartz watches tick (piezoelectric crystal) and lets opera singers smash glasses."}},
{id:"U5T4", name:"Astrophysics & Cosmology", tags:"stars hubble redshift big bang doppler HR luminosity",
notes:{lede:"The Universe: stars, Doppler redshift, Hubble's law and the Big Bang — plus the fate of everything.",
points:[
"<b>Doppler effect:</b> receding source → observed λ longer (<b>redshift</b>). <b>z = Δλ/λ = v/c</b> (v ≪ c). Approaching → blueshift.",
"<b>Hubble's law: v = H₀d</b> — recession velocity ∝ distance. H₀ ≈ 70 km s⁻¹ Mpc⁻¹. Distant galaxies recede faster.",
"<b>Age of universe ≈ 1/H₀</b> ≈ 14 billion years (assumes constant expansion rate — an estimate).",
"<b>Big Bang evidence:</b> ① Hubble redshift (expansion) ② <b>CMB</b> — 2.7 K microwave glow in all directions (cooled early-universe radiation) ③ H:He abundance ratio (~3:1) matches fusion predictions.",
"<b>Stars:</b> luminosity L = 4πr²σT⁴ (Stefan–Boltzmann); hotter = bluer (Wien). <b>H–R diagram:</b> main sequence (H→He fusion) → red giant → white dwarf (small stars) or supernova → neutron star/black hole (massive stars).",
"<b>Standard candles</b> (Type Ia supernovae — same peak luminosity) measure huge distances: brightness ∝ 1/d².",
"<b>Dark matter:</b> galaxies rotate too fast for visible mass — unseen mass (~27%). <b>Dark energy:</b> expansion is ACCELERATING (distant supernovae dimmer than expected) — ~68% of the universe.",
"<b>Fate:</b> accelerating expansion → 'Big Freeze' (heat death) is the current best bet; Big Crunch needs expansion to reverse."],
formulas:[{e:"z = Δλ/λ = v/c",w:"redshift"},{e:"v = H₀d",w:"Hubble's law"},{e:"t ≈ 1/H₀",w:"age estimate"},{e:"L = 4πr²σT⁴",w:"stellar luminosity"}],
defs:[{t:"Redshift",d:"Increase in observed wavelength from a receding source; z = Δλ/λ."},{t:"Standard candle",d:"Object of known luminosity used to find distance from observed brightness."}],
worked:{q:"A galaxy's H-α line (656 nm) appears at 700 nm. Recession speed and distance? (H₀ = 2.3×10⁻¹⁸ s⁻¹)",steps:["z = (700−656)/656 = 0.067 → v = zc = 0.067×3.0×10⁸ = 2.0×10⁷ m s⁻¹.","d = v/H₀ = 2.0×10⁷/2.3×10⁻¹⁸ = 8.7×10²⁴ m ≈ 280 Mpc.","Check: units of H₀ in s⁻¹ give d in metres directly."]},
mistakes:["Saying redshift means stars look red — it's a fractional shift of spectral LINES.","Forgetting H₀ unit conversions (km s⁻¹ Mpc⁻¹ → s⁻¹ needs Mpc → m).","Claiming the Big Bang was an explosion IN space — space itself expands (raisin-bread model)."],
tips:["'Evidence for the Big Bang' = three named pieces with one line each — easy 6 marks.","H–R diagram: learn the axes (L vs T, T backwards!) and the main-sequence position."],
oos:"<b>Beyond syllabus:</b> JWST sees galaxies from ~300 Myr after the Big Bang — and gravitational waves (2015) opened a whole new sense."}}
]},
{id:"U6", code:"WPH16", short:"Unit 6", title:"Practical Skills in Physics II", level:"A2", time:"1 h 20 min", marks:50, weight:"10% of IAL",
topics:[
{id:"U6T1", name:"A2 Practical Techniques & Planning", tags:"practical planning evaluation a2 experiment design",
notes:{lede:"Full A2 practical mastery: planning investigations from scratch, A2 core practicals and top-band evaluation.",
points:[
"<b>Plan structure (6-mark Qs):</b> ① quantity varied (range, ≥6 values) & measured (instrument + resolution) ② controls + HOW controlled ③ data analysis (graph/linearisation → answer) ④ safety + repeats.",
"<b>A2 core practicals:</b> momentum collisions (ICT tracking) • rate of fall / g • capacitor discharge (V–t → τ) • indent of materials? No — key ones: resonant frequencies (unknown mass), SHC/SLH, thermistor calibration, magnetic flux / induction, spectra.",
"<b>Resolution choice:</b> pick the instrument whose % uncertainty is smallest — show the comparison calculation.",
"<b>Systematic improvements:</b> dataloggers (remove reaction time), fiducial markers (oscillations), parallax avoidance (eye ⊥ scale), zero errors, insulation/lagging.",
"<b>Safety specifics:</b> lasers (never look into beam, warning signs), radioactive sources (tongs, distance, time, shielding, no food), heavy masses (toe protection, clamp stands), hot apparatus (gloves, cool before handling).",
"<b>Validity threats:</b> uncontrolled variables, small range, few points, large uncertainties, assumptions in the model (e.g. small-angle, no air resistance).",
"<b>Evaluation language:</b> % uncertainties → 'the largest uncertainty was… so the result is reliable/valid to ±…%'; suggest the improvement that targets THAT uncertainty."],
formulas:[{e:"%U total (×/÷)",w:"add % uncertainties"},{e:"gradient ±",w:"use worst-fit lines for U in gradient"}],
defs:[{t:"Worst-fit line",d:"Steepest/shallowest lines through error bars, giving uncertainty in gradient/intercept."},{t:"Preliminary work",d:"Trial run to choose range, check controls and estimate uncertainties before the full experiment."}],
worked:{q:"Plan: determine g using a pendulum (outline for full marks).",steps:["Vary L (0.2–1.0 m, ≥6 values); measure L (metre rule ±1 mm) and T (time 20 swings, stopwatch).","Control: small amplitude (<10°), same bob, draught-free; repeat each T twice.","Plot T² vs L; gradient = 4π²/g → g = 4π²/gradient; worst-fit lines for uncertainty.","Safety: secure clamp, clear swing zone; heavy bob wired safely."]},
mistakes:["Vague controls ('keep everything the same') — name the variable AND the method.","Forgetting the analysis step: method without the graph scores half marks.","Generic safety ('wear goggles') where irrelevant — match risk to apparatus."],
tips:["Learn 3 plans deeply: g-pendulum, capacitor τ, and one thermal (SHC/SLH) — they recycle yearly.","Always quantify: ranges, resolutions, repeat counts — numbers earn marks."],
oos:"<b>Beyond syllabus:</b> real metrology labs (like NPL) chase uncertainties of parts-per-billion — your ±2% keeps good company."}}
]}
]};
