/* Edexcel IAL Biology (YBI11) — syllabus content & revision notes (current spec) */
var SUBJECT_BIOLOGY = {
id:"biology", name:"Biology", icon:"🧬", color:"#34d399", qual:"YBI11",
desc:"Molecules, cells, transport, immunity, respiration, coordination & gene tech — WBI11 to WBI16.",
hubs:[
 {name:"📄 Save My Exams — IAL Biology past papers", url:"https://www.savemyexams.com/international-a-level/biology/edexcel/past-papers/", desc:"Every unit, QP + MS, all sessions Jan / Jun / Oct."},
 {name:"🏛️ Pearson Edexcel past paper finder", url:"https://qualifications.pearson.com/en/support/support-topics/exams/past-papers.html", desc:"Official WBI papers, mark schemes & examiner reports."},
 {name:"🧬 Chem-Bio — IAL Biology solved papers & notes", url:"https://www.chem-bio.info/ial-biology-chemistry-notes", desc:"Notes by unit and papers worked against the mark scheme."},
 {name:"📚 Physics & Maths Tutor", url:"https://www.physicsandmathstutor.com/", desc:"Notes, flashcards & topic questions for IAL Biology."}
],
units:[
{id:"U1", code:"WBI11", short:"Unit 1", title:"Molecules, Diet, Transport & Health", level:"AS", time:"1 h 30 min", marks:80, weight:"20% of IAL",
topics:[
{id:"U1T1", name:"Biological Molecules: Water, Carbs & Lipids", tags:"water carbohydrate lipid test benedict iodine emulsion monosaccharide",
notes:{lede:"Life's building blocks: why water is weird and wonderful, sugars, starch, cellulose and fats — plus the food tests.",
points:[
"<b>Water:</b> polar + H-bonding → solvent (metabolism/transport), high SHC (stable T), high latent heat (cooling), cohesive (xylem column), ice floats (insulates lakes), dense liquid (supports organisms).",
"<b>Monosaccharides:</b> glucose (α/β), fructose, galactose. <b>Disaccharides:</b> maltose (glu+glu), sucrose (glu+fru), lactose (glu+gal) — formed by <b>condensation</b> (glycosidic bond + H₂O); broken by <b>hydrolysis</b>.",
"<b>Starch (amylose + amylopectin):</b> energy store — coiled/branched, compact, insoluble (no osmotic effect). <b>Glycogen:</b> animal store, highly branched (fast release). <b>Cellulose:</b> β-glucose, straight chains, H-bonded microfibrils — immense tensile strength for walls.",
"<b>Lipids:</b> triglycerides (glycerol + 3 fatty acids, ester bonds) — energy store (more per g than carbs), insulation, buoyancy, protection. <b>Phospholipids:</b> glycerol + 2 fatty acids + phosphate — membranes. Saturated (no C=C, straight, solid fats) vs unsaturated (kinks, liquid oils).",
"<b>Tests:</b> reducing sugars — Benedict's, heat → brick-red ppt (non-reducing: boil with HCl, neutralise, re-test) • starch — iodine → blue-black • lipids — emulsion test (ethanol + water → white emulsion) • proteins — Biuret (purple)."],
formulas:[{e:"condensation ⇌ hydrolysis",w:"+H₂O breaks, −H₂O joins"},{e:"glycerol + 3FA → TG + 3H₂O",w:"triglyceride formation"}],
defs:[{t:"Glycosidic bond",d:"Covalent bond joining monosaccharides, formed by condensation."},{t:"Ester bond",d:"Bond joining fatty acids to glycerol in lipids (also in polyesters)."}],
worked:{q:"A food sample gives: brick-red with Benedict's after acid hydrolysis only; blue-black with iodine. Interpret.",steps:["Direct Benedict's negative → no reducing sugars free.","Positive after hydrolysis → NON-reducing sugar present (sucrose).","Iodine blue-black → starch also present."]},
mistakes:["Saying 'iodine turns blue-black' — iodine is BROWN; the STARCH–iodine complex is blue-black.","Calling sucrose a reducing sugar — it's non-reducing (needs hydrolysis first).","Confusing glycosidic (carbs) with peptide (proteins) and ester (lipids) bonds."],
tips:["Quantitative Benedict's: filter, dry, weigh ppt — or colorimeter (more Cu²⁺ reduced = less blue).","'Explain the structure–function link' → name feature + how it helps + why it matters."],
oos:"<b>Beyond syllabus:</b> lactose intolerance = missing lactase; the mutation for lifelong lactase is recent human evolution in action."}},
{id:"U1T2", name:"Diet, CVD & the Heart", tags:"diet cholesterol cvd heart cardiac cycle blood pressure",
notes:{lede:"Food, blood and the heart: balanced diets, cardiovascular disease and how the cardiac cycle moves blood.",
points:[
"<b>Balanced diet:</b> carbs (energy), lipids (energy/insulation), proteins (growth/repair — essential amino acids), fibre (peristalsis), water, vitamins/minerals, right ENERGY balance. Malnutrition = under OR over (obesity).",
"<b>BMI = mass/height²;</b> obesity raises risk of CVD, type-2 diabetes, some cancers. Waist–hip ratio also used.",
"<b>CVD chain:</b> high LDL cholesterol + high BP + smoking + inactivity → endothelium damage → LDL deposits → <b>atheroma/plaque</b> → narrower lumen → higher BP → clot risk → <b>thrombosis</b> → heart attack (coronary) / stroke (brain). HDL ('good') removes cholesterol to the liver.",
"<b>Smoking:</b> nicotine (addictive, ↑HR/BP), CO (binds Hb → less O₂), tar (carcinogens). Antioxidants/HDL from exercise/oily fish protect.",
"<b>Heart:</b> 4 chambers; <b>cardiac cycle:</b> atrial systole (AV valves open) → ventricular systole (AV shut — 'lub', semilunar open) → diastole (semilunar shut — 'dub', all fill). Valves prevent backflow; septum stops O₂ mixing.",
"<b>Initiation:</b> SAN (pacemaker) → atria contract → AVN delay → bundle of His → Purkyne tissue → ventricles contract base-up. Myogenic (no nerves needed).",
"<b>Vessels:</b> arteries (thick muscle/elastic — stretch + recoil, small lumen), arterioles (vasoconstriction control), capillaries (one-cell wall, slow flow, large total area — exchange), veins (wide, valves, thin walls)."],
formulas:[{e:"BMI = kg/m²",w:"body mass index"}],
defs:[{t:"Atheroma",d:"Fatty plaque deposit in an artery wall narrowing the lumen."},{t:"Myogenic",d:"Heart muscle contracting from internal signals (SAN), not nerve impulses."}],
worked:{q:"Explain how a blood clot in a coronary artery causes a heart attack.",steps:["Plaque narrows the coronary artery; rough surface triggers clotting (thrombosis).","Clot blocks blood → cardiac muscle downstream starved of O₂/glucose.","Muscle respires anaerobically then dies (myocardial infarction) — heart can't pump."]},
mistakes:["Saying 'cholesterol clogs arteries' — plaques form UNDER damaged endothelium (LDL + white cells + fibres).","Mixing up AV and semilunar valve timing — learn lub (AV shut) / dub (semilunar shut).","SAN vs AVN roles swapped — SAN starts, AVN delays."],
tips:["CVD Qs want the FULL chain: risk factor → damage → plaque → clot → consequence.","Correlation vs causation: 'studies show link' — mention controlling variables, large samples."],
oos:"<b>Beyond syllabus:</b> statins block cholesterol synthesis; stents + bypasses replumb hearts — prevention still beats cure."}},
{id:"U1T3", name:"Transport: Blood, Haemoglobin & Xylem/Phloem", tags:"haemoglobin oxygen dissociation tissue fluid xylem transpiration phloem",
notes:{lede:"Moving things around: haemoglobin's clever loading curve, tissue fluid and how plants lift water 100 metres.",
points:[
"<b>Blood:</b> RBCs (no nucleus, biconcave — Hb + diffusion), WBCs (defence), platelets (clotting), plasma (water, proteins, hormones, urea, dissolved CO₂).",
"<b>Haemoglobin:</b> 4 haem groups, each binds 1 O₂ → <b>cooperative binding</b> (1st O₂ makes the next easier) → sigmoid dissociation curve. Loads in lungs (high pO₂), unloads in respiring tissues (low pO₂).",
"<b>Bohr effect:</b> high CO₂ (→ H⁺, low pH) shifts curve RIGHT — Hb releases O₂ more easily in active tissues. Myoglobin (muscles) has higher affinity (left curve, stores O₂).",
"<b>CO₂ transport:</b> ~85% as HCO₃⁻ in plasma (carbonic anhydrase in RBCs: CO₂ + H₂O → H⁺ + HCO₃⁻; chloride shift), ~10% carbamino (on Hb), ~5% dissolved. H⁺ buffered by Hb (haemoglobinic acid).",
"<b>Tissue fluid:</b> high hydrostatic pressure at arteriole end forces fluid out (plasma proteins + cells stay); low pressure + osmosis at venule end draws most back; excess → lymph. Oedema if it fails.",
"<b>Xylem:</b> dead hollow vessels, lignified — water + minerals UP via <b>cohesion–tension</b> (transpiration pull; cohesion + adhesion). <b>Phloem:</b> living sieve tubes + companions — sugars BOTH ways via <b>translocation</b> (mass flow: loading → high pressure → unloading).",
"<b>Transpiration factors:</b> ↑temperature, ↑air movement, ↓humidity, ↑light (stomata open) → faster. Potometer measures UPTAKE (≈ transpiration). Xerophytes: thick cuticle, sunken stomata, rolled leaves, hairs."],
formulas:[{e:"CO₂ + H₂O ⇌ H⁺ + HCO₃⁻",w:"carbonic anhydrase reaction"}],
defs:[{t:"Bohr effect",d:"Rightward shift of the O₂ dissociation curve at high CO₂/low pH, aiding unloading."},{t:"Translocation",d:"Mass-flow movement of assimilates in phloem from source to sink."}],
worked:{q:"Why does fetal haemoglobin have a dissociation curve to the LEFT of adult Hb?",steps:["Left = higher affinity for O₂ at any pO₂.","Fetal Hb must 'steal' O₂ from maternal Hb across the placenta.","So it loads O₂ at the low pO₂ where maternal Hb unloads."]},
mistakes:["Reading the curve backwards — RIGHT shift = LOWER affinity (unloads easier).","Saying water 'is pushed up xylem by roots' alone — cohesion–tension (transpiration pull) is the main force.","Tissue fluid 'contains RBCs' — cells and plasma proteins stay in the capillary."],
tips:["Every dissociation-curve Q: quote pO₂ values + % saturation + affinity language.","Potometer: 'cut shoot UNDER WATER, vaseline seals, equilibrate' — method marks."],
oos:"<b>Beyond syllabus:</b> free-diving mammals (seals) pack myoglobin — the same curve logic, extreme edition."}},
{id:"U1T4", name:"Membranes, Proteins & DNA", tags:"membrane fluid mosaic diffusion osmosis active transport dna protein synthesis",
notes:{lede:"Cell boundaries and information: the fluid-mosaic membrane, transport across it, and DNA → protein.",
points:[
"<b>Fluid-mosaic membrane:</b> phospholipid bilayer (hydrophilic heads out, hydrophobic tails in) + intrinsic/extrinsic proteins (channels, carriers, receptors, enzymes) + cholesterol (stability/fluidity) + glycoproteins/glycolipids (recognition).",
"<b>Diffusion:</b> net movement down a concentration gradient (small/non-polar directly through bilayer). <b>Facilitated:</b> via channel/carrier proteins (large/polar). <b>Osmosis:</b> water across a partially permeable membrane down its water-potential gradient.",
"<b>Active transport:</b> AGAINST the gradient using ATP via carrier proteins (e.g. Na⁺/K⁺ pump, mineral uptake in roots). <b>Endo/exocytosis:</b> bulk transport in vesicles (phagocytosis, secretion).",
"<b>Factors in diffusion rate:</b> gradient steepness, surface area, thickness, temperature, molecule size. Surface-area:volume FALLS with size → need specialised exchange surfaces.",
"<b>Proteins:</b> amino acids + peptide bonds (condensation). 4 structure levels: primary (sequence) → secondary (α-helix/β-sheet, H-bonds) → tertiary (H/ionic/disulfide/London) → quaternary (multi-chain, e.g. Hb). Shape = function.",
"<b>Enzymes:</b> globular, specific active sites (induced fit), lower E_a; affected by T (kinetic energy → denature), pH (bonds/charge → denature), substrate/enzyme concentration, inhibitors (competitive: block site, reversible by ↑[S]; non-competitive: change shape elsewhere).",
"<b>DNA:</b> double helix, sugar–phosphate backbone, A–T (2 H-bonds), C–G (3 H-bonds), antiparallel. <b>Replication:</b> semi-conservative — helicase unzips, DNA polymerase adds complementary nucleotides 5'→3', ligase joins. <b>Protein synthesis:</b> transcription (mRNA copy in nucleus) → translation (ribosome, tRNA anticodons, codons — AUG start, 3 stop)."],
formulas:[{e:"SA:V = 6/L (cube)",w:"ratio falls as size grows"}],
defs:[{t:"Water potential",d:"Tendency of water to move; pure water = 0 kPa, solutions negative."},{t:"Codon",d:"Three-base mRNA sequence coding for one amino acid (or stop)."}],
worked:{q:"Explain why heating egg white turns it solid white (denaturation).",steps:["Heat gives kinetic energy → H-bonds/ionic bonds in tertiary structure break.","Protein unfolds (denatures) — shape/active properties lost.","Unfolded chains tangle/coagulate → solid white mass; irreversible."]},
mistakes:["'Cell wall is partially permeable' — the MEMBRANE is; walls are fully permeable.","Osmosis defined as solute movement — it's WATER movement.","DNA replication enzymes mixed up: helicase UNZIPS, polymerase BUILDS, ligase JOINS."],
tips:["Core practical: membrane permeability with beetroot + colorimeter — % transmission vs T/alcohol.","Enzyme Qs: always link factor → bonds/shape → active site → rate."],
oos:"<b>Beyond syllabus:</b> aquaporins (water channels) won a Nobel; CRISPR edits the DNA code directly (Unit 5!)."}}
]},
{id:"U2", code:"WBI12", short:"Unit 2", title:"Cells, Development, Biodiversity & Conservation", level:"AS", time:"1 h 30 min", marks:80, weight:"20% of IAL",
topics:[
{id:"U2T1", name:"Cell Structure & Microscopy", tags:"cell organelles microscope magnification resolution mitosis",
notes:{lede:"Inside cells: organelles, how microscopes work and the calculation that appears every single year.",
points:[
"<b>Organelles:</b> nucleus (DNA, pores), RER (protein folding/transport), ribosomes (translation), Golgi (modifies/packages), mitochondria (aerobic respiration/ATP), chloroplasts (photosynthesis), lysosomes (hydrolysis), cell wall (cellulose support), vacuole (turgor), centrioles (spindle).",
"<b>Eukaryote vs prokaryote:</b> prokaryotes (bacteria) — no nucleus (naked loop DNA), no membrane organelles, 70S ribosomes, small (~1 µm), cell wall of murein. Eukaryotes bigger with 80S ribosomes.",
"<b>Microscopes:</b> light (live, stained, ~0.2 µm resolution) • TEM (electrons through sections, ultra detail, dead, B&W) • SEM (surface 3D, dead). <b>Resolution</b> = smallest separable distance (λ-limited); <b>magnification</b> = size increase.",
"<b>Magnification = image size / real size.</b> Units: mm → µm (×1000) → nm (×1000). Measure with ruler, convert consistently.",
"<b>Calibration:</b> eyepiece graticule calibrated against stage micrometer for each objective. Scale bars on micrographs.",
"<b>Cell fractionation:</b> homogenise (cold, isotonic, buffered) → filter → ultracentrifuge at increasing speeds (nuclei → mitochondria → membranes/ribosomes)."],
formulas:[{e:"M = I / A",w:"magnification = image ÷ actual"}],
defs:[{t:"Resolution",d:"Minimum distance at which two objects appear as separate."},{t:"Organelle",d:"Membrane-bound compartment with a specific function."}],
worked:{q:"A chloroplast image is 40 mm long at ×20,000. Real length in µm?",steps:["Real = image/M = 40 mm / 20,000 = 0.002 mm.","0.002 mm × 1000 = 2 µm.","Sensible: chloroplasts are ~2–10 µm."]},
mistakes:["Unit conversions (mm/µm/nm) — write the ×1000 chain every time.","'High magnification = high resolution' — empty magnification enlarges blur; resolution needs short λ.","Calling the nucleolus the nucleus — nucleolus MAKES ribosomes inside the nucleus."],
tips:["Learn one TEM vs light comparison table — easy 4 marks.","'Explain how to prepare a slide' → thin section, stain, coverslip at angle (no bubbles), low→high power."],
oos:"<b>Beyond syllabus:</b> cryo-EM (2017 Nobel) freezes proteins mid-action — atomic movies of molecules."}},
{id:"U2T2", name:"Mitosis, Meiosis & Reproduction", tags:"mitosis meiosis cell cycle fertilisation variation",
notes:{lede:"How cells divide: the cell cycle, mitosis for growth and meiosis for gametes — the engine of variation.",
points:[
"<b>Cell cycle:</b> interphase (G1 growth, S DNA replication, G2 prep) → mitosis → cytokinesis. Checkpoints; uncontrolled = cancer.",
"<b>Mitosis:</b> PMAT — prophase (chromosomes condense, spindle forms), metaphase (line up on equator), anaphase (sister chromatids pulled apart), telophase (nuclei reform) → 2 genetically IDENTICAL diploid cells. For growth, repair, asexual reproduction.",
"<b>Meiosis:</b> TWO divisions → 4 genetically DIFFERENT haploid gametes. Meiosis I separates HOMOLOGOUS pairs (reduction); Meiosis II separates chromatids. <b>Crossing over</b> (prophase I) + <b>independent assortment</b> (metaphase I) create variation.",
"<b>Variation sources:</b> crossing over, independent assortment, random fertilisation, mutation. Mutations: substitution (may be silent/missense/nonsense), deletion/insertion (frameshift — usually severe).",
"<b>Fertilisation in mammals:</b> sperm (acrosome enzymes digest zona pellucida, haploid nucleus) + egg → diploid zygote; cortical reaction blocks polyspermy. In plants: pollen tube delivers nuclei (double fertilisation).",
"<b>Core practical:</b> mitosis in garlic root tips — stain (toluidine/acetic orcein), squash, count phases → mitotic index = dividing/total. Treat variables: same root zone, fix/stain times."],
formulas:[{e:"MI = dividing ÷ total",w:"mitotic index"}],
defs:[{t:"Homologous chromosomes",d:"Pair carrying the same genes (one from each parent), same length/centromere position."},{t:"Crossing over",d:"Exchange of sections between non-sister chromatids in prophase I."}],
worked:{q:"A root-tip field shows 120 cells, 18 in mitosis. Mitotic index? What does a higher MI mean?",steps:["MI = 18/120 = 0.15 (15%).","Higher MI = faster growth / more division (e.g. near tip, or with fertiliser).","Count several fields and average for reliability."]},
mistakes:["Meiosis I vs II confusion: homologues separate in I, chromatids in II.","Saying mitosis creates variation — it makes IDENTICAL cells.","Anaphase of mitosis vs anaphase I: chromatids vs whole chromosomes moving."],
tips:["Draw labelled PMAT diagrams once and memorise — describe chromosome behaviour per stage.","'Explain the significance of meiosis' → halving + variation, both needed."],
oos:"<b>Beyond syllabus:</b> nondisjunction (chromosomes fail to separate) causes Down/Turner syndromes — meiosis misfiring."}},
{id:"U2T3", name:"Gene Expression, Stem Cells & Differentiation", tags:"differentiation stem cell gene expression epigenetics totipotent",
notes:{lede:"One genome, many cells: how genes switch on and off, stem cells and the epigenetics rewriting textbooks.",
points:[
"<b>Differentiation:</b> cells become specialised by expressing SOME genes and switching others off — same genome, different proteome (e.g. haemoglobin only in RBCs, insulin only in β cells).",
"<b>Control:</b> transcription factors bind DNA/promoters; some genes always on (housekeeping); others triggered by signals/hormones.",
"<b>Stem cells:</b> unspecialised, self-renewing, can differentiate. <b>Totipotent</b> (zygote → everything incl. placenta) → <b>pluripotent</b> (embryonic → all body cells) → <b>multipotent</b> (adult, e.g. bone marrow → blood cells) → unipotent.",
"<b>Uses:</b> replace damaged tissue (Parkinson's, spinal injury, diabetes β cells, burns), drug testing, iPS cells (reprogrammed adult cells — fewer ethical issues). Risks: rejection, tumour formation, ethics of embryos.",
"<b>Epigenetics:</b> heritable changes in gene expression WITHOUT changing DNA sequence — DNA methylation / histone modification switch genes off/on. Influenced by environment (diet, stress, toxins); can pass to offspring.",
"<b>Phenotype = genotype + environment:</b> identical twins diverge epigenetically; height, skin colour, IQ all show both influences."],
formulas:[],
defs:[{t:"Totipotent",d:"Able to divide into every cell type including extra-embryonic tissue."},{t:"Epigenetics",d:"Heritable gene-expression changes without altering the DNA base sequence."}],
worked:{q:"Explain why a liver cell and a nerve cell differ despite identical DNA.",steps:["Both contain the full genome, but different genes are transcribed.","Transcription factors/epigenetic marks activate liver genes in liver, nerve genes in nerve cells.","Different proteins made → different structures/functions (differentiation)."]},
mistakes:["'Cells lose genes as they specialise' — genes are SWITCHED OFF, not lost.","Totipotent vs pluripotent swapped — totipotent includes placenta.","Saying mutations and epigenetics are the same — epigenetics doesn't change the sequence."],
tips:["Stem-cell ethics Qs: present BOTH sides (cures vs embryo status) + a conclusion.","iPS = induced pluripotent stem cells — adult cells reprogrammed back."],
oos:"<b>Beyond syllabus:</b> the Dutch Hunger Winter showed famine altering grandchildren's genes — epigenetic inheritance in humans."}},
{id:"U2T4", name:"Plants, Biodiversity & Conservation", tags:"plant biodiversity classification conservation seed bank niche",
notes:{lede:"Green machines and saving species: plant transport tissues, classifying life and protecting biodiversity.",
points:[
"<b>Plant cells:</b> wall, vacuole, chloroplasts; tissues — <b>xylem</b> (water up), <b>phloem</b> (sugars), meristems (growth). Leaves: palisade (photosynthesis), spongy (gas diffusion), stomata/guards (gas + water control), waxy cuticle.",
"<b>Plant uses:</b> fibres (cotton, flax/linen, hemp — cellulose strength), drugs (aspirin from willow, taxol from yew, quinine, morphine), food, fuels. Sustainable harvesting vs overexploitation.",
"<b>Biodiversity:</b> variety of genes, species and ecosystems. Measured by <b>species richness</b> (count) and <b>index of diversity</b> d = N(N−1)/Σn(n−1) (Simpson's — accounts for abundance/evenness).",
"<b>Sampling:</b> random quadrats (plants/sessile), transects (across zones), mark–release–recapture (mobile animals: N = n₁×n₂/m₂). Random + large sample + repeats = representative.",
"<b>Classification:</b> domain → kingdom → phylum → class → order → family → genus → species. <b>Species</b> = group that can interbreed → fertile offspring. Natural selection drives speciation: isolation → different selection pressures → genetic divergence → can't interbreed.",
"<b>Conservation:</b> in situ (reserves, marine parks — natural, needs space/cooperation) vs ex situ (zoos, seed banks like Svalbard/Millennium, captive breeding — safe but costly/artificial). CITES restricts trade; EIA guides development.",
"<b>Selection:</b> directional (one extreme favoured, e.g. antibiotic resistance), stabilising (middle, e.g. birth weight), disruptive (both extremes). Antibiotic resistance = directional selection on bacterial variation."],
formulas:[{e:"d = N(N−1)/Σn(n−1)",w:"Simpson's diversity index"},{e:"N = n₁n₂/m₂",w:"mark–release–recapture"}],
defs:[{t:"Species",d:"Group of similar organisms able to breed to produce fertile offspring."},{t:"Niche",d:"Role of a species: habitat, resources, interactions and conditions it needs."}],
worked:{q:"Quadrat data: daisies 8, grass 10, clover 2 (N=20). Calculate Simpson's d.",steps:["Σn(n−1) = 8×7 + 10×9 + 2×1 = 56 + 90 + 2 = 148.","d = 20×19/148 = 380/148 = 2.57.","Higher d = more diverse (max = number of species)."]},
mistakes:["Species richness vs diversity index — richness ignores abundance.","Mark–release assumptions forgotten (no migration/births/deaths, marks stay, random mixing).","Saying 'evolution stopped' — resistance/pesticide Qs show it continuing."],
tips:["Antibiotic-resistance explanation: variation exists FIRST → antibiotic SELECTS → resistant survive/reproduce → allele frequency rises. Never 'bacteria mutate to resist'.","Seed-bank advantages: cheap, tiny space, long storage, genetic diversity kept."],
oos:"<b>Beyond syllabus:</b> eDNA (sequencing water/soil) now surveys hidden biodiversity without catching anything."}}
]},
{id:"U3", code:"WBI13", short:"Unit 3", title:"Practical Skills in Biology I", level:"AS", time:"1 h 20 min", marks:50, weight:"10% of IAL",
topics:[
{id:"U3T1", name:"AS Practical Skills & Core Practicals", tags:"practical colorimeter t-test chi squared sampling",
notes:{lede:"Biology in the lab: core practicals, colorimetry, sampling stats and evaluation that hits every mark.",
points:[
"<b>Core practicals AS:</b> ① membrane permeability (beetroot + colorimeter vs T) ② enzyme rates (amylase + starch + iodine timing, or pH/T effects) ③ mitotic index (root tips) ④ biodiversity sampling (quadrats/transects) ⑤ plant fibres/drugs? + food tests (quantitative Benedict's).",
"<b>Colorimeter:</b> calibrate with blank (distilled water = 100% transmission/0 absorbance), same wavelength filter, same cuvettes, wipe clean. Plot calibration curves for concentrations.",
"<b>Controlling biology:</b> water baths (±0.5 °C), buffers (pH), same age/size/species, equilibrate before mixing, repeats (≥3), range (≥5 values).",
"<b>Statistics AS:</b> mean ± SD; <b>t-test</b> (compare two MEANS — significant if t > critical, p < 0.05); <b>chi-squared</b> (compare observed vs EXPECTED ratios, e.g. genetics); Spearman (correlation). State null hypothesis, df, critical value, conclusion.",
"<b>Graphs:</b> scatter/line for continuous IV; bar for categoric; error bars (±SD or range); lines of best fit balanced. Never bar charts for continuous data!",
"<b>Evaluation:</b> %U of small volumes/masses; biological variation (bigger n); control failures; validity of proxy measures (e.g. colour ≈ concentration). Improvements must target the named weakness."],
formulas:[{e:"p < 0.05 → significant",w:"reject the null hypothesis"}],
defs:[{t:"Null hypothesis",d:"Statement of no difference/effect, tested statistically."},{t:"Calibration curve",d:"Graph of known concentrations vs absorbance, used to find unknowns."}],
worked:{q:"t-test comparing plant heights in two fields gives t = 3.1, critical (p=0.05) = 2.1. Conclude.",steps:["t (3.1) > critical (2.1) → difference is SIGNIFICANT.","Reject the null hypothesis (p < 0.05).","There is a real difference in mean heights — less than 5% likely due to chance."]},
mistakes:["Wrong test: t-test for means, chi-squared for RATIOS/categories — don't swap.","'Proves' language — statistics SUPPORT/reject at 95%, never prove.","Forgetting df for chi-squared (categories − 1)."],
tips:["Learn the stats decision table: means→t-test, ratios→chi², correlation→Spearman.","Method Qs: 'equilibrate, mix, time, repeat, average, plot' — in that order."],
oos:"<b>Beyond syllabus:</b> p-hacking (torturing data to p<0.05) caused a replication crisis — preregistration now fights it."}}
]},
{id:"U4", code:"WBI14", short:"Unit 4", title:"Energy, Environment, Microbiology & Immunity", level:"A2", time:"1 h 45 min", marks:90, weight:"20% of IAL",
topics:[
{id:"U4T1", name:"Energy Flow, Ecosystems & Environment", tags:"photosynthesis ecosystem succession pollution eutrophication",
notes:{lede:"Energy through life: photosynthesis, food webs, succession — and how humans break and fix environments.",
points:[
"<b>Photosynthesis:</b> 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. <b>Light-dependent</b> (thylakoids: photolysis of water → ATP + NADPH + O₂, chlorophyll a P680/P700) → <b>Calvin cycle</b> (stroma: CO₂ fixed by Rubisco → GP → TP using ATP/NADPH → glucose).",
"<b>Limiting factors:</b> light, CO₂, temperature (not water usually — stomata close first). Glasshouse control: ↑CO₂, optimal T, light — cost vs yield. Inverse-square law for lamp distance.",
"<b>Energy transfer:</b> ~10% between trophic levels (respiration, excretion, uneaten parts, egestion). Gross vs net production; pyramids of biomass/energy (always upright) vs numbers (can invert).",
"<b>Decomposition:</b> saprobionts (bacteria/fungi) digest detritus extracellularly → release CO₂ (respiration) + minerals (recycling). <b>Nitrogen cycle:</b> fixation (Rhizobium/lightning) → NH₃ → nitrification (Nitrosomonas → nitrite, Nitrobacter → nitrate) → uptake → denitrification (anaerobic → N₂).",
"<b>Succession:</b> pioneer → sere → climax community; biodiversity/productivity ↑, conditions change (humus, shelter). Deflected (plagioclimax) by grazing/burning/mowing.",
"<b>Eutrophication:</b> fertiliser leach → algal bloom → blocks light → plants die → bacteria decompose → O₂ used up → fish die (low BOD… high oxygen demand). Indicator species (stonefly = clean, sludgeworm = polluted).",
"<b>Human impacts:</b> deforestation (CO₂, soil erosion, biodiversity loss), greenhouse effect (CO₂/CH₄ absorb IR re-radiated), global warming evidence + mitigation (renewables, reforestation, carbon capture, international agreements)."],
formulas:[{e:"6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂",w:"photosynthesis"}],
defs:[{t:"Gross primary production",d:"Total energy fixed by photosynthesis; net = gross − respiration."},{t:"Eutrophication",d:"Nutrient enrichment causing algal blooms and oxygen depletion."}],
worked:{q:"Gross production 8000 kJ m⁻² yr⁻¹, respiration 5000. Net production and % transferred if herbivores gain 240?",steps:["Net = 8000 − 5000 = 3000 kJ m⁻² yr⁻¹.","Transfer = 240/3000 × 100 = 8% (typical ~10%).","Rest lost: respiration, faeces, uneaten tissue, excretion."]},
mistakes:["Light-dependent vs independent locations swapped — thylakoid vs STROMA.","Saying respiration only happens at night — plants respire ALWAYS.","Eutrophication order muddled — learn the 6-step chain in sequence."],
tips:["'Explain the shape of the photosynthesis–light curve' → limiting factor changes along it.","Nitrogen-cycle bacteria NAMES earn marks — Nitrosomonas, Nitrobacter, Rhizobium, Azotobacter."],
oos:"<b>Beyond syllabus:</b> C4 plants (maize) and CAM (cacti) beat photorespiration — evolution's photosynthesis upgrades."}},
{id:"U4T2", name:"Microbiology & Forensics", tags:"bacteria growth aseptic antibiotic forensic dna profiling",
notes:{lede:"Growing germs safely: bacterial growth, aseptic technique, antibiotics — and catching criminals with DNA.",
points:[
"<b>Bacterial growth curve:</b> lag (adapting/enzymes) → log (exponential, doubling) → stationary (nutrients run out = death rate) → death/decline. Plot log(count) vs time for straight log phase.",
"<b>Aseptic technique:</b> flame loops/necks, work near Bunsen (updraft), sterile media, disinfect surfaces, incubate ≤30 °C (schools — avoid pathogens), tape plates (don't seal fully), autoclave before disposal.",
"<b>Measuring growth:</b> viable count (dilution plating — colonies from LIVING cells), total count (haemocytometer), turbidity (colorimeter — living + dead).",
"<b>Antibiotics:</b> target bacterial features — penicillin blocks wall synthesis, others block protein synthesis/DNA replication. Resistance via mutation + selection + plasmids (horizontal transfer). MRSA/VRSA; prudent use (finish courses, no viral use, farm limits).",
"<b>Hospital control:</b> hand hygiene, isolation, sterilisation, screening, antibiotic stewardship.",
"<b>Forensics:</b> DNA profiling — extract, cut (restriction enzymes), amplify (PCR), separate (electrophoresis), compare band patterns (VNTR/minisatellites) — match probability tiny. Blood spatter, fibres, fingerprints support. Time of death: body temp (algor mortis), rigor, entomology."],
formulas:[{e:"colonies × dilution ÷ volume",w:"viable count (cfu cm⁻³)"}],
defs:[{t:"Aseptic technique",d:"Procedures preventing contamination by unwanted microbes."},{t:"Minimum inhibitory concentration",d:"Lowest antibiotic concentration preventing visible growth."}],
worked:{q:"0.1 cm³ of a 10⁻⁵ dilution gives 86 colonies. Original concentration?",steps:["86 colonies from 0.1 cm³ of diluted → 860 cm⁻³ of diluted.","× 10⁵ (dilution factor) = 8.6×10⁷ cfu cm⁻³.","Count plates with 30–300 colonies for accuracy."]},
mistakes:["Incubation at 37 °C in schools — use ≤30 °C (pathogen risk).","Sealing plates fully — anaerobic pathogens; tape in 2 places only.","Saying antibiotics kill viruses — they target BACTERIAL structures."],
tips:["Zone-of-inhibition Qs: measure DIAMETER, compare areas, control disc (solvent only).","Growth-curve explanations: link EACH phase to nutrients/waste."],
oos:"<b>Beyond syllabus:</b> phage therapy (viruses vs bacteria) is back — precision weapons against superbugs."}},
{id:"U4T3", name:"Immunity", tags:"immunity antibody vaccine phagocytosis t cell b cell",
notes:{lede:"Defending the body: innate barriers, phagocytes, lymphocytes, antibodies and vaccines.",
points:[
"<b>Barriers:</b> skin, mucus/cilia, stomach acid, lysozyme, clotting, inflammation (histamine → blood flow, phagocytes attracted).",
"<b>Phagocytosis (non-specific):</b> phagocyte recognises foreign antigens → engulfs (pseudopodia) → phagosome fuses with lysosome → hydrolysed → presents antigens (antigen presentation to lymphocytes).",
"<b>Humoral (B cells):</b> B cell meets matching antigen → clonal selection → plasma cells (antibodies, specific to antigen) + memory cells. Antibodies: Y-shaped, variable region binds antigen (agglutination, opsonisation, neutralisation).",
"<b>Cell-mediated (T cells):</b> T-helper (activate B/T, cytokines) + T-killer/cytotoxic (destroy infected/cancer cells, perforin) + T-memory + T-regulatory. Needed against viruses/cancer (hidden inside cells).",
"<b>Primary response:</b> slow, low antibody (first exposure). <b>Secondary:</b> fast, huge (memory cells) — basis of immunity.",
"<b>Vaccines:</b> attenuated/inactivated/subunit antigen → primary response + memory WITHOUT disease. <b>Herd immunity:</b> high coverage stops spread, protecting the vulnerable (vaccination thresholds ~90%+ for measles). Risks debated: side effects vs disease — evaluate with data.",
"<b>Monoclonal antibodies:</b> B cell × myeloma → hybridoma → identical antibodies (pregnancy tests, cancer therapy, ELISA). <b>Active</b> (you make antibodies, long-lived) vs <b>passive</b> (given antibodies, instant but temporary — e.g. antivenom, breast milk)."],
formulas:[],
defs:[{t:"Antigen",d:"Molecule triggering an immune response (usually foreign protein/polysaccharide)."} ,{t:"Clonal selection",d:"Antigen selecting matching lymphocytes to divide into effector + memory cells."}],
worked:{q:"Why do you need a tetanus booster every 10 years but measles vaccine usually lasts for life?",steps:["Memory cells fade over time; boosters re-stimulate → fresh memory (secondary response).","Measles virus is stable (one serotype) and provokes strong lifelong memory.","Tetanus boosters also counter waning antibody titres against a deadly toxin."]},
mistakes:["'Antibodies kill pathogens' — they MARK/NEUTRALISE; phagocytes/complement destroy.","Active vs passive immunity swapped — active = YOU respond (slow, lasting).","Vaccines 'give you a mild dose of disease' — modern antigens can't cause disease."],
tips:["Primary vs secondary graph: label lag, antibody concentration, memory — classic 5-marker.","Herd-immunity Qs: explain protection of the UNVACCINATED (too young/ill)."],
oos:"<b>Beyond syllabus:</b> mRNA vaccines (COVID) deliver instructions, not antigen — your cells print the spike."}}
]},
{id:"U5", code:"WBI15", short:"Unit 5", title:"Respiration, Homeostasis, Coordination & Genes", level:"A2", time:"1 h 45 min", marks:90, weight:"20% of IAL",
topics:[
{id:"U5T1", name:"Respiration & Muscles", tags:"respiration atp glycolysis krebs oxidative mitochondria muscle",
notes:{lede:"Releasing energy: glycolysis to oxidative phosphorylation, and how muscles turn ATP into movement.",
points:[
"<b>ATP:</b> energy currency — hydrolysis (ATP → ADP + Pi) releases ~30 kJ mol⁻¹ for muscle, active transport, biosynthesis. Resynthesised by respiration.",
"<b>Glycolysis (cytoplasm):</b> glucose → 2 pyruvate + net 2 ATP + 2 NADH. No O₂ needed.",
"<b>Link + Krebs (mitochondrial matrix):</b> pyruvate → acetyl-CoA (CO₂ + NADH) → Krebs cycle spins off CO₂, ATP, NADH, FADH₂.",
"<b>Oxidative phosphorylation (cristae):</b> NADH/FADH₂ donate e⁻ to ETC → H⁺ pumped to intermembrane space → gradient drives ATP synthase (chemiosmosis) → ~34 ATP; O₂ is the FINAL e⁻ acceptor (→ water). Total ~38 ATP/glucose aerobic.",
"<b>Anaerobic:</b> animals — pyruvate → lactate (NAD⁺ regenerated, 2 ATP only); plants/yeast — pyruvate → ethanol + CO₂. Oxygen debt repaid later (lactate → liver → glucose/pyruvate). RQ = CO₂/O₂ (carbs 1.0, lipids ~0.7, protein ~0.8).",
"<b>Muscles:</b> sarcomere — actin (thin) + myosin (thick). <b>Sliding filament:</b> nerve impulse → Ca²⁺ released → tropomyosin moves → myosin heads bind actin (cross-bridges) → power stroke (ATP) → filaments slide (H zone/I band shorten, A band same). Creatine phosphate = fast ATP backup.",
"<b>Muscle types:</b> slow-twitch (myoglobin-rich, aerobic, endurance) vs fast-twitch (glycolytic, sprint). Training/exercise ↑ mitochondria, capillaries, heart efficiency."],
formulas:[{e:"C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O",w:"aerobic respiration"},{e:"RQ = CO₂ out ÷ O₂ in",w:"respiratory quotient"}],
defs:[{t:"Chemiosmosis",d:"ATP synthesis driven by a proton gradient through ATP synthase."},{t:"Oxygen debt",d:"Extra O₂ needed post-exercise to oxidise lactate and restore ATP/CP."}],
worked:{q:"Why do cyanide victims die despite normal blood oxygen?",steps:["Cyanide blocks the electron transport chain (complex IV).","No H⁺ gradient → no ATP via oxidative phosphorylation; tissues can't USE the O₂.","Cells die of energy failure — oxygen delivery is fine, utilisation is blocked."]},
mistakes:["'Anaerobic respiration produces no ATP' — it makes 2 (glycolysis still runs).","Krebs location: MATRIX; ETC: CRISTAE membrane — don't swap.","Sliding filament: filaments SLIDE (lengths unchanged) — A band stays constant."],
tips:["Respirometer Qs: KOH absorbs CO₂ (O₂ uptake only); with/without KOH compares RQ.","'Explain the need for NAD⁺ regeneration' → without it glycolysis halts."],
oos:"<b>Beyond syllabus:</b> mitochondria were free bacteria (endosymbiosis) — they keep their own DNA."}},
{id:"U5T2", name:"Homeostasis: Kidney, Liver & Control", tags:"homeostasis kidney nephron osmoregulation thermoregulation diabetes",
notes:{lede:"Staying constant: negative feedback, the kidney's filter, blood glucose and temperature control.",
points:[
"<b>Homeostasis:</b> maintaining a constant internal environment via receptors → coordinator → effectors, usually <b>negative feedback</b> (change triggers reversal). Examples: glucose, water, temperature, CO₂/pH.",
"<b>Kidney:</b> cortex (glomeruli, convoluted tubules) + medulla (loops of Henle) + pelvis. <b>Ultrafiltration</b> (glomerulus: high pressure forces small molecules into Bowman's capsule; cells/proteins stay) → <b>selective reabsorption</b> (PCT: all glucose/amino acids, most water/ions, active transport) → <b>loop of Henle</b> (medulla gradient via counter-current multiplier) → <b>DCT/collecting duct</b> (ADH-controlled water).",
"<b>Osmoregulation:</b> dehydrated → blood water-potential ↓ → osmoreceptors (hypothalamus) → ADH (pituitary) ↑ → collecting-duct walls more permeable → more water reabsorbed → concentrated urine. Reverse when hydrated.",
"<b>Thermoregulation:</b> hypothalamus monitors blood T. Hot: vasodilation, sweating, hairs flat, less shivering/metabolism. Cold: vasoconstriction, shivering (muscle contraction), hairs erect (trapped air), adrenaline/thyroxine ↑ metabolism.",
"<b>Blood glucose:</b> high → β cells release INSULIN → liver/muscles take up glucose (glycogenesis), cells respire more → falls. Low → α cells release GLUCAGON → glycogenolysis/gluconeogenesis → rises. Adrenaline also raises glucose.",
"<b>Diabetes:</b> Type 1 (no insulin — autoimmune β destruction; treat with insulin) vs Type 2 (insulin resistance/reduced — lifestyle-linked; diet/exercise/drugs). Test: glucose tolerance (blood glucose vs time), urine glucose. <b>Liver:</b> deamination (→ urea/ornithine cycle), glycogen store, detox (alcohol), bile, heat."],
formulas:[],
defs:[{t:"Negative feedback",d:"Control where a change triggers responses reversing the change."},{t:"Ultrafiltration",d:"Pressure-forced filtration of small molecules from glomerulus to Bowman's capsule."}],
worked:{q:"Explain why eating a very salty meal makes urine more concentrated.",steps:["Salt absorbed → blood water potential falls → osmoreceptors detect.","Hypothalamus → more ADH released from posterior pituitary.","Collecting ducts more permeable → more water reabsorbed → small volume, concentrated urine."]},
mistakes:["ADH 'absorbs water' — it makes ducts PERMEABLE (aquaporins); osmosis does the moving.","Insulin/glucagon sources swapped — β = insulin, α = glucagon.","Loop of Henle 'reabsorbs water into blood' — it builds the MEDULLA GRADIENT; collecting duct does the ADH-regulated reabsorption."],
tips:["Every homeostasis answer: stimulus → receptor → coordinator → hormone/nerves → effector → response → feedback.","Kidney diagrams: label cortex/medulla/pelvis/ureter + nephron parts with functions."],
oos:"<b>Beyond syllabus:</b> dialysis mimics ultrafiltration + diffusion; kidney transplants beat it — immunosuppressants stop T-cell rejection."}},
{id:"U5T3", name:"Nervous System & Coordination", tags:"neurone synapse action potential reflex eye brain",
notes:{lede:"Rapid messaging: neurones, the action potential, synapses and how eye and brain process the world.",
points:[
"<b>Neurones:</b> sensory (receptor → CNS) • relay (within CNS) • motor (CNS → effector). Myelin (Schwann cells) + nodes of Ranvier → saltatory conduction (fast ~100 m s⁻¹). Larger diameter = faster.",
"<b>Resting potential (−70 mV):</b> Na⁺/K⁺ pump (3 Na⁺ out, 2 K⁺ in) + K⁺ leak → inside negative. <b>Action potential:</b> stimulus → Na⁺ channels open → depolarisation (+40 mV) → Na⁺ close, K⁺ open → repolarisation → hyperpolarisation → pump restores. All-or-nothing; refractory period → one direction + discrete impulses.",
"<b>Synapses:</b> AP arrives → Ca²⁺ in → vesicles fuse → neurotransmitter (acetylcholine) diffuses → binds receptors → new AP (if threshold). Summation (temporal/spatial); inhibitory transmitters (hyperpolarise); drugs act here (nicotine mimics ACh, organophosphates block cholinesterase).",
"<b>Reflex arc:</b> receptor → sensory → relay (spinal cord) → motor → effector — fast, involuntary, protective (e.g. withdrawal, blinking). Brain informed after.",
"<b>Eye:</b> cornea/lens focus (accommodation: ciliary muscles + suspensory ligaments), iris/pupil (light intensity), retina (rods: dim light, many→one bipolar = sensitive, low acuity; cones: colour/acuity, fovea dense). Rhodopsin (vitamin A) bleaches in light.",
"<b>Brain:</b> cerebrum (conscious thought, memory), cerebellum (coordination/balance), medulla (autonomic: heart, breathing), hypothalamus (homeostasis, pituitary link). Scans (fMRI/PET) map function — ethics of animal/human study."],
formulas:[],
defs:[{t:"Saltatory conduction",d:"AP jumping between nodes of Ranvier — fast, energy-efficient."},{t:"Summation",d:"Combined sub-threshold potentials reaching threshold (temporal: repeated; spatial: several synapses)."}],
worked:{q:"Explain how the response to dim light differs from bright light in the retina.",steps:["Dim: rods active — rhodopsin intact, many rods converge on one bipolar (sensitive, poor acuity, monochrome).","Bright: rods bleached/saturated; cones (fovea) take over — high acuity, colour.","Pupil also dilates in dim light (radial muscles) to admit more light."]},
mistakes:["Na⁺/K⁺ directions swapped — Na⁺ OUT (3), K⁺ IN (2) by the pump.","'Impulse gets weaker along the axon' — all-or-nothing, constant size; intensity = FREQUENCY.","Synapse direction: neurotransmitter crosses ONE way (pre → post)."],
tips:["AP graph: label −70, +40, Na⁺/K⁺ channel states per phase — classic 6-marker.","Drug-action Qs: state the synapse step affected + excitatory/inhibitory consequence."],
oos:"<b>Beyond syllabus:</b> optogenetics switches neurones with light — mapping brains neuron by neuron."}},
{id:"U5T4", name:"Gene Technology & Control", tags:"genetic engineering pcr electrophoresis gene therapy cloning",
notes:{lede:"Rewriting life: recombinant DNA, PCR, electrophoresis, gene therapy and the ethics of it all.",
points:[
"<b>Recombinant DNA:</b> isolate gene (restriction enzymes leave sticky ends) → cut vector (plasmid) with SAME enzyme → join with ligase → insert into host (heat shock/Ca²⁺) → marker genes (antibiotic resistance) identify transformants → culture (fermenters) → extract product (insulin, growth hormone, factor VIII).",
"<b>PCR:</b> cycles of denaturation (~95 °C) → annealing primers (~55 °C) → extension (Taq polymerase, 72 °C) → DNA doubles each cycle (2ⁿ). Needs primers, nucleotides, Taq. Used in forensics, diagnosis, sequencing prep.",
"<b>Gel electrophoresis:</b> DNA fragments separated by SIZE (smallest travel furthest toward +) in agarose; compare bands to markers/samples (profiling, paternity, disease alleles).",
"<b>Gene therapy:</b> somatic (patient's cells, e.g. cystic fibrosis lung cells via vectors — not inherited) vs germ-line (heritable — banned in most countries). Ex vivo (cells out, edited, back) vs in vivo (vector injected). Risks: immune reaction, off-target insertion (cancer), ethics.",
"<b>Plant technology:</b> tissue culture/micropropagation (identical clones, fast, virus-free), GM crops (Bt insect resistance, herbicide tolerance, Golden Rice vitamin A) — debate: yield/food security vs gene escape/superweeds/corporate control.",
"<b>Cloning animals:</b> embryo splitting / somatic-cell nuclear transfer (Dolly) — identical genotype; uses (prize livestock, research, rescue) vs ethics/health (premature ageing, low success).",
"<b>Control of gene expression:</b> transcription factors, oestrogen (steroid → enters cell → receptor complex → DNA), siRNA/RNAi (silencing); epigenetics (Unit 2) links environment to expression."],
formulas:[{e:"2ⁿ copies",w:"PCR amplification (n cycles)"}],
defs:[{t:"Vector",d:"DNA carrier (e.g. plasmid) transferring a gene into host cells."},{t:"Sticky ends",d:"Complementary single-stranded overhangs from staggered restriction cuts."}],
worked:{q:"Starting with 1 DNA molecule, how many after 20 PCR cycles? Why must primers be specific?",steps:["2²⁰ ≈ 1,048,576 (~1 million) copies.","Primers define WHAT amplifies — specific primers bind only the target flanks.","Wrong primers → wrong/no product; two primers bracket the region."]},
mistakes:["Restriction + ligase roles swapped — restriction CUTS, ligase JOINS.","'PCR needs DNA polymerase from humans' — Taq (heat-stable, from Thermus aquaticus) survives 95 °C.","Somatic vs germ-line therapy confused — somatic isn't inherited."],
tips:["Genetic-engineering method: 6 steps in order (isolate, cut, join, insert, select, culture) — memorise.","Ethics Qs: benefits vs risks + who decides + a justified conclusion."],
oos:"<b>Beyond syllabus:</b> CRISPR-Cas9 cuts + pastes genes precisely — cures for sickle-cell already approved."}}
]},
{id:"U6", code:"WBI16", short:"Unit 6", title:"Practical Skills in Biology II", level:"A2", time:"1 h 20 min", marks:50, weight:"10% of IAL",
topics:[
{id:"U6T1", name:"A2 Practical Skills & Investigation Planning", tags:"practical stats planning respirometer colorimeter",
notes:{lede:"A2 biology practicals: planning from scratch, respirometry, statistics and evaluation at distinction level.",
points:[
"<b>Plan framework:</b> hypothesis (directional, testable) → IV (range ≥5) / DV (how measured, units) / controls (how) → method (stepwise, volumes/times) → repeats (≥3) → analysis (graph + stats test named) → safety + ethics.",
"<b>Respirometer:</b> organisms + KOH (absorbs CO₂) → O₂ uptake moves fluid; control (glass beads) for T/pressure; equilibrate; repeat at different T/masses. Without KOH, movement = O₂ in − CO₂ out.",
"<b>Enzyme kinetics A2:</b> initial rates (tangent at t=0) vs [S] → Vmax/Km ideas; Lineweaver–Burk qualitative (competitive: same Vmax; non-competitive: lower Vmax). Iodine clock / pH-stat methods.",
"<b>Stats A2:</b> choose correctly — t-test (2 means), chi² (ratios), Spearman RANK (correlation, r_s vs critical), Mann–Whitney preview? (IAL focuses t/chi²/Spearman). Always: null hypothesis → calculate → compare critical (p=0.05) → conclude in context.",
"<b>Sampling A2:</b> random (random-number grid/quadrats) vs systematic (transects across gradients); abundance scales (ACFOR); Simpson's d comparisons between sites; kick-sampling + biotic indices for streams.",
"<b>Validity killers:</b> uncontrolled T/pH/light, small n, biased sampling, proxy measures (e.g. turbidity = growth?), organism variation (age/size/health), acclimatisation time.",
"<b>Ethics/safety:</b> minimal organism harm, release/return, no cruelty; disinfectants, sharps, allergens, electrical water-bath care; risk assessment matrix (likelihood × severity)."],
formulas:[{e:"r_s vs critical",w:"Spearman correlation test"}],
defs:[{t:"Initial rate",d:"Reaction rate at t=0 (before substrate depletes/product inhibits) — tangent gradient."},{t:"Biotic index",d:"Pollution score from presence/abundance of indicator species."}],
worked:{q:"Plan: effect of temperature on respiration rate in woodlice (respirometer).",steps:["IV: T (10–40 °C, water baths, 5+ values); DV: O₂ uptake (mm³ min⁻¹ g⁻¹); controls: mass/number/species of woodlice, time, apparatus.","Equilibrate 5 min, record dye movement 5 min, ×3 repeats; control tube with beads.","Plot rate vs T; t-test between extremes; safety: release woodlice, gentle handling, water + electrics."]},
mistakes:["Controlling the DV ('keep respiration constant') — control everything EXCEPT IV.","No stats test named in the plan — 'analyse results' alone scores nothing.","Ethics ignored for animal work — always include minimising harm."],
tips:["'Write a plan' = 6 marks: hypothesis, variables, method, repeats, analysis, safety — one per bullet.","Practise the three stats decisions until automatic."],
oos:"<b>Beyond syllabus:</b> field biologists now log data on phones + eDNA — your quadrat skills scale up."}}
]}
]};
