/* Edexcel IAL Mathematics (YMA01) — P1-P4, S1, M1 syllabus content & revision notes */
var SUBJECT_MATHS = {
id:"maths", name:"Mathematics", icon:"📐", color:"#fbbf24", qual:"YMA01",
desc:"Pure 1–4 plus Statistics 1 and Mechanics 1 — WMA11–WMA14, WST01, WME01. Six 75-mark papers.",
hubs:[
 {name:"📄 Save My Exams — IAL Maths past papers", url:"https://www.savemyexams.com/international-a-level/maths/edexcel/past-papers/", desc:"P1–P4, S1, M1 — QP + MS for every session."},
 {name:"🎯 IAL questions by topic (with MS)", url:"https://alevelmathsrevision.com/edexcel-ial-questions-by-topic/", desc:"Topical compilations per unit — perfect paired practice with this site."},
 {name:"🏛️ Pearson Edexcel past paper finder", url:"https://qualifications.pearson.com/en/support/support-topics/exams/past-papers.html", desc:"Official WMA/WST/WME papers & mark schemes."},
 {name:"📊 IAL Maths unit guide & paper index", url:"https://papamarks.com/blog/edexcel-ial-maths-guide", desc:"Unit-by-unit content map with question counts per topic."}
],
units:[
{id:"P1", code:"WMA11", short:"P1", title:"Pure Mathematics 1", level:"AS", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"P1T1", name:"Algebra, Quadratics & Inequalities", tags:"algebra quadratics discriminant completing square inequalities indices",
notes:{lede:"The algebra engine: indices, surds, quadratics, completing the square and inequalities — used in every paper.",
points:[
"<b>Indices:</b> a^m·a^n = a^(m+n) • a^m÷a^n = a^(m−n) • (a^m)^n = a^mn • a^0 = 1 • a^−n = 1/a^n • a^(1/n) = ⁿ√a. Surds: √ab = √a√b; rationalise (× conjugate).",
"<b>Quadratics:</b> factorise (double brackets), formula x = (−b ± √(b²−4ac))/2a, or complete the square: a(x + b/2a)² − ….",
"<b>Discriminant:</b> b² − 4ac > 0 two real roots • = 0 repeated root • < 0 no real roots. For 'tangent' or 'no intersection' Qs, set = 0 or < 0.",
"<b>Completing the square:</b> x² + bx + c = (x + b/2)² − (b/2)² + c → vertex (−b/2, min value). For a > 0 minimum; a < 0 maximum.",
"<b>Inequalities:</b> sketch the curve, find critical values, test regions. Quadratics: between roots (if < 0, ∪ shape) or outside. NEVER multiply/divide by x (sign unknown) — collect to one side and factorise.",
"<b>Simultaneous:</b> linear + quadratic → substitute → discriminant tells intersections (2/1/0)."],
formulas:[{e:"x = (−b ± √(b²−4ac)) / 2a",w:"quadratic formula"},{e:"b² − 4ac",w:"discriminant"}],
defs:[{t:"Discriminant",d:"b²−4ac — determines the number of real roots."},{t:"Critical values",d:"Roots bounding the regions in an inequality sketch."}],
worked:{q:"Find k for which x² + kx + 9 = 0 has equal roots, and solve.",steps:["Equal roots → discriminant = 0: k² − 36 = 0 → k = ±6.","k = 6: (x+3)² = 0 → x = −3 (repeated).","k = −6: (x−3)² = 0 → x = 3."]},
mistakes:["Dividing an inequality by a negative without flipping the sign.","Writing x > 2 AND x < −1 for outside-roots (use OR).","Forgetting both k values in discriminant-equals-zero Qs."],
tips:["Always SKETCH for inequalities — the graph is the method.","'Show that…' quadratics: substitute and rearrange to the given form first."],
oos:"<b>Beyond syllabus:</b> quadratics over complex numbers always have 2 roots — FP1 opens that door."}},
{id:"P1T2", name:"Functions, Graphs & Transformations", tags:"functions transformations sketching graphs domain range",
notes:{lede:"Reading and moving graphs: domain, range, transformations and sketching polynomials and reciprocals.",
points:[
"<b>Functions:</b> one x → one y. Notation f(x), fg (do g first), f⁻¹ (reflect y = x). Domain (allowed x) & range (possible y).",
"<b>Transformations:</b> y = f(x) + a (up) • f(x + a) (LEFT — counterintuitive!) • af(x) (vertical stretch) • f(ax) (horizontal squash 1/a) • −f(x) (reflect x-axis) • f(−x) (reflect y-axis).",
"<b>Order matters:</b> apply inside-bracket (x) changes first when reading left-to-right… safest: track a point (x, y) through each stage.",
"<b>Sketching:</b> find intercepts (x=0, y=0), factorise for roots, end behaviour (leading term dominates), turning points optional.",
"<b>Reciprocal 1/x:</b> asymptotes x = 0, y = 0. <b>1/x²:</b> always positive, same asymptotes. Transformations shift asymptotes.",
"<b>Proportionality:</b> y ∝ x² → y = kx² (find k from a point). Intersection of graphs = simultaneous solution."],
formulas:[{e:"f(x+a): shift LEFT a",w:"inside = opposite!"},{e:"af(x): ×a vertically",w:"outside = as expected"}],
defs:[{t:"Domain",d:"Set of input x-values a function accepts."},{t:"Asymptote",d:"Line a curve approaches but never reaches."}],
worked:{q:"The graph of y = f(x) passes through (2, 5). State a point on y = 3f(x − 1) + 2.",steps:["x − 1: shift right 1 → x = 2 + 1 = 3.","×3 then +2 on y: y = 3×5 + 2 = 17.","Point (3, 17)."]},
mistakes:["f(x+2) shifted RIGHT — inside shifts go OPPOSITE.","Forgetting asymptotes move with translations.","Domain of 1/(x−2): x ≠ 2 missing from answers."],
tips:["Transformations Qs: map 2–3 key points (intercepts, vertex) — don't redraw blindly.","'Describe the transformation' → name + direction + magnitude, all three."],
oos:"<b>Beyond syllabus:</b> function composition builds fractals — iterate z → z² + c and meet the Mandelbrot set."}},
{id:"P1T3", name:"Coordinate Geometry & Straight Lines", tags:"coordinate geometry straight line gradient midpoint circle",
notes:{lede:"Lines and lengths: gradients, equations, perpendiculars, midpoints and circle basics.",
points:[
"<b>Gradient m = (y₂−y₁)/(x₂−x₁).</b> Length = √((Δx)² + (Δy)²). Midpoint = averages of x and y.",
"<b>Line equations:</b> y = mx + c • y − y₁ = m(x − x₁) (point + gradient) • ax + by + c = 0 (general).",
"<b>Parallel:</b> same m. <b>Perpendicular:</b> m₁m₂ = −1 (negative reciprocal).",
"<b>Circle centre (a,b) radius r:</b> (x−a)² + (y−b)² = r². Complete the square to find centre/radius from expanded form.",
"<b>Tangent ⊥ radius:</b> gradient of radius × gradient of tangent = −1. Find radius gradient from centre to point, flip for tangent.",
"<b>Applications:</b> show a point lies on a line (substitute), find intersections (solve simultaneously), area of triangles (½bh with perpendicular height)."],
formulas:[{e:"m = Δy/Δx",w:"gradient"},{e:"y − y₁ = m(x − x₁)",w:"point–gradient form"},{e:"m₁m₂ = −1",w:"perpendicular lines"}],
defs:[{t:"Normal",d:"Line perpendicular to a curve at a point."},{t:"Locus",d:"Set of points satisfying a condition (e.g. fixed distance = circle)."}],
worked:{q:"Find the tangent to (x−1)² + (y+2)² = 25 at (4, 2).",steps:["Centre (1, −2); radius gradient = (2−(−2))/(4−1) = 4/3.","Tangent gradient = −3/4.","y − 2 = −¾(x − 4) → 3x + 4y − 20 = 0."]},
mistakes:["Sign slips in centre: (x−1)² → centre x = +1.","Using radius gradient AS the tangent gradient.","Forgetting to verify the point is ON the circle first."],
tips:["Circle Qs: complete the square immediately — centre and radius unlock everything.","Show-that-parallel: compare gradients in y = mx + c form."],
oos:"<b>Beyond syllabus:</b> coordinate geometry + calculus = analytic geometry, Descartes' gift to science."}},
{id:"P1T4", name:"Trigonometry (P1)", tags:"trigonometry sine cosine rule sohcahtoa graphs radians",
notes:{lede:"Triangles and waves: SOHCAHTOA, sine/cosine rules, areas and the trig graphs.",
points:[
"<b>SOHCAHTOA</b> for right-angled triangles. Pythagoras to find missing sides first if needed.",
"<b>Sine rule:</b> a/sinA = b/sinB = c/sinC — use for opposite pairs (2 angles + 1 side, or 2 sides + 1 non-included angle). Ambiguous case: sin θ = sin(180−θ) — check for TWO solutions!",
"<b>Cosine rule:</b> a² = b² + c² − 2bc cosA — 3 sides + 1 angle situations (SSS→angle, SAS→side).",
"<b>Area = ½ab sinC</b> — two sides + included angle.",
"<b>Exact values:</b> sin/cos/tan of 30°, 45°, 60° (learn the triangles: 1–√3–2 and 1–1–√2). No calculator marks for these!",
"<b>Graphs:</b> sin/cos period 360°, amplitude 1; tan period 180°, asymptotes at 90° + 180°n. Transformations apply (amplitude, period)."],
formulas:[{e:"a/sinA = b/sinB",w:"sine rule"},{e:"a² = b²+c²−2bc cosA",w:"cosine rule"},{e:"A = ½ab sinC",w:"area"}],
defs:[{t:"Ambiguous case",d:"Two possible triangles from SSA data (acute + obtuse supplements)."}],
worked:{q:"Triangle: a = 7, b = 9, C = 60°. Find c and area.",steps:["c² = 49 + 81 − 2×7×9×cos60° = 130 − 63 = 67 → c = 8.19.","Area = ½ × 7 × 9 × sin60° = 27.3.","Check: c between |a−b| and a+b ✓"]},
mistakes:["Sine rule upside down — match sides to OPPOSITE angles.","Missing the second (obtuse) solution in SSA Qs.","Calculator in radian mode for degree Qs — check every paper!"],
tips:["Bearings: measure clockwise from North; draw the North lines first.","Exact-value answers: leave as √3/2 etc. unless told to round."],
oos:"<b>Beyond syllabus:</b> trig graphs are the purest waves — Fourier built all signals from them."}},
{id:"P1T5", name:"Differentiation (P1)", tags:"differentiation gradient tangent normal stationary points",
notes:{lede:"Rates of change: differentiating powers, tangents, normals and finding maxima and minima.",
points:[
"<b>Power rule:</b> y = axⁿ → dy/dx = anxⁿ⁻¹. Rewrite roots/reciprocals FIRST: √x = x^½, 1/x² = x⁻², then differentiate term by term.",
"<b>dy/dx = gradient function.</b> Second derivative d²y/dx²: > 0 minimum (∪), < 0 maximum (∩).",
"<b>Tangent:</b> gradient = dy/dx at the point; equation via y − y₁ = m(x − x₁). <b>Normal:</b> m_normal = −1/m_tangent.",
"<b>Stationary points:</b> dy/dx = 0 → solve → classify with d²y/dx² or gradient test. Max/min (+ points of inflection in P2).",
"<b>Increasing/decreasing:</b> dy/dx > 0 increasing; < 0 decreasing. For 'show increasing for all x' prove dy/dx > 0 always (e.g. sum of squares).",
"<b>Real contexts:</b> dV/dt, cost minimisation, area maximisation — differentiate, = 0, verify max/min, contextual conclusion."],
formulas:[{e:"d/dx(axⁿ) = anxⁿ⁻¹",w:"power rule"},{e:"d²y/dx² > 0 → min",w:"second-derivative test"}],
defs:[{t:"Stationary point",d:"Point where dy/dx = 0 (max, min or point of inflection)."}],
worked:{q:"Find stationary points of y = x³ − 3x² − 9x + 5.",steps:["dy/dx = 3x² − 6x − 9 = 0 → x² − 2x − 3 = 0 → x = 3 or x = −1.","Points: (3, −22) and (−1, 10).","d²y/dx² = 6x − 6: at 3 → 12 > 0 MIN; at −1 → −12 < 0 MAX."]},
mistakes:["Differentiating before simplifying (expand brackets, split fractions first).","Forgetting to find the Y-coordinate of stationary points.","Normal gradient = −1/m, not −m."],
tips:["'Show (2, 5) is a maximum' → substitute into dy/dx (= 0) AND d²y/dx² (< 0).","Optimisation: define variables, eliminate to one variable, differentiate."],
oos:"<b>Beyond syllabus:</b> Newton vs Leibniz fought over calculus; dy/dx is Leibniz's notation winning."}},
{id:"P1T6", name:"Integration (P1)", tags:"integration area under curve definite indefinite constant",
notes:{lede:"The reverse of differentiation: indefinite and definite integrals and areas under curves.",
points:[
"<b>Power rule:</b> ∫xⁿ dx = xⁿ⁺¹/(n+1) + c (n ≠ −1). Add +c ALWAYS for indefinite integrals. Check by differentiating back.",
"<b>Definite:</b> ∫ₐᵇ f(x) dx = [F(x)]ₐᵇ = F(b) − F(a). No +c (cancels). Negative answers = net signed area below axis.",
"<b>Area under curve:</b> integrate y dx between limits. If the curve CROSSES the axis, split at roots and ADD absolute areas.",
"<b>Area between curves/lines:</b> ∫(top − bottom) dx between intersection x-values. Find intersections first!",
"<b>Kinematics link (M1):</b> integrate acceleration → velocity → displacement (+c from initial conditions)."],
formulas:[{e:"∫xⁿ dx = xⁿ⁺¹/(n+1) + c",w:"power rule"},{e:"∫ₐᵇ = F(b) − F(a)",w:"definite integral"}],
defs:[{t:"Indefinite integral",d:"Family of antiderivatives (+ c) — the reverse of differentiation."}],
worked:{q:"Find the area enclosed by y = x² − 4 and the x-axis.",steps:["Roots: x = ±2. Curve below axis between → area = −∫₋₂² (x²−4) dx.","−[x³/3 − 4x]₋₂² = −[(8/3−8) − (−8/3+8)] = −[−32/3] = 32/3.","Area = 10.7 square units (positive!)."]},
mistakes:["Dropping +c in indefinite integration (loses the mark).","Integrating across a root without splitting — signed areas cancel.","∫1/x = ln|x| (P2) — the power rule FAILS for n = −1."],
tips:["Sketch first: roots and top/bottom decide the whole setup.","'Find the equation given dy/dx and a point' → integrate, use point for c."],
oos:"<b>Beyond syllabus:</b> the integral sign ∫ is a stretched S (summa) — integration is infinite summation."}}
]},
{id:"P2", code:"WMA12", short:"P2", title:"Pure Mathematics 2", level:"AS", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"P2T1", name:"Proof, Polynomials & Binomial Expansion", tags:"proof factor remainder theorem binomial expansion polynomial",
notes:{lede:"Proving, factoring and expanding: proof by exhaustion/contradiction, the factor theorem and binomial series.",
points:[
"<b>Proof by exhaustion:</b> check ALL cases (e.g. all residues mod n). <b>Disproof:</b> ONE counterexample suffices. <b>Contradiction (P4):</b> assume false → absurdity.",
"<b>Factor theorem:</b> (x − a) is a factor ⇔ f(a) = 0. <b>Remainder theorem:</b> remainder on ÷(x−a) is f(a). For (ax − b), use x = b/a.",
"<b>Algebraic division:</b> long division or compare coefficients after factorising. Cubic ÷ linear → quadratic → factorise/solve.",
"<b>Binomial (positive integer n):</b> (a+b)ⁿ = Σ ⁿCᵣ aⁿ⁻ʳbʳ. Coefficients from Pascal's triangle or ⁿCᵣ = n!/r!(n−r)!. (1+x)ⁿ expansions + approximations for small x.",
"<b>General binomial (P4):</b> (1+x)ⁿ for any n (fractions/negatives) with |x| < 1 validity — preview in P2 only for integer powers."],
formulas:[{e:"f(a) = 0 ⇔ (x−a) factor",w:"factor theorem"},{e:"ⁿCᵣ = n!/r!(n−r)!",w:"binomial coefficient"}],
defs:[{t:"Counterexample",d:"Single case disproving a general statement."}],
worked:{q:"Show (x − 2) is a factor of f(x) = x³ − 5x² + 8x − 4, then solve f(x) = 0.",steps:["f(2) = 8 − 20 + 16 − 4 = 0 ✓ so (x−2) is a factor.","Divide: f = (x−2)(x² − 3x + 2) = (x−2)(x−1)(x−2).","x = 2 (repeated) or x = 1."]},
mistakes:["f(a) with (2x−1): use x = ½, not x = 1.","Stopping at the quadratic without factorising/solving.","Binomial signs with (a−b)ⁿ — alternate the signs."],
tips:["'Find the remainder' → remainder theorem (one substitution), not long division.","Repeated roots: factor theorem twice, or check f'(a) = 0 too."],
oos:"<b>Beyond syllabus:</b> the binomial theorem generalises to infinite series — Newton's pride."}},
{id:"P2T2", name:"Sequences & Series", tags:"arithmetic geometric series sigma summation",
notes:{lede:"Patterns that pay: arithmetic and geometric progressions, sigma notation and sums to infinity.",
points:[
"<b>AP:</b> a, a+d, … nth term uₙ = a + (n−1)d. Sum Sₙ = n/2(2a + (n−1)d) = n/2(a + l).",
"<b>GP:</b> a, ar, … uₙ = arⁿ⁻¹. Sum Sₙ = a(1−rⁿ)/(1−r). Sum to infinity S∞ = a/(1−r) ONLY if |r| < 1 (convergent).",
"<b>Sigma Σ:</b> Σᵣ₌₁ⁿ means sum r = 1 to n. Split sums, factor constants out.",
"<b>Modelling:</b> AP for constant ADDITION (salary +£500/yr), GP for constant MULTIPLICATION (interest, decay, depreciation). State limitations (model breaks eventually).",
"<b>Recurrence/sequences:</b> uₙ₊₁ = f(uₙ) — iterate; increasing/decreasing/periodic behaviour; converge to fixed point (P3 iteration)."],
formulas:[{e:"uₙ = a+(n−1)d",w:"AP nth term"},{e:"S∞ = a/(1−r), |r|<1",w:"GP to infinity"}],
defs:[{t:"Convergent series",d:"Series with a finite sum to infinity (|r| < 1 for GP)."}],
worked:{q:"A GP has u₂ = 6, u₅ = 48. Find a, r and S∞ if it exists.",steps:["ar = 6, ar⁴ = 48 → r³ = 8 → r = 2, a = 3.","|r| = 2 > 1 → DIVERGES, no sum to infinity.","(If r were ½, S∞ = a/(1−r).)"]},
mistakes:["Using Sₙ with r > 1 in the (1−r) form — fine, but negatives trip people; use a(rⁿ−1)/(r−1).","S∞ when |r| ≥ 1 — always CHECK convergence.","Off-by-one: u₁ = a (n starts at 1)."],
tips:["'Show the series converges' → prove |r| < 1 first.","Word problems: identify AP vs GP from 'same amount' vs 'same proportion'."],
oos:"<b>Beyond syllabus:</b> 1 + ½ + ¼ + … = 2 settled Zeno's paradox — infinities can sum."}},
{id:"P2T3", name:"Exponentials & Logarithms", tags:"exponential logarithm ln growth decay reduction linear form",
notes:{lede:"Growth and decay: eˣ, log laws, solving exponential equations and straightening curves.",
points:[
"<b>y = aˣ:</b> through (0,1), asymptote y = 0; growth (a > 1), decay (0 < a < 1). <b>e ≈ 2.718</b> — natural base; y = eˣ has gradient = value (why calculus loves it).",
"<b>Log laws:</b> log(ab) = log a + log b • log(a/b) = log a − log b • log(aⁿ) = n log a • log_a(a) = 1. ln = log_e.",
"<b>Solving:</b> same base → equate powers; else take logs: aˣ = b → x = log b / log a. eˣ = k → x = ln k.",
"<b>Growth/decay models:</b> N = N₀e^(kt) (k > 0 growth, < 0 decay). Half-life: t½ = ln2/|k|. Doubling time likewise.",
"<b>Reduction to linear form:</b> y = abˣ → log y = log a + x log b (plot log y vs x). y = axⁿ → log y = log a + n log x. Gradient/intercept give constants."],
formulas:[{e:"log(ab) = log a + log b",w:"first log law"},{e:"aˣ = b → x = logb/loga",w:"solving exponentials"}],
defs:[{t:"Natural logarithm",d:"Log base e (ln) — inverse of eˣ."}],
worked:{q:"Bacteria N = 500e^(0.2t). When does N reach 5000?",steps:["5000 = 500e^0.2t → 10 = e^0.2t.","ln 10 = 0.2t → t = 2.3026/0.2 = 11.5 hours.","Check: e^2.3 ≈ 10 ✓"]},
mistakes:["log(a+b) split as log a + log b — laws apply to ×/÷, NOT +/−.","Forgetting ln and e cancel: ln(eˣ) = x.","Linear-form plots: wrong log base mix (use one base throughout)."],
tips:["'Show data fits y = abˣ' → plot log y vs x, straight line proves it.","Half-life Qs: set N = N₀/2 and solve — works for any base."],
oos:"<b>Beyond syllabus:</b> log scales (Richter, decibels, pH) compress huge ranges — same laws."}},
{id:"P2T4", name:"Trigonometry (P2): Identities, Equations & Radians", tags:"trigonometry identities radians equations small angle",
notes:{lede:"Trig level 2: exact equations, identities, radians and arc/segment area.",
points:[
"<b>Identities:</b> tanθ = sinθ/cosθ • sin²θ + cos²θ = 1. Use to rewrite equations in ONE trig function, then solve.",
"<b>Solving (degrees or radians):</b> principal value → CAST/other quadrants in RANGE → all solutions. Always check the given interval!",
"<b>Radians:</b> π rad = 180°. Arc length s = rθ, sector area A = ½r²θ, segment = sector − triangle (½r²(θ − sinθ)).",
"<b>Small-angle approximations (θ in RADIANS):</b> sinθ ≈ θ, cosθ ≈ 1 − θ²/2, tanθ ≈ θ — for limits and approximations.",
"<b>Graphs:</b> solve graphically (intersections) or analytically; transformations change period/amplitude (y = 3sin2x: amplitude 3, period 180°)."],
formulas:[{e:"sin²θ + cos²θ = 1",w:"Pythagorean identity"},{e:"s = rθ, A = ½r²θ",w:"arc & sector (radians)"}],
defs:[{t:"Radian",d:"Angle subtending arc length = radius; 2π rad = 360°."}],
worked:{q:"Solve 2sin²x − sin x − 1 = 0 for 0° ≤ x < 360°.",steps:["Factor: (2sin x + 1)(sin x − 1) = 0 → sin x = −½ or 1.","sin x = 1 → x = 90°. sin x = −½ → x = 210°, 330°.","Solutions: 90°, 210°, 330°."]},
mistakes:["Dividing by cos x (loses solutions) — factorise instead.","Radian/degree mode mismatch — #1 trig error.","Forgetting θ − sinθ needs θ in RADIANS for segment area."],
tips:["Rewrite everything in sin OR cos first, then substitute u = sin x.","List solutions systematically with CAST — missing one is the classic lost mark."],
oos:"<b>Beyond syllabus:</b> radians make d/dx(sin x) = cos x exact — degrees would add an ugly constant."}},
{id:"P2T5", name:"Differentiation & Integration (P2)", tags:"differentiation tangents trapezium rule definite integration",
notes:{lede:"Calculus grows: connected ideas, more areas and the trapezium rule for awkward integrals.",
points:[
"<b>Applications of differentiation:</b> tangents/normals (harder functions), stationary points + classification, increasing/decreasing, optimisation with constraints, small changes preview.",
"<b>Definite integration:</b> areas under curves (split at roots!), areas between curve and LINE (find intersections, ∫(top−bottom)).",
"<b>Trapezium rule:</b> ∫ₐᵇ f ≈ h/2 [y₀ + yₙ + 2(y₁+…+yₙ₋₁)], h = (b−a)/n. MORE strips = better. Over/underestimates: concave-down (∩) → trapezium UNDER; concave-up (∪) → OVER.",
"<b>∫1/x = ln|x| + c</b> — the missing power-rule case. Definite versions give exact areas with ln.",
"<b>Kinematics:</b> given a(t): integrate for v(t), s(t) using initial conditions; max height when v = 0."],
formulas:[{e:"∫ₐᵇf ≈ h/2[y₀+yₙ+2Σ]",w:"trapezium rule"},{e:"∫1/x dx = ln|x|+c",w:"the log integral"}],
defs:[{t:"Trapezium rule",d:"Numerical integration using trapeziums — exact for straight lines."}],
worked:{q:"Estimate ∫₀² √(1+x³) dx with 4 strips (n = 4).",steps:["h = 0.5; x = 0, 0.5, 1, 1.5, 2 → y = 1, 1.0607, 1.4142, 2.0917, 3.","Integral ≈ 0.25[1 + 3 + 2(1.0607+1.4142+2.0917)] = 0.25 × 13.133 = 3.28.","Curve ∪-shaped → slight overestimate."]},
mistakes:["Trapezium: forgetting ×2 on MIDDLE ordinates only.","ln|x| without modulus — or without +c.","Area between curve and line: integrating the wrong way round."],
tips:["Show the strip table (x, y) — method marks even if arithmetic slips.","'Explain over/underestimate' → sketch trapeziums vs curve concavity."],
oos:"<b>Beyond syllabus:</b> Simpson's rule (parabolas) beats trapeziums — same idea, curvier."}},
{id:"P2T6", name:"Circles & Coordinate Geometry (P2)", tags:"circles tangents geometry intersection",
notes:{lede:"Circle geometry: equations, tangents, intersections and geometric proofs.",
points:[
"<b>Circle:</b> (x−a)² + (y−b)² = r²; centre (a, b), radius r. From x² + y² + 2gx + 2fy + c = 0: centre (−g, −f), r = √(g² + f² − c).",
"<b>Tangent at point:</b> radius gradient → perpendicular → line equation. <b>Tangents from external point:</b> solve |distance from centre| = r conditions (often quadratic → 2 tangents).",
"<b>Line–circle intersections:</b> substitute → quadratic → discriminant: 2 = secant, 1 = tangent, 0 = miss.",
"<b>Circle–circle:</b> compare centre distance d with r₁ ± r₂ (separate, touching, intersecting, inside).",
"<b>Geometric facts:</b> angle in semicircle = 90° (Thales) — proves right angles; perpendicular from centre bisects chords."],
formulas:[{e:"(x−a)² + (y−b)² = r²",w:"circle equation"},{e:"r = √(g²+f²−c)",w:"from general form"}],
defs:[{t:"Chord",d:"Line segment joining two points on a circle."}],
worked:{q:"Show that x + y = 9 is a tangent to x² + y² = 41, and find the point.",steps:["Substitute y = 9−x: x² + (9−x)² = 41 → 2x² − 18x + 40 = 0 → x² − 9x + 20 = 0.","Discriminant: 81 − 80 = 1… ≠ 0? Recheck: x²+81−18x+x²=41 → 2x²−18x+40=0 → x²−9x+20=0 → (x−4)(x−5)=0.","Two points (4,5),(5,4) — it's a CHORD, not a tangent! (Always verify claims.)"]},
mistakes:["Centre signs from general form: (−g, −f), not (g, f).","Assuming tangency without checking discriminant = 0.","Tangent-from-point: forgetting there are TWO tangents."],
tips:["'Find the equation of the circle through…' → general form + simultaneous, or geometry (centre equidistant).","Sketch every circle Q — geometry guides algebra."],
oos:"<b>Beyond syllabus:</b> circle inversion turns lines into circles — a favourite olympiad trick."}}
]},
{id:"P3", code:"WMA13", short:"P3", title:"Pure Mathematics 3", level:"A2", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"P3T1", name:"Functions, Modulus & Partial Fractions", tags:"functions modulus partial fractions domain composite inverse",
notes:{lede:"A2 algebra foundations: composite/inverse functions, modulus graphs and partial fractions for integration.",
points:[
"<b>Composite fg(x) = f(g(x))</b> — inside first. Domain of fg: x must be valid for g AND g(x) valid for f.",
"<b>Inverse f⁻¹:</b> exists only if ONE-TO-ONE (restrict domain if needed, e.g. x ≥ 0 for x²). Find: y = f(x) → swap → solve. Domain of f⁻¹ = range of f.",
"<b>Modulus |x|:</b> reflect negative parts up over the x-axis. |f(x)| reflects below-axis parts; f(|x|) reflects the x ≥ 0 part left. Solve |ax+b| = k → two equations (squaring also works but check).",
"<b>Inequalities with modulus:</b> sketch BOTH sides, find intersections, read off. Or square (careful with domains).",
"<b>Partial fractions:</b> proper fraction → A/(x−a) + B/(x−b)…; repeated: + B/(x−a)²; quadratics: (Ax+B)/(x²+…). Cover-up or compare coefficients. Split TOP-HEAVY via division first.",
"<b>Purpose:</b> partial fractions turn hard integrals into ln integrals (P3T5)."],
formulas:[{e:"fg(x) = f(g(x))",w:"composition"},{e:"|a| = |b| → a = ±b",w:"modulus equations"}],
defs:[{t:"One-to-one",d:"Each y comes from exactly one x — required for an inverse."}],
worked:{q:"f(x) = 2x + 3 (x ≥ 0), g(x) = x². Find gf(x) and f⁻¹(x).",steps:["gf(x) = g(f(x)) = (2x+3)², domain x ≥ 0.","f⁻¹: y = 2x+3 → x = (y−3)/2 → f⁻¹(x) = (x−3)/2, domain x ≥ 3.","Domain of inverse = range of f: f ≥ 3 ✓"]},
mistakes:["fg vs gf order — they differ!","Inverse of x² on all ℝ — not a function; must restrict domain.","Partial fractions with top-heavy fractions — divide FIRST."],
tips:["Modulus sketch Qs: draw f first, then reflect — two stages, two marks.","Cover-up rule: for A/(x−a), set x = a in the whole identity."],
oos:"<b>Beyond syllabus:</b> partial fractions are the baby version of contour integration — complex analysis."}},
{id:"P3T2", name:"Trigonometry (P3): sec/csc/cot & Compound Angles", tags:"sec csc cot compound angle double angle r formula",
notes:{lede:"The full trig toolkit: reciprocal functions, compound and double-angle formulae and the R-formula.",
points:[
"<b>Reciprocals:</b> secθ = 1/cosθ • cosecθ = 1/sinθ • cotθ = 1/tanθ. Identities: 1 + tan²θ = sec²θ • 1 + cot²θ = cosec²θ. Domains exclude asymptotes.",
"<b>Compound angles:</b> sin(A±B), cos(A±B), tan(A±B) — in the formula book; use to get EXACT values (e.g. sin75° = sin(45+30)).",
"<b>Double angles:</b> sin2A = 2sinAcosA • cos2A = cos²A−sin²A = 2cos²A−1 = 1−2sin²A • tan2A = 2tanA/(1−tan²A). Three versions of cos2A — pick to match what you have.",
"<b>Half-angle forms:</b> cos²A = (1+cos2A)/2, sin²A = (1−cos2A)/2 — essential for INTEGRATION (P3T5).",
"<b>R-formula:</b> a sinθ ± b cosθ = R sin(θ ± α), R = √(a²+b²), tanα = b/a (check quadrant!). For max/min (amplitude R) and solving equations.",
"<b>Solving:</b> convert multiple angles (express everything in θ or 2θ consistently), watch the RANGE (2θ doubles the interval!)."],
formulas:[{e:"cos2A = 2cos²A − 1",w:"double angle"},{e:"R = √(a²+b²)",w:"R-formula amplitude"}],
defs:[{t:"Principal value",d:"Inverse-trig output in the standard range (calculator value)."}],
worked:{q:"Express 3sinθ + 4cosθ in R sin(θ+α) form, and find its maximum.",steps:["R = √(9+16) = 5; tanα = 4/3 → α = 53.13°.","= 5sin(θ + 53.1°). Max = 5 at θ + 53.1° = 90° → θ = 36.9°.","(Check quadrant: a,b > 0 → α acute ✓)"]},
mistakes:["α in the wrong quadrant — sketch a,b signs first.","Range errors with 2θ: 0 ≤ θ < 360° means 0 ≤ 2θ < 720°.","Using degrees in calculus — differentiate trig in RADIANS."],
tips:["cos2A: three forms — choose the one killing the function you don't want.","R-formula max/min: max = R, min = −R, found when sin = ±1."],
oos:"<b>Beyond syllabus:</b> e^(iθ) = cosθ + i sinθ unites trig with exponentials — Euler's gem."}},
{id:"P3T3", name:"Exponentials, Logs & Modelling (P3)", tags:"exponential modelling growth log laws",
notes:{lede:"eˣ grows up: harder exponential equations, the eˣ/calculus link preview and real-world modelling.",
points:[
"<b>Log laws fluency:</b> solve equations with logs on both sides (combine → drop logs → check validity: arguments > 0!).",
"<b>eˣ equations:</b> e^(2x) − 5e^x + 6 = 0 → substitute u = e^x → quadratic. Always u > 0 — reject non-positive roots!",
"<b>Modelling:</b> N = ab^t or N₀e^(kt); find constants from data (two points or linearised plot); interpret (initial value, growth rate); critique (bounded reality — model fails long-term).",
"<b>Differentiation preview:</b> d/dx(eˣ) = eˣ, d/dx(ln x) = 1/x — proved properly in P3T4, used freely after."],
formulas:[{e:"e²ˣ − 5eˣ + 6 = 0 → u = eˣ",w:"substitute quadratics"}],
defs:[{t:"Mathematical model",d:"Equation describing reality — with assumptions and limits."}],
worked:{q:"Solve e^(2x) − 4e^x + 3 = 0.",steps:["u = e^x: u² − 4u + 3 = 0 → u = 1 or u = 3.","x = ln 1 = 0 or x = ln 3.","Both valid (u > 0) ✓"]},
mistakes:["Accepting u ≤ 0 roots for e^x substitutions.","Log of negative/zero slipping through — always CHECK.","Model extrapolation beyond data range without comment."],
tips:["'Comment on the model' → short-term good, long-term fails (limits, saturation).","Two data points → two equations → solve for a and k."],
oos:"<b>Beyond syllabus:</b> logistic curves fix exponential blow-up — the S-curve of epidemics."}},
{id:"P3T4", name:"Differentiation (P3): Chain, Product & Quotient", tags:"chain rule product quotient rule exponential trig differentiation",
notes:{lede:"Differentiating anything: the three rules plus eˣ, ln x and trig derivatives.",
points:[
"<b>Chain rule:</b> y = f(g(x)) → dy/dx = f'(g)·g'(x). Think: differentiate outside, × differentiate inside. E.g. (3x+1)⁵ → 15(3x+1)⁴.",
"<b>Product rule:</b> (uv)' = u'v + uv'. E.g. x²sin x → 2x sin x + x²cos x.",
"<b>Quotient rule:</b> (u/v)' = (u'v − uv')/v². E.g. (x+1)/(x−1) → −2/(x−1)². (Or rewrite as product with ( )⁻¹ — often easier!)",
"<b>Standard derivatives:</b> eˣ→eˣ • ln x→1/x • sin→cos • cos→−sin • tan→sec² (prove via quotient!). aˣ → aˣ ln a.",
"<b>With chain:</b> e^(3x)→3e^(3x); sin(2x)→2cos(2x); ln(x²+1)→2x/(x²+1).",
"<b>Applications:</b> tangents/normals, stationary points, increasing/decreasing proofs, optimisation — same P1 ideas, harder functions."],
formulas:[{e:"(uv)' = u'v + uv'",w:"product rule"},{e:"(u/v)' = (u'v−uv')/v²",w:"quotient rule"},{e:"dy/dx = dy/du · du/dx",w:"chain rule"}],
defs:[{t:"Stationary point",d:"dy/dx = 0 — classify via sign or second derivative."}],
worked:{q:"Differentiate y = x²e^(3x) and find stationary points.",steps:["Product: dy/dx = 2xe^3x + 3x²e^3x = xe^3x(2 + 3x).","= 0 → x = 0 or x = −2/3.","Points (0, 0) and (−2/3, 4e⁻²/9); classify via d²y/dx² or sign test."]},
mistakes:["Quotient numerator order: u'v − uv' (minus!) — the top error.","Forgetting × inside-derivative in chain rule.","Product rule written as u'v' — it's u'v + uv'."],
tips:["Factorise dy/dx (common e^(…)/powers) BEFORE solving = 0.","For quotients, consider rewriting as products — fewer sign errors."],
oos:"<b>Beyond syllabus:</b> the chain rule is why neural networks learn — backpropagation is chains all the way down."}},
{id:"P3T5", name:"Integration (P3)", tags:"integration standard forms substitution f prime over f areas",
notes:{lede:"Integrating properly: standard forms, f'/f, integrating trig powers and areas with harder curves.",
points:[
"<b>Standard forms:</b> ∫eˣ = eˣ • ∫1/x = ln|x| • ∫sin = −cos • ∫cos = sin • ∫sec² = tan. With linear inner: divide by its gradient (∫e^(3x) = e^(3x)/3).",
"<b>Reverse chain:</b> ∫2x(x²+1)⁵ = (x²+1)⁶/6 — spot the inside-derivative. ∫f'(x)/f(x) = ln|f(x)| + c (numerator = derivative of denominator!).",
"<b>Trig powers:</b> use cos2A forms: ∫sin²x = ∫(1−cos2x)/2 = x/2 − sin2x/4. ∫cos²x similarly. ∫tan²x = ∫(sec²x − 1) = tan x − x.",
"<b>Definite integrals:</b> exact answers with e, ln, π. Areas: split at roots, top−bottom for regions between curves.",
"<b>Partial fractions → integrals:</b> A/(x−a) integrates to A ln|x−a| (P3T1 pays off here)."],
formulas:[{e:"∫f'/f = ln|f| + c",w:"log integration"},{e:"∫sin²x = x/2 − sin2x/4",w:"via double angle"}],
defs:[{t:"Reverse chain rule",d:"Integrating f'(g)·g' by spotting the composition."}],
worked:{q:"Evaluate ∫₀^(π/2) sin²x dx.",steps:["sin²x = (1 − cos2x)/2.","∫ = [x/2 − sin2x/4]₀^(π/2) = (π/4 − 0) − (0 − 0) = π/4.","No calculator needed — exact form."]},
mistakes:["Forgetting ÷gradient for linear inners (∫cos(2x) = sin(2x)/2).","ln without modulus or +c.","Integrating sin²x as −⅓cos³x style errors — use double-angle FIRST."],
tips:["See a fraction? Ask: is top the derivative of bottom? → ln. Else: partial fractions.","Definite trig integrals: keep π symbolic until the end."],
oos:"<b>Beyond syllabus:</b> ∫e^(−x²) has no elementary form — yet its definite integral is √π."}},
{id:"P3T6", name:"Numerical Methods", tags:"numerical methods iteration newton raphson change of sign",
notes:{lede:"Solving the unsolvable: sign-change location, iteration and Newton–Raphson.",
points:[
"<b>Existence:</b> continuous f with f(a), f(b) opposite signs → root in (a, b). Show f(a)×f(b) < 0 with VALUES.",
"<b>Iteration xₙ₊₁ = g(xₙ):</b> rearrange f(x) = 0 into x = g(x); iterate from x₀; converges if |g'(x)| < 1 near root (staircase/cobweb diagrams). Quote to required d.p. with extra digit working.",
"<b>Newton–Raphson:</b> xₙ₊₁ = xₙ − f(xₙ)/f'(xₙ) — tangent-chasing, converges FAST (quadratic) near simple roots. Fails if f' = 0 nearby, poor x₀, or cycles/oscillates.",
"<b>Rearrangement choice:</b> many g(x) exist; some converge, some diverge — check |g'| < 1 or test convergence.",
"<b>Answers:</b> iterate to stability, state the root to the required accuracy, verify with a sign-change check in a small interval."],
formulas:[{e:"xₙ₊₁ = xₙ − f/f'",w:"Newton–Raphson"},{e:"|g'(x)| < 1",w:"convergence condition"}],
defs:[{t:"Convergence",d:"Iterates approaching a fixed limit (the root)."}],
worked:{q:"f(x) = x³ − x − 2. Show a root in [1, 2]; one Newton step from x₀ = 1.5.",steps:["f(1) = −2 < 0, f(2) = 4 > 0 → sign change → root in (1,2).","f'(x) = 3x² − 1; x₁ = 1.5 − f(1.5)/f'(1.5) = 1.5 − (−0.125)/5.75 = 1.5217.","True root ≈ 1.5214 — one step already 3 d.p.!"]},
mistakes:["Claiming a root from sign change without CONTINUITY stated.","Rounding mid-iteration — keep 5+ s.f., round only at the end.","Newton with f'(xₙ) = 0 — formula explodes; choose new x₀."],
tips:["'Show the iteration converges' → compute 3–4 iterates tending to a limit.","Always finish with a sign-change verification interval."],
oos:"<b>Beyond syllabus:</b> Newton fractals colour which root each start finds — chaos from calculus."}}
]},
{id:"P4", code:"WMA14", short:"P4", title:"Pure Mathematics 4", level:"A2", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"P4T1", name:"Proof by Contradiction & General Binomial", tags:"proof contradiction binomial general expansion validity",
notes:{lede:"Proving the impossible and expanding everything: contradiction proofs and the full binomial series.",
points:[
"<b>Proof by contradiction:</b> assume the statement FALSE → follow logic → reach an impossibility → original must be TRUE. Classics: √2 irrational, infinite primes, no largest prime.",
"<b>√2 template:</b> assume √2 = a/b (lowest terms) → 2b² = a² → a even → a = 2c → b even → contradicts lowest terms. Adapt for √3, √5….",
"<b>General binomial:</b> (1+x)ⁿ = 1 + nx + n(n−1)x²/2! + … for ANY real n, valid |x| < 1. Coefficients: n(n−1)(n−2)…/r!.",
"<b>With (a+bx)ⁿ:</b> factor out aⁿ → aⁿ(1 + bx/a)ⁿ, expand, validity |bx/a| < 1 i.e. |x| < |a/b|.",
"<b>Uses:</b> approximations (√1.02 ≈ 1 + x/2…), expansions to x³, partial fractions → binomial for integrals/series."],
formulas:[{e:"(1+x)ⁿ = 1+nx+n(n−1)x²/2+…",w:"general binomial, |x|<1"}],
defs:[{t:"Contradiction",d:"Proof method: assume negation, derive absurdity."}],
worked:{q:"Expand √(4+x) to x² and state validity.",steps:["√(4+x) = 2(1 + x/4)^½.","= 2[1 + ½(x/4) + (½)(−½)(x/4)²/2] = 2 + x/4 − x²/64.","Valid |x/4| < 1 → |x| < 4."]},
mistakes:["Forgetting to factor out the constant FIRST in (a+bx)ⁿ.","Validity in terms of x after factoring — rescale!","Binomial coefficients with negative n: signs — write (n−1),(n−2) carefully."],
tips:["'Show the expansion is valid' → derive the |x| range explicitly.","√2-style proofs: memorise the skeleton, adapt the numbers."],
oos:"<b>Beyond syllabus:</b> Euclid's infinite-primes proof (c. 300 BC) still delights — contradiction's crown jewel."}},
{id:"P4T2", name:"Differentiation (P4): Implicit, Parametric & Rates", tags:"implicit parametric connected rates differentiation",
notes:{lede:"Advanced differentiation: implicit curves, parametric equations and connected rates of change.",
points:[
"<b>Implicit:</b> differentiate every term w.r.t. x; y-terms need × dy/dx (chain). E.g. x² + y² = 25 → 2x + 2y dy/dx = 0 → dy/dx = −x/y.",
"<b>Tangents to implicit curves:</b> find dy/dx, substitute the point. Vertical tangent when denominator = 0 (dy/dx infinite).",
"<b>Parametric:</b> x = x(t), y = y(t) → dy/dx = (dy/dt)/(dx/dt). Second derivative: differentiate dy/dx w.r.t. t, ÷ dx/dt. Convert to Cartesian by eliminating t.",
"<b>Connected rates:</b> chain rule with time: dV/dt = dV/dr × dr/dt. Write the chain, substitute knowns. Volumes: sphere 4πr³/3, cone πr²h/3 — eliminate extra variables via similar shapes/ratio FIRST.",
"<b>Small increments:</b> δy ≈ dy/dx × δx (linear approximation)."],
formulas:[{e:"dy/dx = (dy/dt)/(dx/dt)",w:"parametric differentiation"},{e:"dV/dt = dV/dr·dr/dt",w:"connected rates"}],
defs:[{t:"Parametric equations",d:"x and y each defined via a parameter t."}],
worked:{q:"x = 2t, y = t². Find dy/dx and the Cartesian equation.",steps:["dx/dt = 2, dy/dt = 2t → dy/dx = 2t/2 = t.","t = x/2 → dy/dx = x/2. Cartesian: t = x/2 → y = x²/4.","Check: differentiating y = x²/4 gives x/2 ✓"]},
mistakes:["Implicit: forgetting × dy/dx on y-terms.","Parametric second derivative: differentiating w.r.t. x wrongly — ÷ dx/dt again.","Connected rates: substituting r's VALUE before differentiating."],
tips:["Parametric tangents: find t at the point FIRST, then dy/dx at that t.","Similar-triangles elimination before differentiating cones."],
oos:"<b>Beyond syllabus:</b> parametric curves draw fonts and roller-coasters — Bézier curves run design."}},
{id:"P4T3", name:"Integration (P4): Parts, Substitution, Volumes & ODEs", tags:"integration parts substitution volumes revolution differential equations",
notes:{lede:"The integration arsenal: parts, substitution, volumes of revolution and first-order differential equations.",
points:[
"<b>By parts:</b> ∫u dv/dx = uv − ∫v du/dx. Choose u via ILATE (Inverse-trig, Log, Algebraic, Trig, Exp — u first in list). E.g. ∫x sinx: u = x. Repeat or cycle (eˣsinx needs twice + rearrange).",
"<b>By substitution:</b> spot inner function: u = g(x), du = g'dx. E.g. ∫x√(x²+1): u = x²+1. Change LIMITS for definite integrals (or substitute back).",
"<b>Trig substitutions/half-angle:</b> ∫1/(a²+x²) = (1/a)arctan(x/a). ∫ involving √(a²−x²): x = a sinθ (in formula book).",
"<b>Volumes of revolution:</b> about x-axis: V = π∫y² dx. About y-axis: V = π∫x² dy. Between curves: subtract volumes. Sketch + limits from intersections.",
"<b>Trapezium volumes:</b> numerical V ≈ π × trapezium on y² values.",
"<b>First-order ODEs (separable):</b> dy/dx = f(x)g(y) → ∫dy/g(y) = ∫f(x)dx → general solution + c → particular via given point. Models: cooling, decay, population, flow."],
formulas:[{e:"∫u v' = uv − ∫v u'",w:"integration by parts"},{e:"V = π∫y²dx",w:"volume about x-axis"}],
defs:[{t:"Separable ODE",d:"dy/dx factorises into f(x)·g(y) — split and integrate."}],
worked:{q:"Find ∫x cos x dx.",steps:["Parts: u = x, dv/dx = cos x → du/dx = 1, v = sin x.","= x sin x − ∫sin x dx = x sin x + cos x + c.","Differentiate back to verify ✓"]},
mistakes:["Parts: wrong u choice (differentiate the polynomial!).","Substitution: forgetting to change limits in definite integrals.","Volumes: integrating y not y², or missing π."],
tips:["ILATE for parts; inner-derivative spotting for substitution.","ODE: +c BEFORE using the condition; then solve for the particular."],
oos:"<b>Beyond syllabus:</b> ODEs model everything from pandemics to planets — applied maths' mother tongue."}},
{id:"P4T4", name:"Vectors", tags:"vectors dot product lines planes magnitude",
notes:{lede:"Arrows with attitude: vector algebra, lines in 3D and the scalar product.",
points:[
"<b>Basics:</b> magnitude |a| = √(x²+y²+z²); unit vector â = a/|a|; position vectors; AB = b − a. Parallel vectors are scalar multiples.",
"<b>Scalar (dot) product:</b> a·b = |a||b|cosθ = a₁b₁ + a₂b₂ + a₃b₃. Perpendicular ⇔ a·b = 0. Angle: cosθ = (a·b)/(|a||b|).",
"<b>Line equation:</b> r = a + λd (a = point, d = direction). Cartesian: (x−a₁)/d₁ = (y−a₂)/d₂ = (z−a₃)/d₃ (if dᵢ ≠ 0).",
"<b>Intersections:</b> equate components with DIFFERENT parameters (λ, μ) → solve 2 equations → VERIFY in the 3rd. No solution = skew (3D) or parallel.",
"<b>Distance from point to line:</b> foot of perpendicular via (p − (a+λd))·d = 0 → solve λ → distance. (Or area/cross-product methods — dot-product foot is syllabus-safe.)",
"<b>Applications:</b> shortest distance between skew lines (preview), geometry proofs (midpoints, parallel/perpendicular)."],
formulas:[{e:"a·b = |a||b|cosθ",w:"scalar product"},{e:"r = a + λd",w:"vector line"}],
defs:[{t:"Skew lines",d:"Non-parallel 3D lines that never meet."}],
worked:{q:"Find the angle between a = 2i − j + 2k and b = i + 2j − k.",steps:["a·b = 2 − 2 − 2 = −2.","|a| = 3, |b| = √6.","cosθ = −2/(3√6) → θ = 105.8°."]},
mistakes:["Same parameter for two lines — always λ and μ.","Forgetting to VERIFY the third component (skew trap).","Angle > 180°? Use the acute/obtuse from arccos directly (0–180°)."],
tips:["Perpendicular facts → dot product = 0 is the workhorse.","Foot-of-perpendicular: let F = a + λd, solve (p−F)·d = 0."],
oos:"<b>Beyond syllabus:</b> vectors + matrices = linear algebra — the engine of graphics and AI."}}
]},
{id:"S1", code:"WST01", short:"S1", title:"Statistics 1", level:"AS/A2", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"S1T1", name:"Data: Location, Spread & Representation", tags:"mean median standard deviation box plot histogram cumulative frequency",
notes:{lede:"Summarising data: averages, spread, outliers and the right diagram for the job.",
points:[
"<b>Location:</b> mean x̄ = Σx/n (uses all data, pulled by extremes) • median (middle, robust) • mode (most frequent). For grouped: midpoints × frequencies.",
"<b>Spread:</b> range • IQR = Q3 − Q1 (robust) • variance σ² = Σ(x−x̄)²/n • <b>standard deviation σ = √variance</b>. Coding: y = (x−a)/b simplifies grouped calcs.",
"<b>Outliers:</b> < Q1 − 1.5×IQR or > Q3 + 1.5×IQR (small k for large data: Q1 − k(Q3−Q1) variants exist — IAL uses 1.5×IQR or mean ± 2/3σ). Plot × on box plots, investigate, don't auto-delete.",
"<b>Diagrams:</b> stem-and-leaf (shape + values) • box plot (median, quartiles, range, outliers) • histogram (AREA ∝ frequency; frequency DENSITY = f/class width) • cumulative frequency (median/quartiles by interpolation).",
"<b>Skew:</b> positive (tail right: mean > median) • negative (tail left) • symmetric. Compare distributions: location AND spread AND skew, with VALUES.",
"<b>Interpolation:</b> median from grouped: L + ((n/2 − F)/f)×w. Show the formula with values substituted."],
formulas:[{e:"σ = √(Σ(x−x̄)²/n)",w:"standard deviation"},{e:"outlier < Q1−1.5IQR",w:"outlier rule"}],
defs:[{t:"Frequency density",d:"Frequency ÷ class width — histogram bar HEIGHT."}],
worked:{q:"Data: 12, 15, 18, 20, 45. Mean, median, and is 45 an outlier?",steps:["Mean = 110/5 = 22; median = 18.","Q1 = 13.5, Q3 = 32.5, IQR = 19; upper fence = 32.5 + 28.5 = 61.","45 < 61 → NOT an outlier (just skews the mean — median better here)."]},
mistakes:["Histogram bars ∝ frequency with UNEQUAL widths — use frequency DENSITY.","Median position (n+1)/2 vs n/2 for grouped continuous — follow the interpolation formula.","Comparing distributions with only averages — always add spread + skew."],
tips:["Calculator stats mode for x̄ and σ — but SHOW the formula/value for method marks.","Box-plot comparisons: three points minimum (median, IQR, skew/range)."],
oos:"<b>Beyond syllabus:</b> Anscombe's quartet — identical stats, wildly different plots. Always graph!."}},
{id:"S1T2", name:"Probability", tags:"probability venn tree conditional independent mutually exclusive",
notes:{lede:"Chance done right: Venn diagrams, tree diagrams, conditional probability and independence.",
points:[
"<b>Basics:</b> P(A') = 1 − P(A). <b>Mutually exclusive:</b> P(A∩B) = 0 → P(A∪B) = P(A) + P(B). <b>Independent:</b> P(A∩B) = P(A)P(B) — occurrence doesn't affect.",
"<b>Addition law:</b> P(A∪B) = P(A) + P(B) − P(A∩B). Venn diagrams organise two/three-set problems.",
"<b>Tree diagrams:</b> multiply ALONG branches, add ACROSS outcomes. Conditional branches update after events (without replacement!).",
"<b>Conditional:</b> P(A|B) = P(A∩B)/P(B) — 'given B'. Read trees: second-branch probabilities are conditional.",
"<b>Sampling:</b> with replacement (independent, same p) vs without (hypergeometric-style counting — tree with changing denominators)."],
formulas:[{e:"P(A|B) = P(A∩B)/P(B)",w:"conditional probability"},{e:"P(A∪B) = P(A)+P(B)−P(A∩B)",w:"addition law"}],
defs:[{t:"Independent events",d:"P(A∩B) = P(A)×P(B) — neither affects the other."}],
worked:{q:"Bag: 4 red, 6 blue. Two drawn without replacement. P(both red)? P(one of each)?",steps:["P(RR) = 4/10 × 3/9 = 12/90 = 2/15.","P(one each) = P(RB) + P(BR) = (4×6 + 6×4)/90 = 48/90 = 8/15.","Without replacement → denominators change ✓"]},
mistakes:["Multiplying for unions (P(A∪B) ≠ P(A)P(B) — that's intersection of independents).","'Without replacement' treated as independent.","Conditional denominator: P(A|B) divides by P(B), not P(A)."],
tips:["Fill Venn CENTRE (intersection) first, work outwards.","Two-way tables often beat trees for 'given that' Qs."],
oos:"<b>Beyond syllabus:</b> Bayes' theorem flips conditionals — the maths behind spam filters and medical tests."}},
{id:"S1T3", name:"Correlation & Regression", tags:"correlation regression pmcc scatter explanatory response",
notes:{lede:"Relationships in data: scatter diagrams, PMCC and the regression line that predicts.",
points:[
"<b>Scatter diagram:</b> explanatory (independent) on x, response on y. Pattern: positive/negative/none; strength; outliers; (non-)linearity.",
"<b>PMCC r:</b> −1 ≤ r ≤ 1 — measures LINEAR correlation strength/direction. Near ±1 strong linear; near 0 weak/no LINEAR (could still be curved!). r = Sxy/√(Sxx·Syy).",
"<b>Regression line y on x:</b> y = a + bx, b = Sxy/Sxx (gradient), a = ȳ − bx̄ (passes through (x̄, ȳ)). Predict y from x ONLY.",
"<b>Interpolation (within range) = reliable; extrapolation (outside) = unreliable.</b> Always comment when predicting!",
"<b>Correlation ≠ causation:</b> lurking variables, coincidence — interpret carefully. Residuals (observed − predicted) reveal poor fits.",
"<b>Coding:</b> linear coding doesn't change r — compute with coded values freely."],
formulas:[{e:"b = Sxy/Sxx",w:"regression gradient"},{e:"r = Sxy/√(Sxx·Syy)",w:"PMCC"}],
defs:[{t:"PMCC",d:"Product-moment correlation coefficient — linear association measure."}],
worked:{q:"Sxx = 40, Sxy = 60, x̄ = 5, ȳ = 12. Regression line + predict x = 7.",steps:["b = 60/40 = 1.5; a = 12 − 1.5×5 = 4.5 → y = 4.5 + 1.5x.","x = 7 → y = 15.","Valid only if 7 lies within the data range (interpolation)."]},
mistakes:["Regressing x on y when asked y on x — b = Sxy/Sxx (x in denominator!).","Calling r = 0.1 'no relationship' — no LINEAR relationship (check the plot!).","Extrapolating without the reliability comment."],
tips:["Line passes through (x̄, ȳ) — use it to check/finish.","'Interpret b' → y increases by b per unit x (in CONTEXT)."],
oos:"<b>Beyond syllabus:</b> spurious correlations (cheese vs bedsheets!) warn: mechanism matters."}},
{id:"S1T4", name:"Discrete Random Variables & Distributions", tags:"random variable expectation variance binomial poisson",
notes:{lede:"Variables with probabilities: expectation, variance, binomial and Poisson models.",
points:[
"<b>Discrete RV:</b> table of x with P(X=x), ΣP = 1. <b>E(X) = ΣxP</b> (mean). <b>Var(X) = E(X²) − [E(X)]² = Σx²P − μ².</b>",
"<b>Linear transforms:</b> E(aX+b) = aE(X)+b; Var(aX+b) = a²Var(X) (b vanishes!).",
"<b>Binomial B(n,p):</b> fixed n trials, independent, two outcomes, constant p. P(X=r) = ⁿCᵣpʳ(1−p)ⁿ⁻ʳ. E(X) = np, Var = np(1−p). Use cumulative TABLES for P(X ≤ …) — show the expression + table value.",
"<b>Poisson Po(λ):</b> events in time/space: P(X=r) = e^(−λ)λʳ/r!. E = Var = λ. Adjust λ to the interval (λ for 2 hours = 2× hourly rate). Conditions: independent, single rate, random.",
"<b>Choosing:</b> fixed trials + p → binomial; rate over continuum → Poisson. Normal approximation (P2/S2 territory) NOT required — but continuity ideas preview.",
"<b>Hypothesis tests (S1 intro):</b> H₀ (p = …) vs H₁ (one/two-tail); find P(observed or more extreme); reject H₀ if < significance (5%/1%). State conclusion IN CONTEXT."],
formulas:[{e:"E(X) = ΣxP",w:"expectation"},{e:"Var = E(X²) − μ²",w:"variance"},{e:"P = ⁿCᵣpʳqⁿ⁻ʳ",w:"binomial"},{e:"P = e⁻λλʳ/r!",w:"Poisson"}],
defs:[{t:"Binomial conditions",d:"Fixed n, independent trials, two outcomes, constant p."}],
worked:{q:"X ~ B(10, 0.3). Find P(X = 4) and P(X ≤ 1).",steps:["P(X=4) = ¹⁰C₄(0.3)⁴(0.7)⁶ = 210 × 0.0081 × 0.117649 = 0.2001.","P(X≤1) = P(0) + P(1) = 0.7¹⁰ + 10(0.3)(0.7)⁹ = 0.0282 + 0.1211 = 0.1493.","(Or read cumulative tables: show P(X≤1) lookup.)"]},
mistakes:["Binomial without checking conditions (p changing = not binomial).","Poisson λ for the wrong interval — rescale first.","P(X < 2) vs P(X ≤ 2) — discrete boundaries matter."],
tips:["'Show X can be modelled by B(…)' → verify all 4 conditions in CONTEXT.","Hypothesis tests: critical region + actual comparison + contextual conclusion."],
oos:"<b>Beyond syllabus:</b> Poisson caught WW2 bomb patterns and predicts call centres — randomness has laws."}},
{id:"S1T5", name:"The Normal Distribution", tags:"normal distribution z-score standardise inverse",
notes:{lede:"The bell curve: standardising, finding probabilities and working backwards from areas.",
points:[
"<b>X ~ N(μ, σ²):</b> symmetric about μ, points of inflection at μ ± σ. Notation uses VARIANCE σ² (careful: tables need σ!).",
"<b>Standardise:</b> Z = (X − μ)/σ ~ N(0, 1). Then use tables/calculator: P(Z < z) = Φ(z). Symmetry: Φ(−z) = 1 − Φ(z).",
"<b>Finding probabilities:</b> P(X < a): standardise → Φ. P(a < X < b): Φ(b') − Φ(a'). P(X > a): 1 − Φ. Sketch the curve + shade!",
"<b>Inverse (given %):</b> find z for the area (tables backwards), then x = μ + zσ. E.g. top 5% → z = 1.6449.",
"<b>Finding μ/σ:</b> two percentile statements → two equations → solve simultaneously.",
"<b>Modelling:</b> heights, errors, natural variation — check symmetry/unimodality; discrete data needs continuity correction (S2) — S1 sticks to continuous."],
formulas:[{e:"Z = (X−μ)/σ",w:"standardisation"},{e:"x = μ + zσ",w:"inverse normal"}],
defs:[{t:"Standard normal",d:"N(0,1) — the tabled reference distribution."}],
worked:{q:"X ~ N(20, 9). Find P(X < 23) and the value exceeded by 10%.",steps:["σ = 3. z = (23−20)/3 = 1 → Φ(1) = 0.8413.","Top 10%: z = 1.2816 → x = 20 + 1.2816×3 = 23.84.","Sketch + shade both — visual checks catch errors."]},
mistakes:["Using variance (9) as σ — square-root FIRST.","Φ(−z) computed as −Φ(z) — it's 1 − Φ(z).","Inverse normal: confusing lower-tail with upper-tail areas."],
tips:["Always standardise explicitly — the z line earns a method mark.","'Find μ and σ' → two z-equations, solve simultaneously."],
oos:"<b>Beyond syllabus:</b> the Central Limit Theorem — means of anything become Normal. Statistics' superpower."}}
]},
{id:"M1", code:"WME01", short:"M1", title:"Mechanics 1", level:"AS/A2", time:"1 h 30 min", marks:75, weight:"16⅔% of IAL",
topics:[
{id:"M1T1", name:"Modelling, Vectors & Kinematics Foundations", tags:"modelling vectors kinematics displacement velocity",
notes:{lede:"Thinking like a mechanician: models, vector language and describing motion precisely.",
points:[
"<b>Modelling assumptions:</b> particle (no size/rotation) • light (massless) strings/rods • inextensible (fixed length) • smooth (no friction) • uniform • air resistance ignored. State them; refine if results disagree.",
"<b>Vectors:</b> magnitude + direction. Position/displacement/velocity/acceleration/force are vectors; distance/speed/mass/time are scalars. i, j notation: v = 3i − 2j.",
"<b>Vector kinematics:</b> differentiate/integrate component-wise: r(t) → v = dr/dt → a = dv/dt (+c vectors from initial conditions). Speed = |v|.",
"<b>Sign conventions:</b> choose positive direction, stick to it; g = 9.8 m s⁻² downwards (M1 uses 9.8!). Up = positive is common for vertical motion."],
formulas:[{e:"v = dr/dt, a = dv/dt",w:"vector calculus link"}],
defs:[{t:"Particle model",d:"Body treated as a point mass — rotation and size ignored."}],
worked:{q:"r = (3t² − 2t)i + 5t j. Find v and speed at t = 2.",steps:["v = dr/dt = (6t − 2)i + 5j.","At t=2: v = 10i + 5j.","Speed = √(100+25) = √125 = 11.2 m s⁻¹."]},
mistakes:["g = 9.81 (physics) vs 9.8 (M1) — use 9.8 unless told otherwise.","Speed vs velocity: speed = MAGNITUDE (positive scalar).","Forgetting +c (initial conditions) when integrating."],
tips:["List assumptions at the start of 'model' Qs — easy marks.","Differentiate/integrate EACH component separately."],
oos:"<b>Beyond syllabus:</b> all of M1 is Newton's Principia (1687) in modern dress."}},
{id:"M1T2", name:"Kinematics: suvat & Graphs", tags:"suvat kinematics graphs projectile vertical motion",
notes:{lede:"Motion maths: suvat equations, multi-stage journeys and reading motion graphs.",
points:[
"<b>suvat (constant a ONLY):</b> v = u + at • s = ut + ½at² • v² = u² + 2as • s = ½(u+v)t • s = vt − ½at². Pick the equation WITHOUT the variable you don't want.",
"<b>Vertical motion:</b> a = −g (if up positive). Max height: v = 0. Time of flight: s = 0 (back to start). Speed on return = launch speed (no air resistance).",
"<b>Multi-stage:</b> split journeys (accelerate → constant → decelerate); final of one stage = initial of next. Draw the v–t graph!",
"<b>Graphs:</b> s–t gradient = v; v–t gradient = a, AREA = displacement/distance. Distance vs displacement: distance adds absolute areas (below axis counts positive).",
"<b>Calculus forms:</b> non-constant a(t): integrate/differentiate; max/min via dv/dt = 0."],
formulas:[{e:"v = u + at",w:"suvat 1"},{e:"s = ut + ½at²",w:"suvat 2"},{e:"v² = u² + 2as",w:"suvat 3"}],
defs:[{t:"suvat",d:"Constant-acceleration equations linking s, u, v, a, t."}],
worked:{q:"Ball thrown up at 14 m s⁻¹ (g = 9.8). Max height and time to return?",steps:["Max: v² = u² − 2gs → 0 = 196 − 19.6s → s = 10 m.","Time up: v = u − gt → t = 14/9.8 = 1.43 s; total = 2.86 s.","(Or s = 0: 14t − 4.9t² = 0 → t = 2.86 s.)"]},
mistakes:["suvat with CHANGING acceleration — use calculus instead.","Sign chaos: pick up/down positive and KEEP it.","Distance vs displacement on v–t graphs crossing the axis."],
tips:["Write S U V A T, fill knowns, choose the equation — systematic = fast.","'Show that' times/heights: substitute, don't solve generally."],
oos:"<b>Beyond syllabus:</b> Galileo timed balls on ramps with his pulse — suvat before stopwatches."}},
{id:"M1T3", name:"Dynamics: Newton's Laws & Connected Particles", tags:"newton dynamics connected particles pulleys tension",
notes:{lede:"Forces cause acceleration: F = ma for single and connected bodies, pulleys and lifts.",
points:[
"<b>F = ma</b> along the direction of motion (resultant!). Draw force diagrams: weight (mg down), normal (⊥ surface), tension (along string), friction (opposes motion), thrust/driving force.",
"<b>Connected particles:</b> SAME speed/acceleration magnitude (inextensible string); tensions EQUAL either side of a smooth light pulley. Write F = ma for EACH mass, solve simultaneously.",
"<b>Pulleys:</b> direction changes; magnitudes shared. Atwood variations + strings over edges (with/without friction).",
"<b>Lifts:</b> accelerating up: R = m(g+a) (heavier); down: R = m(g−a) (lighter); constant: R = mg. Apparent weight = normal reaction.",
"<b>Resolving on slopes:</b> component down slope = mg sinθ, normal = mg cosθ. Then F = ma along the slope.",
"<b>Impulse preview:</b> F = ma with variable forces integrates to momentum ideas (M1T6)."],
formulas:[{e:"F = ma",w:"Newton II"},{e:"R = m(g±a)",w:"lift reaction"}],
defs:[{t:"Tension",d:"Pulling force in a string — same throughout a light string."}],
worked:{q:"3 kg and 5 kg joined over a smooth pulley. Find acceleration and tension.",steps:["Heavier falls: 5g − T = 5a; lighter rises: T − 3g = 3a.","Add: 2g = 8a → a = g/4 = 2.45 m s⁻².","T = 3(g + a) = 3 × 12.25 = 36.75 N."]},
mistakes:["One equation for two unknowns — write F = ma PER MASS.","Tension ≠ weight for accelerating masses.","Friction direction: opposes MOTION (or impending motion), not 'down the slope' by default."],
tips:["Add the two F = ma equations to kill T and find a fast.","State direction of acceleration explicitly."],
oos:"<b>Beyond syllabus:</b> Atwood's machine (1784) slowed free-fall to measurable — suvat verified."}},
{id:"M1T4", name:"Statics: Equilibrium & Friction", tags:"statics friction equilibrium limiting smooth rough",
notes:{lede:"Staying still: equilibrium (resultant = 0), friction limits and bodies on the point of slipping.",
points:[
"<b>Equilibrium:</b> resultant force = 0 (and resultant moment = 0 for rods — M1T5). Resolve in two perpendicular directions (usually ∥ and ⊥ to a surface).",
"<b>Friction:</b> F ≤ μR (μ = coefficient). Static adjusts up to LIMITING friction F_max = μR; at 'point of slipping'/'limiting equilibrium', F = μR exactly. Kinetic (sliding) friction ≈ μR.",
"<b>Rough slopes:</b> equilibrium: mg sinθ = F ≤ μR with R = mg cosθ. On the point of slipping: tanθ = μ. Steeper than arctan μ → slides.",
"<b>Strings/rods in equilibrium:</b> resolve horizontally AND vertically; two equations → two unknowns (tensions/angles).",
"<b>Smooth contact:</b> reaction ⊥ surface only (no friction). Rough: reaction has normal + friction components."],
formulas:[{e:"F ≤ μR",w:"friction law"},{e:"tanθ = μ (limiting)",w:"angle of friction"}],
defs:[{t:"Limiting friction",d:"Maximum static friction μR — motion impends beyond it."}],
worked:{q:"A 10 kg block rests on a rough slope (μ = 0.4) at 20°. Is it in equilibrium?",steps:["R = 10g cos20° = 92.1 N; F_max = 0.4 × 92.1 = 36.8 N.","Needed: mg sin20° = 33.5 N < 36.8 N → holds (F = 33.5 N).","Equilibrium ✓ (not limiting)."]},
mistakes:["Setting F = μR when NOT limiting — F only equals μR at the point of slipping.","Resolving weight wrong: down-slope = mg sinθ (not cos).","Forgetting the normal-reaction equation (need R for F_max)."],
tips:["'Find the range of θ/m for equilibrium' → limiting case gives the boundary.","Always state F ≤ μR then test — examiners love the inequality."],
oos:"<b>Beyond syllabus:</b> μ isn't constant — tyres, earthquakes and violin bows all break the simple law."}},
{id:"M1T5", name:"Moments & Centres of Mass", tags:"moments centre of mass equilibrium rods tilting toppling",
notes:{lede:"Turning effects: moments, couples, centres of mass and rods that tilt or topple.",
points:[
"<b>Moment = force × perpendicular distance</b> (Nm). Equilibrium of a rigid body: resultant force = 0 AND resultant moment = 0 (about ANY point — choose to eliminate an unknown!).",
"<b>Uniform rod:</b> weight acts at the MIDPOINT. Non-uniform: given centre of mass (or find via balance). Rods on pivots: reactions at supports; tilting = reaction at one end → 0.",
"<b>Couples:</b> two equal opposite parallel forces — pure turning, moment = F × separation (free vector).",
"<b>Centre of mass:</b> point where weight acts. Composite bodies: moments about an axis (Σmx/Σm). Hanging in equilibrium → COM below suspension; toppling when COM passes the base edge.",
"<b>Ladders (preview of M2 ideas at M1 level):</b> rough ground + smooth wall standard: resolve + moments about base → friction, reactions."],
formulas:[{e:"M = F × d⊥",w:"moment"},{e:"x̄ = Σmx/Σm",w:"centre of mass"}],
defs:[{t:"Couple",d:"Pair of equal, opposite, parallel forces producing pure rotation."}],
worked:{q:"Uniform 4 m rod (20 N) rests on pivots 1 m from each end. A 30 N child sits at one end. Find pivot reactions.",steps:["Pivots at x = 1 and x = 3; weight at x = 2; child at x = 0.","Moments about left pivot: R₂×2 = 20×1 + 30×1 → R₂ = 25 N.","Resolve: R₁ + 25 = 50 → R₁ = 25 N. (Check moments about right pivot ✓)"]},
mistakes:["Taking moments about a point then forgetting a force (weight! reactions!).","Distances from the WRONG point — label a datum.","Tilting conditions: reaction = 0 at the lifting end, not 'moments equal'."],
tips:["Moments about a pivot kills its unknown — fastest route.","Tilting/toppling: the lost-contact reaction is zero — state it."],
oos:"<b>Beyond syllabus:</b> the COM of the solar system wobbles outside the Sun — Jupiter bosses it around."}},
{id:"M1T6", name:"Momentum & Impulse", tags:"momentum impulse collisions conservation",
notes:{lede:"Collisions and kicks: conservation of momentum, impulse and Newton's experimental law preview.",
points:[
"<b>Momentum p = mv</b> (vector). <b>Impulse J = F·t = Δp</b> (constant F) or area under F–t graph. Units N s = kg m s⁻¹.",
"<b>Conservation:</b> total momentum conserved in collisions/explosions if no external impulse. m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂ (signs for direction!).",
"<b>Impacts:</b> impulse on each body EQUAL and OPPOSITE (Newton 3). A wall's impulse reverses the ball's momentum component.",
"<b>Explosions/recoil:</b> initial momentum usually 0 → momenta equal and opposite (gun recoil, ice skaters pushing apart).",
"<b>Variable force:</b> impulse = area under F–t (triangles/trapeziums in M1). Link to integration (P1/P2)."],
formulas:[{e:"J = Ft = Δp",w:"impulse–momentum"},{e:"Σmu = Σmv",w:"conservation"}],
defs:[{t:"Impulse",d:"Change in momentum from a force acting over time."}],
worked:{q:"2 kg at 3 m s⁻¹ hits stationary 4 kg; they coalesce. Find v and impulse on the 4 kg.",steps:["2×3 + 0 = 6v → v = 1 m s⁻¹.","Impulse on 4 kg = Δp = 4×1 − 0 = 4 N s.","(On the 2 kg: 2×1 − 2×3 = −4 N s — equal/opposite ✓)"]},
mistakes:["Sign errors: define positive direction FIRST.","Impulse direction: Δp = FINAL − initial (order!).","Assuming KE conserved — only momentum is guaranteed (M1 collisions often coalesce)."],
tips:["Coalesce = stick together: common v, one unknown — easiest Qs.","'Find the impulse on…' → Δp of THAT body only."],
oos:"<b>Beyond syllabus:</b> rocket equation: momentum conservation with CHANGING mass — M1's bigger sibling."}}
]}
]};
