/* Biology topical exam-style question bank — modelled on real WBI papers (current spec) */
var QBANK_BIOLOGY = {
U1:[
{id:"BIO-U1-01",topics:["U1T1"],ref:"WBI11 • June 2019 • Q1 style",title:"Food tests & sugars",marks:7,diff:1,time:"7 min",
q:"A student tests three solutions: glucose, sucrose, starch.\n(a) Describe the Benedict's test and give the result for EACH solution. (4)\n(b) Describe how to test for the non-reducing sugar, with the result for sucrose. (3)",
hint:"Direct Benedict's only catches reducing sugars. Hydrolyse the rest.",
ans:["(a) Add Benedict's, heat to ~80 °C in a water bath. Glucose: brick-red ppt (reducing). Sucrose: stays blue. Starch: stays blue.","(b) Boil sample with dilute HCl (hydrolysis), neutralise with NaHCO₃/NaOH, re-test with Benedict's → sucrose now gives brick-red (glucose + fructose released)."]},
{id:"BIO-U1-02",topics:["U1T1"],ref:"WBI11 • Jan 2020 • Q2 style",title:"Water & transport properties",marks:6,diff:2,time:"7 min",
q:"(a) Explain how TWO properties of water suit it for transporting substances in blood. (4)\n(b) Explain why large organisms need a transport system. (2)",
hint:"Solvent + high SHC + cohesion. SA:V falls with size.",
ans:["(a) Excellent solvent (polar) → carries ions, glucose, urea dissolved. High SHC → blood temperature stable despite heat transport. Cohesion/adhesion → continuous columns; incompressible → pressure transmission.","(b) Small SA:V → diffusion too slow over large distances; high metabolic demand needs fast bulk delivery/removal."]},
{id:"BIO-U1-03",topics:["U1T2"],ref:"WBI11 • Oct 2021 • Q3 style",title:"CVD risk & atheroma",marks:8,diff:2,time:"9 min",
q:"(a) Describe how an atheroma forms in a coronary artery. (4)\n(b) Explain how smoking increases the risk of cardiovascular disease. (4)",
hint:"Damage → LDL → plaque. Nicotine, CO, tar — three weapons.",
ans:["(a) Endothelium damaged (high BP, smoking) → LDL cholesterol accumulates underneath → white blood cells engulf it (foam cells) → fibrous plaque/cap forms → lumen narrows, wall stiffens.","(b) Nicotine: addictive, raises HR/BP (more damage). CO: binds Hb → less O₂ → heart works harder. Tar/chemicals damage endothelium directly. All accelerate atheroma + clot risk."]},
{id:"BIO-U1-04",topics:["U1T2"],ref:"WBI11 • June 2022 • Q4 style",title:"Cardiac cycle & valves",marks:7,diff:2,time:"8 min",
q:"(a) Describe the events of the cardiac cycle from atrial systole to the end of ventricular systole. (4)\n(b) Explain why the left ventricle wall is thicker than the right. (3)",
hint:"Pressure opens/closes valves. Left pumps to the whole body.",
ans:["(a) Atrial systole: atria contract, AV valves open, blood → ventricles. Ventricular systole: ventricles contract, pressure rises, AV valves shut (lub), semilunar valves open, blood → aorta/pulmonary artery.","(b) Left ventricle pumps blood around the WHOLE body (high resistance, long distance) → needs higher pressure → more muscle; right only pumps to nearby lungs (low pressure)."]},
{id:"BIO-U1-05",topics:["U1T3"],ref:"WBI11 • Jan 2023 • Q5 style",title:"Haemoglobin & Bohr effect",marks:9,diff:3,time:"11 min",
q:"(a) Explain the shape of the haemoglobin oxygen dissociation curve. (4)\n(b) Explain the advantage of the Bohr effect to actively respiring muscle. (3)\n(c) Suggest why myoglobin has a curve to the left of haemoglobin. (2)",
hint:"Cooperative binding → sigmoid. CO₂ shifts right. Myoglobin stores.",
ans:["(a) Sigmoid from cooperative binding: 1st O₂ hard to load (low affinity at low pO₂), each O₂ changes shape easing the next (steep middle), last sites saturate (plateau as all loaded).","(b) Active muscle makes CO₂ (→ H⁺, low pH) → curve shifts right → Hb affinity falls → MORE O₂ unloaded exactly where needed.","(c) Higher affinity: loads O₂ from Hb/myoglobin store and releases only at very low pO₂ — an O₂ reserve for muscle."]},
{id:"BIO-U1-06",topics:["U1T3"],ref:"WBI11 • June 2023 • Q6 style",title:"Tissue fluid & oedema",marks:7,diff:2,time:"8 min",
q:"(a) Explain how tissue fluid is formed at the arteriole end of a capillary. (4)\n(b) Explain why fluid is reabsorbed at the venule end, and what happens to fluid that is not reabsorbed. (3)",
hint:"Hydrostatic pressure out; osmosis + low pressure back; lymph drains excess.",
ans:["(a) High hydrostatic (blood) pressure forces small molecules (water, ions, glucose, O₂) through capillary pores; cells and plasma proteins too large to leave.","(b) Pressure fallen (friction); water potential lower in blood (proteins remain) → osmosis draws most fluid back. Excess (~10%) drains into lymph vessels → returned via lymphatic system. Blockage → oedema."]},
{id:"BIO-U1-07",topics:["U1T3"],ref:"WBI11 • Oct 2022 • Q7 style",title:"Transpiration & xerophytes",marks:8,diff:2,time:"9 min",
q:"A potometer measures water uptake of 4.0 cm³ per hour at 25 °C.\n(a) State THREE conditions for a fair comparison at 35 °C. (3)\n(b) Predict the result at 35 °C and explain it. (3)\n(c) Describe TWO xerophytic adaptations that reduce water loss. (2)",
hint:"Control light, humidity, air flow. Heat → evaporation. Xerophytes trap moist air.",
ans:["(a) Same light intensity, humidity, air movement, plant/shoot, equilibration time.","(b) Faster uptake: higher T → faster evaporation from mesophyll → steeper diffusion gradient → faster diffusion out of stomata → greater transpiration pull.","(c) Sunken stomata (trap moist air, ↓ gradient); thick waxy cuticle (↓ cuticular loss); rolled leaves/hairs (still air layer); fewer/smaller leaves."]},
{id:"BIO-U1-08",topics:["U1T4"],ref:"WBI11 • Jan 2024 • Q8 style",title:"Membranes & enzymes",marks:10,diff:3,time:"12 min",
q:"(a) Describe the fluid-mosaic model of the cell membrane. (4)\n(b) Explain why a rise in temperature increases the rate of diffusion across a membrane. (2)\n(c) An enzyme's rate falls sharply above 40 °C. Explain in terms of protein structure. (4)",
hint:"Bilayer + proteins + cholesterol. KE. Denaturation breaks tertiary bonds.",
ans:["(a) Phospholipid bilayer (heads out, tails in); intrinsic/extrinsic proteins (channels, carriers, receptors); cholesterol (fluidity/stability); glycoproteins/glycolipids (recognition); 'fluid' (molecules move) + 'mosaic' (protein pattern).","(b) Higher KE → molecules move faster → more cross per second down the gradient.","(c) Heat vibrates/breaks H-bonds/ionic bonds holding tertiary structure → active site shape lost (denatures) → substrate no longer fits → fewer/no ES complexes."]}
],
U2:[
{id:"BIO-U2-01",topics:["U2T1"],ref:"WBI12 • June 2019 • Q1 style",title:"Microscopy calculation & TEM",marks:7,diff:2,time:"8 min",
q:"A mitochondrion image measures 60 mm at ×30,000 magnification.\n(a) Calculate the real length in micrometres. (3)\n(b) Explain why a TEM rather than a light microscope is needed to see cristae. (2)\n(c) Give TWO limitations of TEM. (2)",
hint:"Real = image ÷ M. Resolution ~0.2 µm for light.",
ans:["(a) 60 mm/30000 = 0.002 mm = 2 µm.","(b) Cristae spacing < 0.2 µm (light resolution limit); TEM's electron beam (short λ) resolves ~0.1 nm.","(c) Dead specimens only (vacuum); no colour (stained B&W); expensive/thin sections/artefacts."]},
{id:"BIO-U2-02",topics:["U2T2"],ref:"WBI12 • Jan 2020 • Q2 style",title:"Mitosis stages & mitotic index",marks:8,diff:2,time:"9 min",
q:"(a) Describe what happens to chromosomes in prophase, metaphase and anaphase of mitosis. (3)\n(b) A root-tip squash shows 200 cells, 24 in mitosis. Calculate the mitotic index. (2)\n(c) Explain why root tips are used and state TWO variables to control when comparing two treatments. (3)",
hint:"Condense, line up, separate. MI = dividing ÷ total.",
ans:["(a) Prophase: chromatin condenses (visible chromosomes), nuclear envelope breaks down, spindle forms. Metaphase: chromosomes line up on equator (centromeres to spindle). Anaphase: sister chromatids pulled to opposite poles.","(b) MI = 24/200 = 0.12 (12%).","(c) Meristem — rapid division. Control: same species/age, same distance from tip, same stain/time, same temperature, count same field area."]},
{id:"BIO-U2-03",topics:["U2T2"],ref:"WBI12 • Oct 2021 • Q3 style",title:"Meiosis & variation",marks:7,diff:2,time:"8 min",
q:"(a) Explain how meiosis produces genetically different gametes. (4)\n(b) Explain why fertilisation restores the diploid number and why this matters. (3)",
hint:"Crossing over + independent assortment + random fusion. Halve then restore.",
ans:["(a) Crossing over (prophase I): alleles swap between homologues → new combinations. Independent assortment (metaphase I): maternal/paternal homologues orient randomly → 2ⁿ gamete types. Random fertilisation multiplies variation.","(b) Two haploid nuclei fuse → diploid zygote; keeps chromosome number constant generation to generation (prevents doubling); restores homologous pairs."]},
{id:"BIO-U2-04",topics:["U2T3"],ref:"WBI12 • June 2022 • Q4 style",title:"Stem cells & ethics",marks:8,diff:2,time:"9 min",
q:"(a) Explain what is meant by pluripotent, and give an example. (3)\n(b) Describe how stem cells could treat Type 1 diabetes, and give ONE risk. (3)\n(c) Give one ethical argument for and one against embryonic stem-cell research. (2)",
hint:"All body cells but not placenta. Replace β cells. Cures vs embryo status.",
ans:["(a) Can differentiate into (almost) all body cell types (not placenta); e.g. inner-mass embryonic stem cells / iPS cells.","(b) Differentiate into insulin-secreting β cells → transplant → restore glucose control. Risk: immune rejection, tumour formation, wrong differentiation.","(c) For: relieves suffering/cures disease (greater good). Against: embryo destroyed (right to life); slippery slope (designer uses)."]},
{id:"BIO-U2-05",topics:["U2T3"],ref:"WBI12 • Jan 2023 • Q5 style",title:"Epigenetics & twins",marks:6,diff:2,time:"7 min",
q:"Identical twins develop different risks of diabetes despite identical DNA.\n(a) Explain this using the concept of epigenetics. (4)\n(b) State what is meant by 'phenotype = genotype + environment'. (2)",
hint:"Methylation switches genes. Same genes, different expression.",
ans:["(a) Different lifestyles (diet, stress) add/remove methyl groups/histone marks → genes switched on/off differently → different proteins → different disease risk, without changing DNA sequence. Changes can be heritable.","(b) Observed traits result from genes AND environmental influences on expression; identical genotypes can give different phenotypes in different environments."]},
{id:"BIO-U2-06",topics:["U2T4"],ref:"WBI12 • June 2023 • Q6 style",title:"Simpson's diversity index",marks:7,diff:2,time:"8 min",
q:"Site A: 30 grass, 20 daisies, 10 clover. Site B: 50 grass, 5 daisies, 5 clover.\n(a) Calculate Simpson's index for both sites. (4)\n(b) State which is more diverse and explain what the index accounts for. (3)",
hint:"d = N(N−1)/Σn(n−1). Evenness matters.",
ans:["(a) A: N=60; Σ = 30×29+20×19+10×9 = 870+380+90 = 1340; d = 3540/1340 = 2.64. B: N=60; Σ = 2450+20+20 = 2490; d = 3540/2490 = 1.42.","(b) A more diverse. Index accounts for richness AND evenness — B is dominated by grass so less diverse despite equal N."]},
{id:"BIO-U2-07",topics:["U2T4"],ref:"WBI12 • Oct 2022 • Q7 style",title:"Antibiotic resistance evolution",marks:7,diff:2,time:"8 min",
q:"Explain how the overuse of antibiotics leads to resistant bacterial populations. (7)",
hint:"Variation exists FIRST. Antibiotic selects. Never 'mutate to resist'.",
ans:["Genetic variation exists (random mutations; some bacteria carry resistance alleles e.g. β-lactamase).","Antibiotic kills susceptible bacteria (selection pressure) — resistant survive.","Survivors reproduce (binary fission), passing resistance alleles on (vertical + plasmid transfer).","Allele frequency rises → population resistant (directional selection).","Overuse/ unfinished courses strengthen selection; finish courses + stewardship slow it."]}
],
U3:[
{id:"BIO-U3-01",topics:["U3T1"],ref:"WBI13 • June 2019 • Q1 style",title:"Beetroot colorimetry",marks:7,diff:2,time:"8 min",
q:"Beetroot discs are placed in water baths at 20–70 °C; pigment release is measured by colorimeter.\n(a) Describe how to use the colorimeter to get valid results. (3)\n(b) Sketch the expected graph of absorbance vs temperature and explain its shape. (4)",
hint:"Blank, same filter/cuvettes. Membranes break down with heat.",
ans:["(a) Calibrate with distilled-water blank (zero absorbance); same wavelength (green filter); same cuvettes, wiped; equal volumes; repeat and average.","(b) Low flat absorbance then steep rise: heat denatures membrane proteins + increases fluidity/kinetic energy → membranes leaky/ruptured → betalain leaks out; denaturation accelerates above ~40 °C."]},
{id:"BIO-U3-02",topics:["U3T1"],ref:"WBI13 • Jan 2022 • Q2 style",title:"Chi-squared & t-test choice",marks:6,diff:2,time:"7 min",
q:"(a) A genetic cross expects a 3:1 ratio. Observed: 90 dominant, 22 recessive. State the test, degrees of freedom and what p < 0.05 would mean. (3)\n(b) A student compares mean leaf lengths in sun vs shade. State the test and the null hypothesis. (3)",
hint:"Ratios → chi². Means → t-test.",
ans:["(a) Chi-squared; df = 2−1 = 1. p<0.05: significant difference from 3:1 → reject null (ratio does not fit).","(Quick check: expected 84/28; χ² = 36/84+36/28 = 1.71 < 3.84 → not significant — fits 3:1.)","(b) t-test. H₀: no difference in mean leaf length between sun and shade."]},
{id:"BIO-U3-03",topics:["U3T1"],ref:"WBI13 • Oct 2023 • Q3 style",title:"Quadrats & validity",marks:6,diff:2,time:"7 min",
q:"A student estimates daisy coverage using 5 quadrats placed 'where daisies look typical'.\n(a) Give THREE criticisms and an improvement for each. (3)\n(b) Explain the difference between random and systematic sampling and when each is used. (3)",
hint:"Biased, small n, no repeats. Random for uniformity, transects for gradients.",
ans:["(a) Biased placement → random coordinates (random-number grid). Only 5 → more quadrats (≥10–20). No repeats/mean → repeat, average, calculate SD. Also: edge effect rule needed.","(b) Random: every point equally likely — representative mean for uniform areas. Systematic (transects/belts): regular intervals — shows CHANGE across gradients/zones."]}
],
U4:[
{id:"BIO-U4-01",topics:["U4T1"],ref:"WBI14 • June 2019 • Q1 style",title:"Photosynthesis limiting factors",marks:8,diff:2,time:"9 min",
q:"A student varies lamp distance and measures oxygen bubbles from pondweed.\n(a) Sketch the expected rate–vs–light-intensity curve and explain its shape. (4)\n(b) State THREE variables to control. (3)\n(c) Give one limitation of counting bubbles. (1)",
hint:"Light limits, then CO₂/T. Same CO₂, T, plant.",
ans:["(a) Rate rises steeply then plateaus: at low light, light limits (more photons → more photolysis/ATP); at high light, CO₂ or temperature limits (Calvin cycle/enzymes maxed).","(b) Temperature (water bath), CO₂ (NaHCO₃ concentration), same shoot/leaf area, pH, time of day.","(c) Bubbles vary in size; dissolving O₂; counting errors → use gas syringe/volume instead."]},
{id:"BIO-U4-02",topics:["U4T1"],ref:"WBI14 • Jan 2020 • Q2 style",title:"Nitrogen cycle & eutrophication",marks:9,diff:3,time:"11 min",
q:"(a) Describe the roles of nitrogen-fixing bacteria, nitrifying bacteria and denitrifying bacteria. (3)\n(b) Explain how fertiliser runoff causes fish deaths (eutrophication). (6)",
hint:"Fix → nitrify → denitrify. Fertilisers feed algae, bacteria eat oxygen.",
ans:["(a) Fixing (Rhizobium/Azotobacter): N₂ → NH₃/ammonium. Nitrifying (Nitrosomonas → nitrite, Nitrobacter → nitrate): NH₃ → NO₃⁻ (plant-usable). Denitrifying (anaerobic): NO₃⁻ → N₂.","(b) Nitrates leach → algal bloom → blocks light → submerged plants die → saprobionts decompose (aerobic respiration) → O₂ depleted → fish suffocate. Toxins from some algae add harm."]},
{id:"BIO-U4-03",topics:["U4T1"],ref:"WBI14 • Oct 2021 • Q3 style",title:"Energy transfer 10%",marks:6,diff:2,time:"7 min",
q:"A food chain: wheat (9000 kJ m⁻² yr⁻¹ net) → mice → owls. Mice gain 720 kJ; owls gain 65 kJ.\n(a) Calculate transfer efficiencies. (3)\n(b) Explain why efficiency is low. (3)",
hint:"720/9000, 65/720. Respiration, excretion, uneaten.",
ans:["(a) Wheat→mice: 720/9000 = 8%. Mice→owls: 65/720 = 9.0%.","(b) Energy lost: respiration (movement, heat), excretion (urine), egestion (faeces), uneaten parts (bones, roots), death/decomposition before eating."]},
{id:"BIO-U4-04",topics:["U4T2"],ref:"WBI14 • June 2022 • Q4 style",title:"Bacterial growth & aseptic technique",marks:9,diff:2,time:"10 min",
q:"(a) Sketch and label the bacterial growth curve (log count vs time), explaining the stationary phase. (4)\n(b) Describe THREE aseptic techniques for inoculating an agar plate. (3)\n(c) Explain why school plates are incubated below 30 °C. (2)",
hint:"Lag, log, stationary, death. Flame, updraft, sterile. Pathogens like 37 °C.",
ans:["(a) Lag (adapting) → log (exponential) → stationary (birth rate = death rate: nutrients/oxygen run out, waste accumulates) → death/decline.","(b) Flame loop before/after; flame flask neck; work near Bunsen updraft; lift lid minimally; disinfect bench; sterile media.","(c) 37 °C favours human pathogens; lower T grows harmless microbes while reducing pathogen/disease risk."]},
{id:"BIO-U4-05",topics:["U4T2"],ref:"WBI14 • Jan 2023 • Q5 style",title:"Antibiotic zones & resistance",marks:7,diff:2,time:"8 min",
q:"Three antibiotic discs (A, B, C) on a bacterial lawn give zones of diameter 22, 14 and 0 mm.\n(a) State which is most effective and explain how zones form. (3)\n(b) Explain why antibiotic C shows no zone. (2)\n(c) State TWO controls needed for a valid comparison. (2)",
hint:"Bigger zone = more effective. C: resistant or wrong target.",
ans:["(a) A (largest zone). Antibiotic diffuses out; where concentration ≥ MIC, bacteria killed/inhibited → clear zone.","(b) Bacteria resistant (e.g. enzyme/plasmid) or C targets a structure this species lacks; or C can't diffuse.","(c) Same bacterial lawn density/volume; same agar depth; same incubation T/time; control disc (solvent only)."]},
{id:"BIO-U4-06",topics:["U4T3"],ref:"WBI14 • June 2023 • Q6 style",title:"Primary vs secondary response",marks:8,diff:2,time:"9 min",
q:"(a) Sketch antibody concentration after two exposures to the same antigen, labelling primary and secondary responses. (3)\n(b) Explain the difference in terms of memory cells. (3)\n(c) Explain how vaccination uses this to protect against disease. (2)",
hint:"Slow + small, then fast + huge. Memory B/T cells persist.",
ans:["(a) 1st exposure: lag ~days, low peak, short-lived. 2nd: near-instant, much higher, longer-lasting.","(b) Primary: naive B/T cells selected slowly, few memory cells made. Secondary: abundant memory cells activate immediately → rapid mass plasma-cell production.","(c) Vaccine's harmless antigen triggers primary + memory safely; real pathogen later meets a fast secondary response → destroyed before disease."]},
{id:"BIO-U4-07",topics:["U4T3"],ref:"WBI14 • Oct 2022 • Q7 style",title:"Phagocytosis & antibodies",marks:8,diff:2,time:"9 min",
q:"(a) Describe the stages of phagocytosis of a bacterium. (4)\n(b) Describe TWO ways antibodies help destroy pathogens. (4)",
hint:"Engulf → phagosome → lysosome → digest. Agglutination, opsonisation, neutralisation.",
ans:["(a) Phagocyte recognises foreign antigens (receptors) → pseudopodia engulf → phagosome → fuses with lysosome → hydrolytic enzymes digest → harmless products absorbed/egested; antigens presented.","(b) Agglutination: cross-link pathogens → clumps phagocytosed easily. Opsonisation: coating marks pathogens for phagocytes. Neutralisation: block toxins/attachment sites. Complement activation lyses cells. (Any two, explained.)"]},
{id:"BIO-U4-08",topics:["U4T2"],ref:"WBI14 • Jan 2024 • Q8 style",title:"DNA profiling forensics",marks:6,diff:2,time:"7 min",
q:"(a) Describe the stages of DNA profiling from a blood sample. (4)\n(b) Explain why profiling uses non-coding repeated regions (VNTRs). (2)",
hint:"Extract, cut, amplify, separate, compare. Repeats vary between people.",
ans:["(a) Extract DNA (lyse cells) → cut with restriction enzymes → amplify by PCR → separate fragments by gel electrophoresis → visualise bands → compare pattern with suspects (match = same lengths).","(b) VNTR lengths vary hugely between individuals (hypervariable) → unique-ish barcodes; non-coding so free to vary without harming function."]}
],
U5:[
{id:"BIO-U5-01",topics:["U5T1"],ref:"WBI15 • June 2019 • Q1 style",title:"Mitochondria & respiration stages",marks:9,diff:3,time:"11 min",
q:"(a) State where glycolysis, the Krebs cycle and oxidative phosphorylation occur. (3)\n(b) Explain how the structure of the mitochondrion suits oxidative phosphorylation. (3)\n(c) Explain why cyanide (which blocks the electron transport chain) is rapidly fatal. (3)",
hint:"Cytoplasm, matrix, cristae. Surface area + gradient. No ETC → no ATP.",
ans:["(a) Glycolysis: cytoplasm. Krebs: mitochondrial matrix. Oxidative phosphorylation: inner membrane/cristae.","(b) Folded cristae: huge SA for ETC carriers + ATP synthase. Small intermembrane space: steep H⁺ gradient. Matrix holds Krebs enzymes + substrates.","(c) E⁻ can't pass → no H⁺ pumping → no gradient → ATP synthase stops → cells (brain/heart) run out of ATP in minutes despite oxygen present."]},
{id:"BIO-U5-02",topics:["U5T1"],ref:"WBI15 • Jan 2020 • Q2 style",title:"Muscle contraction & RQ",marks:8,diff:2,time:"9 min",
q:"(a) Describe the sliding-filament model of muscle contraction. (5)\n(b) An athlete's RQ is 0.85 during a marathon. Explain what this shows about the respiratory substrate. (3)",
hint:"Ca²⁺, cross-bridges, ATP power stroke. RQ 1.0 carbs, 0.7 fats.",
ans:["(a) Impulse → Ca²⁺ from sarcoplasmic reticulum → binds troponin → tropomyosin moves, exposing actin sites → myosin heads bind (cross-bridges) → power stroke (ATP) pulls actin inward → filaments slide (H/I shorten, A same) → Ca²⁺ pumped back, muscle relaxes.","(b) Between 0.7 and 1.0 → MIXTURE of fats and carbohydrates oxidised (endurance: fats increasingly used as glycogen depletes)."]},
{id:"BIO-U5-03",topics:["U5T2"],ref:"WBI15 • Oct 2021 • Q3 style",title:"Kidney: filtration to ADH",marks:10,diff:3,time:"12 min",
q:"(a) Explain how the glomerulus and Bowman's capsule filter the blood. (4)\n(b) Explain how ADH controls water reabsorption when dehydrated. (4)\n(c) State what happens to urine concentration if ADH secretion fails. (2)",
hint:"High pressure, small molecules out. ADH → permeable ducts.",
ans:["(a) Afferent wider than efferent → high pressure; small molecules (water, ions, glucose, urea) forced through basement membrane into capsule; cells/platelets/plasma proteins stay (too big).","(b) Low blood water potential → osmoreceptors (hypothalamus) → posterior pituitary releases more ADH → collecting-duct cells insert aquaporins → more permeable → more water reabsorbed by osmosis → small concentrated urine.","(c) Diabetes insipidus: large volumes of dilute urine (ducts stay impermeable)."]},
{id:"BIO-U5-04",topics:["U5T2"],ref:"WBI15 • June 2022 • Q4 style",title:"Blood glucose & diabetes",marks:8,diff:2,time:"9 min",
q:"(a) Explain how insulin and glucagon control blood glucose after a meal and during exercise. (5)\n(b) Distinguish Type 1 and Type 2 diabetes (cause + treatment). (3)",
hint:"β/insulin lowers; α/glucagon raises. Autoimmune vs resistance.",
ans:["(a) After meal: high glucose → β cells release insulin → liver/muscles convert glucose to glycogen (glycogenesis), cells ↑ uptake/respiration → falls. Exercise: low glucose → α cells release glucagon → glycogenolysis/gluconeogenesis in liver → rises. Negative feedback both ways.","(b) Type 1: autoimmune β destruction → no insulin → insulin injections. Type 2: insulin resistance/reduced secretion (lifestyle-linked) → diet/exercise/weight loss + drugs (e.g. metformin/insulin if severe)."]},
{id:"BIO-U5-05",topics:["U5T3"],ref:"WBI15 • Jan 2023 • Q5 style",title:"Action potential stages",marks:9,diff:3,time:"11 min",
q:"(a) Explain how the resting potential of −70 mV is maintained. (3)\n(b) Describe the events of an action potential when a stimulus arrives. (4)\n(c) Explain why action potentials are unidirectional. (2)",
hint:"Na⁺/K⁺ pump + K⁺ leak. Na⁺ in, K⁺ out. Refractory period.",
ans:["(a) Na⁺/K⁺ pump (3 Na⁺ out, 2 K⁺ in, ATP) + K⁺ leak channels (K⁺ diffuses out) → inside negative; large anions trapped inside.","(b) Stimulus opens Na⁺ voltage-gated channels (if threshold) → Na⁺ floods in → depolarisation to +40 mV → Na⁺ channels close/inactivate, K⁺ channels open → K⁺ out → repolarisation → brief hyperpolarisation → pump restores resting.","(c) Behind the impulse the membrane is REFRACTORY (Na⁺ channels inactivated) → can't refire → impulse only travels forward."]},
{id:"BIO-U5-06",topics:["U5T3"],ref:"WBI15 • June 2023 • Q6 style",title:"Synapses & drugs",marks:7,diff:2,time:"8 min",
q:"(a) Describe how an impulse crosses a cholinergic synapse. (4)\n(b) Organophosphate insecticides block acetylcholinesterase. Explain why this kills insects. (3)",
hint:"Ca²⁺ → vesicles → ACh → receptors → hydrolysed. No breakdown = spasm.",
ans:["(a) AP arrives → Ca²⁺ channels open → vesicles fuse → ACh released by exocytosis → diffuses → binds receptors on post-synaptic membrane → Na⁺ in → new AP (if threshold) → ACh broken down by cholinesterase (choline recycled).","(b) ACh not broken down → accumulates → postsynaptic membrane continually stimulated → constant muscle contraction/spasm, paralysis → death (respiratory failure)."]},
{id:"BIO-U5-07",topics:["U5T4"],ref:"WBI15 • Oct 2022 • Q7 style",title:"Genetic engineering: insulin",marks:9,diff:3,time:"11 min",
q:"Describe the stages of producing human insulin using genetically modified bacteria. (9)",
hint:"Cut, join, insert, select, culture — in order.",
ans:["Isolate insulin gene (mRNA → cDNA using reverse transcriptase, or synthetic).","Cut plasmid vector + gene with the SAME restriction enzyme → complementary sticky ends.","Join with DNA ligase → recombinant plasmid.","Insert into bacteria (heat shock/Ca²⁺/electroporation).","Select transformants via marker genes (antibiotic resistance).","Culture in fermenters (sterile, optimal T/pH/nutrients) → bacteria express insulin.","Extract + purify insulin (downstream processing, chromatography)."]},
{id:"BIO-U5-08",topics:["U5T4"],ref:"WBI15 • Jan 2024 • Q8 style",title:"PCR & electrophoresis",marks:8,diff:2,time:"9 min",
q:"(a) Describe the three stages of one PCR cycle, with temperatures. (3)\n(b) Starting with 4 DNA molecules, how many after 10 cycles? (2)\n(c) Explain how gel electrophoresis separates the amplified fragments. (3)",
hint:"95 melt, 55 anneal, 72 extend. Doubling. Small = fast.",
ans:["(a) Denaturation ~95 °C (H-bonds break, strands separate); annealing ~55 °C (primers bind); extension ~72 °C (Taq polymerase adds nucleotides).","(b) 4 × 2¹⁰ = 4096.","(c) DNA (negative) loaded in agarose wells → electric field pulls toward +; small fragments navigate pores faster → separate by SIZE; compare bands to ladder/markers."]}
],
U6:[
{id:"BIO-U6-01",topics:["U6T1"],ref:"WBI16 • June 2019 • Q1 style",title:"Respirometer plan",marks:8,diff:3,time:"10 min",
q:"Plan an investigation into the effect of temperature on the respiration rate of germinating seeds using a respirometer. (8)",
hint:"Hypothesis → variables → method → analysis → safety.",
ans:["Hypothesis: higher T increases O₂ uptake rate (up to an optimum).","IV: T (e.g. 10–40 °C water baths, ≥5 values); DV: O₂ uptake (mm³ min⁻¹ g⁻¹); controls: seed mass/species/age, KOH volume, time, apparatus.","Method: weigh seeds, add KOH (CO₂ absorbent), equilibrate 5 min, record manometer movement over 5 min; control tube with glass beads; ×3 repeats.","Analysis: rate vs T graph; t-test between extremes; conclusion vs hypothesis.","Safety/ethics: water + electrics care; handle seeds gently; low risk. Validity: same germination stage, acclimatise, calibrate capillary."]},
{id:"BIO-U6-02",topics:["U6T1"],ref:"WBI16 • Jan 2023 • Q2 style",title:"Spearman correlation",marks:5,diff:2,time:"6 min",
q:"A student tests correlation between lichen coverage and distance from a road. r_s = −0.82, n = 12, critical (5%) = 0.587.\n(a) State the null hypothesis. (1)\n(b) Give the conclusion with reasoning. (2)\n(c) State two limitations of concluding pollution causes the pattern. (2)",
hint:"|r_s| > critical → significant. Correlation ≠ causation.",
ans:["(a) No correlation between lichen coverage and distance from road.","(b) |−0.82| > 0.587 → significant negative correlation → reject H₀ (p < 0.05): coverage falls nearer the road.","(c) Correlation ≠ causation: other factors (salt spray, wind, light, trampling); small n; confounding variables uncontrolled."]},
{id:"BIO-U6-03",topics:["U6T1"],ref:"WBI16 • Oct 2024 • Q3 style",title:"Evaluate: enzyme initial rates",marks:5,diff:2,time:"6 min",
q:"Initial rates of amylase are measured by timing iodine colour loss at different starch concentrations.\n(a) Explain why initial rate (not time to completion) is used. (2)\n(b) Give two sources of error and an improvement for each. (3)",
hint:"Substrate depletes, product inhibits. End-point subjective.",
ans:["(a) At t=0, [S] known/maximal, no product inhibition or reverse reaction → rate reflects [S] only; later, falling [S] + product slow it.","(b) Subjective colour judgement → colorimeter (absorbance vs time, tangent at 0). Temperature drift → water bath. pH change → buffer. Timing error → repeats/average."]}
]};
