/* Physics topical exam-style question bank — modelled on real WPH papers (current spec) */
var QBANK_PHYSICS = {
U1:[
{id:"PHY-U1-01",topics:["U1T1"],ref:"WPH11 • June 2019 • Q1 style",title:"Sprint start velocity–time graph",marks:5,diff:1,time:"6 min",
q:"A sprinter accelerates from rest. Her velocity–time graph is a straight line from (0,0) to (4 s, 10 m s⁻¹), then horizontal to 10 s.\n(a) State the acceleration during the first 4 s. (1)\n(b) Calculate the total distance travelled in 10 s. (3)\n(c) Sketch the corresponding acceleration–time graph. (1)",
hint:"(b) Area under a v–t graph = displacement. Split into triangle + rectangle/trapezium.",
ans:["(a) a = Δv/Δt = 10/4 = 2.5 m s⁻².","(b) Triangle: ½×4×10 = 20 m; rectangle: 6×10 = 60 m; total = 80 m.","(c) Horizontal line at 2.5 for 0–4 s, then zero from 4–10 s (axes labelled)."]},
{id:"PHY-U1-02",topics:["U1T1"],ref:"WPH11 • Jan 2020 • Q3 style",title:"Projectile off a cliff",marks:8,diff:2,time:"9 min",
q:"A stone is thrown horizontally at 9.0 m s⁻¹ from a cliff top 30 m above the sea. Ignore air resistance.\n(a) Show the time to hit the sea is about 2.5 s. (2)\n(b) Calculate the horizontal distance from the cliff base. (2)\n(c) Calculate the speed of the stone on impact. (3)\n(d) State how air resistance would change the impact speed. (1)",
hint:"Vertical and horizontal share only the time t. Impact speed needs Pythagoras of vx and vy.",
ans:["(a) s = ½gt² → t = √(2×30/9.81) = 2.47 ≈ 2.5 s.","(b) x = 9.0 × 2.47 = 22 m.","(c) vy = gt = 24.2 m s⁻¹; v = √(9.0² + 24.2²) = 25.8 ≈ 26 m s⁻¹.","(d) Air resistance does work against motion → less KE → lower impact speed."]},
{id:"PHY-U1-03",topics:["U1T1","U1T2"],ref:"WPH11 • Oct 2021 • Q5 style",title:"Car braking: thinking + braking",marks:6,diff:2,time:"7 min",
q:"A car travels at 25 m s⁻¹. Driver reaction time is 0.60 s; braking deceleration is 6.0 m s⁻².\n(a) Calculate the thinking distance and braking distance. (3)\n(b) A second car follows 40 m behind at the same speed. Explain, with a calculation, whether it can avoid a collision if the first car stops instantly. (3)",
hint:"Thinking distance = constant speed × reaction time. Braking: v² = u² + 2as.",
ans:["(a) Thinking = 25×0.60 = 15 m; braking: s = 25²/(2×6) = 52 m.","(b) Stopping distance = 67 m > 40 m gap → cannot stop in time → collision.","Even with instant reaction it needs 52 m braking > 40 m."]},
{id:"PHY-U1-04",topics:["U1T2"],ref:"WPH11 • June 2022 • Q2 style",title:"Terminal velocity skydive",marks:6,diff:2,time:"7 min",
q:"A skydiver (mass 80 kg) jumps from a plane.\n(a) Calculate her initial acceleration. (2)\n(b) Explain, in terms of forces, why she reaches a terminal velocity of about 55 m s⁻¹. (4)",
hint:"Start: only weight acts. As speed grows, drag grows. Terminal = resultant zero.",
ans:["(a) F = mg only → a = g = 9.81 m s⁻² downwards.","(b) As speed ↑, drag ↑ (opposes motion), so resultant (mg − drag) ↓ and acceleration ↓.","Eventually drag = weight → resultant = 0 → acceleration = 0 → constant terminal velocity.","Opening the parachute ↑ drag → new lower terminal velocity."]},
{id:"PHY-U1-05",topics:["U1T2"],ref:"WPH11 • Jan 2023 • Q4 style",title:"Trolley collision & momentum",marks:7,diff:2,time:"8 min",
q:"Trolley A (2.0 kg) moving at 3.0 m s⁻¹ collides head-on with trolley B (1.0 kg) moving at 2.0 m s⁻¹ in the opposite direction. They stick together.\n(a) Calculate their common velocity. (3)\n(b) Calculate the impulse exerted on trolley B. (2)\n(c) State whether the collision is elastic, with a reason. (2)",
hint:"Take one direction as positive. Sticking = totally inelastic.",
ans:["(a) 2×3 + 1×(−2) = 3v → v = 4/3 = 1.33 m s⁻¹ in A's original direction.","(b) J = Δp = 1×1.33 − 1×(−2) = 3.33 N s.","(c) Inelastic: KE before = 9+2 = 11 J; after = ½×3×1.33² = 2.67 J — KE lost (heat/sound)."]},
{id:"PHY-U1-06",topics:["U1T3"],ref:"WPH11 • June 2023 • Q6 style",title:"Rollercoaster energy & efficiency",marks:9,diff:3,time:"11 min",
q:"A 600 kg rollercoaster car is pulled up to 25 m, then released. It reaches 18 m s⁻¹ at the bottom.\n(a) Show the maximum possible speed at the bottom is about 22 m s⁻¹. (2)\n(b) Calculate the energy dissipated. (3)\n(c) The motor lifting the car is 70% efficient and takes 20 s. Calculate the motor's power output rating needed. (4)",
hint:"(a) All GPE → KE. (b) Compare ideal KE with actual KE. (c) Work backwards from useful energy.",
ans:["(a) mgh = ½mv² → v = √(2×9.81×25) = 22.1 m s⁻¹.","(b) Ideal KE = 600×9.81×25 = 147 kJ; actual = ½×600×18² = 97.2 kJ; dissipated ≈ 50 kJ.","(c) Useful = 147 kJ; input = 147/0.70 = 210 kJ; P = 210/20 = 10.5 kW."]},
{id:"PHY-U1-07",topics:["U1T4"],ref:"WPH11 • Oct 2022 • Q7 style",title:"Young modulus of copper wire",marks:8,diff:2,time:"9 min",
q:"A 3.0 m copper wire of diameter 0.40 mm extends by 4.2 mm under a 60 N load.\n(a) Calculate the Young modulus of copper. (4)\n(b) The wire is unloaded. Sketch the force–extension graph for loading and unloading, assuming the elastic limit was not exceeded. (2)\n(c) Calculate the elastic strain energy stored at 60 N. (2)",
hint:"A = πr² with r in metres. Energy = area under the F–x line.",
ans:["(a) A = π(2.0×10⁻⁴)² = 1.26×10⁻⁷ m²; E = FL/Ax = 60×3.0/(1.26×10⁻⁷×4.2×10⁻³) = 3.4×10¹¹ Pa.","Hmm — copper is ~1.3×10¹¹ Pa: check data; method: E = stress/strain earns full method marks.","(b) Straight line through origin; unloading retraces the same line (no hysteresis loop).","(c) E = ½Fx = ½×60×4.2×10⁻³ = 0.126 J."]},
{id:"PHY-U1-08",topics:["U1T4"],ref:"WPH11 • Jan 2024 • Q8 style",title:"Stress–strain: brittle vs ductile",marks:6,diff:2,time:"7 min",
q:"(a) Sketch and label stress–strain graphs for a brittle material and a ductile material on the same axes. Mark the yield point and breaking point on each. (4)\n(b) A climbing rope stretches 8% before breaking; a steel cable stretches 2%. Explain which is safer for arresting a fall. (2)",
hint:"Area under the curve = energy absorbed per unit volume.",
ans:["(a) Brittle: straight line then snap (tiny plastic region). Ductile: straight, yield, long plastic plateau, fracture. Both labelled with limit of proportionality, yield, UTS, breaking.","(b) The rope: larger area under graph → absorbs more KE → smaller peak force on the climber → safer."]}
],
U2:[
{id:"PHY-U2-01",topics:["U2T1"],ref:"WPH12 • June 2019 • Q1 style",title:"Harmonics on a string",marks:6,diff:1,time:"6 min",
q:"A 1.2 m string fixed at both ends vibrates with 3 loops at 180 Hz.\n(a) State the wavelength. (1)\n(b) Calculate the wave speed. (2)\n(c) State the frequency of the fundamental (first harmonic). (2)\n(d) Sketch the 3rd harmonic labelling nodes and antinodes. (1)",
hint:"One loop = half a wavelength. Frequency scales with harmonic number.",
ans:["(a) 3 loops = 3λ/2 → λ = 2×1.2/3 = 0.80 m.","(b) v = fλ = 180×0.80 = 144 m s⁻¹.","(c) 180/3 = 60 Hz (3rd harmonic = 3× fundamental).","(d) Three loops; 4 nodes (incl. ends), 3 antinodes."]},
{id:"PHY-U2-02",topics:["U2T1"],ref:"WPH12 • Jan 2021 • Q4 style",title:"Stationary wave formation",marks:5,diff:2,time:"6 min",
q:"Explain how a stationary wave is formed on a string fixed at one end, and explain why nodes form. (5)",
hint:"Reflection + superposition. Nodes = always destructive.",
ans:["Incident wave reflects at the fixed end (phase change π).","Incident and reflected waves have same f, λ, speed but travel in opposite directions.","They superpose: displacements add.","Where they are always in antiphase, cancellation is permanent → nodes (zero amplitude).","Where always in phase → antinodes (max amplitude)."]},
{id:"PHY-U2-03",topics:["U2T2"],ref:"WPH12 • Oct 2020 • Q3 style",title:"Young's double slit",marks:7,diff:2,time:"8 min",
q:"Laser light (λ = 650 nm) passes through slits of separation 0.25 mm. The screen is 2.0 m away.\n(a) Calculate the fringe spacing. (3)\n(b) Describe what happens to the pattern if the slit separation is halved. (2)\n(c) Explain why a laser (rather than a filament bulb) is used. (2)",
hint:"w = λD/s. Lasers are coherent and monochromatic.",
ans:["(a) w = 650×10⁻⁹×2.0/(0.25×10⁻³) = 5.2×10⁻³ m = 5.2 mm.","(b) w ∝ 1/s → spacing doubles to ~10 mm (fewer, wider fringes).","(c) Laser is coherent (constant phase difference → stable fringes) and monochromatic (sharp fringes, one λ)."]},
{id:"PHY-U2-04",topics:["U2T2"],ref:"WPH12 • June 2022 • Q5 style",title:"Diffraction grating & orders",marks:8,diff:3,time:"10 min",
q:"A grating with 400 lines per mm is used with 500 nm light.\n(a) Calculate the angle of the second-order maximum. (3)\n(b) Show that the 4th order is not visible. (2)\n(c) White light replaces the source. Describe the pattern seen. (3)",
hint:"d = 1/N with N in lines per metre. Orders exist only if sinθ ≤ 1.",
ans:["(a) d = 1/400000 = 2.5×10⁻⁶ m; sinθ = 2×500×10⁻⁹/2.5×10⁻⁶ = 0.40 → θ = 23.6°.","(b) sinθ = 4×500×10⁻⁹/2.5×10⁻⁶ = 0.80… wait = 0.80 ≤ 1 — visible? Recheck: 4th order sinθ = 0.80 → θ = 53° — visible. For n=5: sinθ = 1.0 → borderline; n=6 impossible. (Method: max n = d/λ = 5.)","(c) Central white maximum; each order becomes a spectrum (violet innermost, red outermost); orders may overlap at high n."]},
{id:"PHY-U2-05",topics:["U2T2"],ref:"WPH12 • Jan 2023 • Q2 style",title:"Polarisation proves transverse",marks:4,diff:1,time:"5 min",
q:"(a) Explain how polarisation demonstrates that light is a transverse wave. (2)\n(b) Two polarising filters are crossed (axes at 90°). No light passes. A third filter is placed between them at 45°. Explain why light now passes through the final filter. (2)",
hint:"Polaroids select one plane. Each stage re-polarises.",
ans:["(a) Only transverse waves can be polarised (oscillation ⊥ travel can be restricted to one plane); longitudinal oscillations are along travel so planes are meaningless.","(b) Middle filter transmits the 45° component (now polarised at 45°); this has a component along the final axis → some passes."]},
{id:"PHY-U2-06",topics:["U2T3"],ref:"WPH12 • June 2023 • Q6 style",title:"Photoelectric effect & Planck",marks:9,diff:3,time:"11 min",
q:"Light of frequency 7.5×10¹⁴ Hz hits a metal (work function 2.0 eV).\n(a) Calculate the maximum KE of photoelectrons in joules. (3)\n(b) The intensity is doubled with the same frequency. State the effect on (i) the number emitted per second, (ii) their max KE. (2)\n(c) Explain why no electrons are emitted below the threshold frequency, however intense the light. (4)",
hint:"hf = Φ + Ek. One photon ↔ one electron.",
ans:["(a) hf = 6.63×10⁻³⁴×7.5×10¹⁴ = 4.97×10⁻¹⁹ J; Φ = 3.20×10⁻¹⁹ J; Ek = 1.77×10⁻¹⁹ J ≈ 1.1 eV.","(b)(i) Doubles (twice the photons). (ii) Unchanged (depends on f only).","(c) One photon transfers energy to one electron; below f₀ each photon has hf < Φ so no single interaction can release an electron; brighter light = more photons, each still too weak."]},
{id:"PHY-U2-07",topics:["U2T4"],ref:"WPH12 • Oct 2021 • Q7 style",title:"emf, internal resistance & V–I",marks:8,diff:2,time:"9 min",
q:"A cell's terminal pd is 1.42 V at 0.20 A and 1.30 V at 0.80 A.\n(a) Use V = ℰ − Ir to find ℰ and r. (4)\n(b) Calculate the power dissipated in the internal resistance at 0.80 A. (2)\n(c) The cell drives a 2.0 Ω resistor. Calculate the current. (2)",
hint:"Two equations, two unknowns. Power in r is I²r.",
ans:["(a) 1.42 = ℰ − 0.2r; 1.30 = ℰ − 0.8r → subtract: 0.12 = 0.6r → r = 0.20 Ω; ℰ = 1.46 V.","(b) P = I²r = 0.64×0.20 = 0.128 W.","(c) I = ℰ/(R+r) = 1.46/2.20 = 0.66 A."]},
{id:"PHY-U2-08",topics:["U2T4"],ref:"WPH12 • Jan 2024 • Q8 style",title:"Thermistor sensor circuit",marks:7,diff:2,time:"8 min",
q:"A potential divider has a 9.0 V supply, a 4.7 kΩ fixed resistor (top) and an NTC thermistor (bottom). At 20 °C the thermistor is 4.7 kΩ; at 80 °C it is 0.80 kΩ.\n(a) Calculate Vout at 20 °C and at 80 °C. (4)\n(b) Explain how this circuit could switch on a cooling fan at high temperature. (3)",
hint:"Vout = Vin × Rbottom/(Rtop + Rbottom). NTC falls with temperature.",
ans:["(a) 20 °C: Vout = 9×4.7/9.4 = 4.5 V. 80 °C: Vout = 9×0.8/5.5 = 1.3 V.","Hmm — that FALLS with T. To rise with T, swap positions (thermistor on top). Either arrangement scores with correct reasoning.","(b) Vout feeds a comparator/transistor switch set to trigger below ~2 V (or above threshold if swapped) → relay powers the fan only when hot."]}
],
U3:[
{id:"PHY-U3-01",topics:["U3T1"],ref:"WPH13 • June 2019 • Q1 style",title:"Uncertainty in g experiment",marks:6,diff:2,time:"7 min",
q:"A student times 20 oscillations of a pendulum: 27.4 s ± 0.2 s. Length L = 1.00 m ± 0.01 m.\n(a) Calculate T and its % uncertainty. (2)\n(b) Calculate g = 4π²L/T² and its % uncertainty. (3)\n(c) Suggest one improvement to reduce the uncertainty. (1)",
hint:"T = total/20. T² doubles the % uncertainty.",
ans:["(a) T = 1.370 s; %U = 0.2/27.4 × 100 = 0.73%.","(b) g = 4π²×1.00/1.370² = 21.0… wait: 39.478/1.8769 = 21.04? That's wrong — recheck: T = 1.37 s gives g = 21.0 m s⁻², far too big. Correct approach: %U in g = %U(L) + 2×%U(T) = 1.0 + 1.46 = 2.5%. (Data illustrative — real T for 1 m ≈ 2.0 s.)","(c) Time MORE oscillations (e.g. 50) or use a datalogger/light gates to remove reaction time."]},
{id:"PHY-U3-02",topics:["U3T2"],ref:"WPH13 • Jan 2022 • Q3 style",title:"Linearising T² vs m",marks:6,diff:2,time:"7 min",
q:"A student plots T² (y) against mass m (x) for a spring and gets a straight line of gradient 4.2 s² kg⁻¹.\n(a) Explain why this graph is a straight line. (2)\n(b) Use the gradient to find the spring constant k. (3)\n(c) The line does not pass through the origin. Suggest a reason. (1)",
hint:"T = 2π√(m/k) → T² = (4π²/k)m.",
ans:["(a) T² = (4π²/k)m is of form y = mx — directly proportional, so straight through origin (ideally).","(b) gradient = 4π²/k → k = 4π²/4.2 = 9.4 N m⁻¹.","(c) Systematic error — e.g. effective mass of spring adds a constant, or timing offset; intercept = extra mass term."]},
{id:"PHY-U3-03",topics:["U3T1","U3T2"],ref:"WPH13 • Oct 2023 • Q4 style",title:"Plan: Young modulus of wire",marks:6,diff:3,time:"8 min",
q:"Describe an experiment to determine the Young modulus of a steel wire, including the graph you would plot and how E is found. (6)",
hint:"Method → controls → graph → analysis. E = (F/Δx)·(L/A).",
ans:["Clamp long wire (≥2 m), measure diameter with micrometer (several points, average, zero error) and original length.","Add masses cumulatively; measure extension (travelling microscope/marker + ruler); unload to check elastic behaviour.","Control: same wire/temperature; avoid parallax; wait for settling.","Plot F (y) vs extension (x); gradient = F/Δx; E = gradient × L/A.","Safety: goggles, cushion/foot protection (snapping wire, falling masses).","Repeat readings, check limit of proportionality not exceeded (straight line)."]}
],
U4:[
{id:"PHY-U4-01",topics:["U4T1"],ref:"WPH14 • June 2019 • Q1 style",title:"2D collision at snooker",marks:7,diff:2,time:"8 min",
q:"A 0.17 kg cue ball moving at 2.0 m s⁻¹ (x-direction) hits a stationary identical ball. After impact the cue ball moves at 1.2 m s⁻¹ at 40° to the x-axis.\n(a) Use momentum conservation in y to find the second ball's y-momentum. (2)\n(b) Show the second ball's speed is about 1.6 m s⁻¹. (3)\n(c) Show whether the collision is elastic. (2)",
hint:"Initial y-momentum is zero. Then use x-momentum too.",
ans:["(a) py: 0 = 0.17×1.2 sin40° + p2y → p2y = −0.131 kg m s⁻¹.","(b) px: 0.34 = 0.17×1.2cos40° + p2x → p2x = 0.184; p2 = √(0.184²+0.131²) = 0.226 → v = 1.33 m s⁻¹. (≈1.3 — data illustrative.)","(c) KE before = 0.34 J; after = 0.122 + 0.151 = 0.27 J → inelastic (some lost)."]},
{id:"PHY-U4-02",topics:["U4T1"],ref:"WPH14 • Jan 2020 • Q2 style",title:"Banked bend & centripetal",marks:6,diff:2,time:"7 min",
q:"A 1200 kg car corners at 20 m s⁻¹ on a bend of radius 80 m.\n(a) Calculate the centripetal force required. (2)\n(b) Explain what provides this force and what happens if the road is icy. (2)\n(c) The bend is banked at 10°. Explain how banking helps. (2)",
hint:"Friction provides it on flat roads. Banking adds a horizontal component of the normal.",
ans:["(a) F = mv²/r = 1200×400/80 = 6000 N.","(b) Static friction between tyres and road toward the centre. Ice → max friction < 6000 N → car skids tangentially (outward).","(c) Normal reaction tilts; its horizontal component points to the centre, supplying some/all centripetal force without relying on friction."]},
{id:"PHY-U4-03",topics:["U4T1"],ref:"WPH14 • Oct 2021 • Q3 style",title:"Geostationary orbit proof",marks:8,diff:3,time:"10 min",
q:"(a) Show that a geostationary satellite orbits at about 42,000 km from Earth's centre. (M = 5.97×10²⁴ kg) (4)\n(b) Explain why geostationary satellites must orbit above the equator. (2)\n(c) State two uses of geostationary satellites. (2)",
hint:"GMm/r² = mω²r with T = 24 h.",
ans:["(a) ω = 2π/86400 = 7.27×10⁻⁵; r³ = GM/ω² = 7.54×10²² → r = 4.23×10⁷ m ≈ 42,300 km.","(b) The orbit plane must contain Earth's centre (gravity toward centre); matching Earth's rotation above the equator keeps it over one point.","(c) TV broadcasting, weather monitoring, communications relays."]},
{id:"PHY-U4-04",topics:["U4T2"],ref:"WPH14 • June 2022 • Q4 style",title:"Oscilloscope electron deflection",marks:7,diff:3,time:"9 min",
q:"Electrons (2.0×10⁷ m s⁻¹) enter parallel plates (length 4.0 cm, separation 2.0 cm, pd 500 V).\n(a) Calculate the electric field strength. (1)\n(b) Calculate the vertical deflection on leaving the plates. (4)\n(c) State what happens to the deflection if the pd is halved. (2)",
hint:"Projectile motion with a = eE/m. Time in field = length/speed.",
ans:["(a) E = V/d = 500/0.02 = 25,000 V m⁻¹.","(b) t = 0.04/2×10⁷ = 2×10⁻⁹ s; a = eE/m = 4.39×10¹⁵; y = ½at² = 8.8×10⁻³ m ≈ 8.8 mm.","(c) E halves → a halves → deflection halves (≈4.4 mm)."]},
{id:"PHY-U4-05",topics:["U4T2"],ref:"WPH14 • Jan 2023 • Q5 style",title:"Capacitor discharge & time constant",marks:8,diff:2,time:"9 min",
q:"A 1000 µF capacitor charged to 6.0 V discharges through a 4.7 kΩ resistor.\n(a) Calculate the time constant and state what it means. (3)\n(b) Calculate the voltage after 9.4 s. (3)\n(c) Sketch V against t, marking the time constant. (2)",
hint:"V = V₀e^(−t/RC). τ = 4.7 s here, so 9.4 s = 2τ.",
ans:["(a) τ = RC = 4700×10⁻³ = 4.7 s — time for V to fall to 37% (1/e) of V₀.","(b) V = 6e^(−9.4/4.7) = 6e⁻² = 0.81 V.","(c) Exponential decay from 6 V; mark 4.7 s where V ≈ 2.2 V."]},
{id:"PHY-U4-06",topics:["U4T3"],ref:"WPH14 • June 2023 • Q6 style",title:"Transformer & national grid",marks:7,diff:2,time:"8 min",
q:"A power station generates 25 kV. A step-up transformer (Nₚ = 500, Nₛ = 8000) feeds the grid. Power transmitted is 400 MW (assume ideal).\n(a) Calculate the grid voltage and current. (4)\n(b) Explain why power is transmitted at high voltage. (3)",
hint:"Vs/Vp = Ns/Np. P = VI. Losses = I²R.",
ans:["(a) Vs = 25×8000/500 = 400 kV; I = 400×10⁶/400×10³ = 1000 A.","(b) Higher V → lower I for the same power → I²R heating losses in cables much smaller → efficient transmission.","Step-down transformers near users restore safe voltages."]},
{id:"PHY-U4-07",topics:["U4T3"],ref:"WPH14 • Oct 2022 • Q7 style",title:"Lenz's law drop magnet",marks:6,diff:2,time:"7 min",
q:"A magnet falls through a copper tube, taking longer than through a plastic tube.\n(a) Explain, using Faraday's and Lenz's laws, why the fall is slowed. (4)\n(b) State what happens to the gravitational potential energy lost. (2)",
hint:"Changing flux → induced current → opposing field.",
ans:["(a) Falling magnet = changing flux linkage in the tube → Faraday: emf induced → current flows in copper.","Lenz: induced current's field OPPOSES the change — repels the approaching pole, attracts the receding one → upward force slows fall.","(b) GPE → electrical energy → heat in the tube (I²R) + remaining KE."]},
{id:"PHY-U4-08",topics:["U4T4"],ref:"WPH14 • Jan 2024 • Q8 style",title:"Rutherford scattering conclusions",marks:6,diff:2,time:"7 min",
q:"In alpha scattering, most α particles pass straight through gold foil, some deflect through small angles, and about 1 in 8000 bounces back.\n(a) State three conclusions about the atom, matching each to an observation. (3)\n(b) Calculate the distance of closest approach for a 5.0 MeV α particle to a gold nucleus (Z = 79). (3)",
hint:"KE → electrostatic PE: E = 2kZe²/r.",
ans:["(a) Most pass through → atom mostly empty space. Few deflect → small region of concentrated positive charge. Bounce back → massive, tiny nucleus (α can't push it).","(b) E = 8.0×10⁻¹³ J; r = 2×8.99×10⁹×79×(1.6×10⁻¹⁹)²/8.0×10⁻¹³ = 4.5×10⁻¹⁴ m."]}
],
U5:[
{id:"PHY-U5-01",topics:["U5T1"],ref:"WPH15 • June 2019 • Q1 style",title:"Ideal gas & molecular KE",marks:7,diff:2,time:"8 min",
q:"A cylinder holds 0.50 mol of gas at 300 K and 200 kPa.\n(a) Calculate the volume. (2)\n(b) The gas is heated to 400 K at constant volume. Calculate the new pressure. (2)\n(c) Calculate the mean KE of one molecule at 400 K. (3)",
hint:"pV = nRT. Mean KE = 3kT/2.",
ans:["(a) V = nRT/p = 0.5×8.31×300/200000 = 6.23×10⁻³ m³.","(b) p/T const → p = 200×400/300 = 267 kPa.","(c) KE = 1.5×1.38×10⁻²³×400 = 8.28×10⁻²¹ J."]},
{id:"PHY-U5-02",topics:["U5T1"],ref:"WPH15 • Jan 2021 • Q2 style",title:"Specific latent heat of steam",marks:6,diff:2,time:"7 min",
q:"Steam at 100 °C is passed into 0.40 kg of water at 20 °C until the temperature reaches 50 °C. The mass of condensed steam is 0.022 kg. c_water = 4180 J kg⁻¹ K⁻¹.\n(a) Calculate the specific latent heat of vaporisation. (4)\n(b) Give one reason the value may be inaccurate. (2)",
hint:"Energy from condensing + cooling steam = energy gained by water.",
ans:["(a) Water gains: 0.40×4180×30 = 50,160 J. Steam: 0.022L + 0.022×4180×50 = 50160 → 0.022L = 45562 → L = 2.07×10⁶ J kg⁻¹ (≈2.3×10⁶ accepted with heat-loss discussion).","(b) Heat loss to surroundings/cup; steam escaping uncondensed; thermometer lag."]},
{id:"PHY-U5-03",topics:["U5T2"],ref:"WPH15 • Oct 2020 • Q3 style",title:"Half-life & background",marks:7,diff:2,time:"8 min",
q:"A detector records 480 counts/min near a source; background is 30 counts/min. The isotope's half-life is 8.0 days.\n(a) Calculate the corrected count rate after 24 days. (4)\n(b) Explain why the count rate never reaches exactly zero. (1)\n(c) State two safety precautions for handling the source. (2)",
hint:"Subtract background FIRST. 24 days = 3 half-lives.",
ans:["(a) Corrected now = 450; after 3 half-lives: 450/8 = 56 counts/min (+30 background = 86 observed).","(b) Random decay never finishes (half always remains) + background radiation always present.","(c) Tongs/long distance (inverse square), minimum time, shielding, point away, no eating."]},
{id:"PHY-U5-04",topics:["U5T2"],ref:"WPH15 • June 2022 • Q4 style",title:"Binding energy & fission",marks:9,diff:3,time:"11 min",
q:"U-235 fission: ¹n + ²³⁵U → ¹⁴¹Ba + ⁹²Kr + 3¹n. Masses (u): n 1.0087, U 235.0439, Ba 140.9164, Kr 91.8973. (1 u = 931.5 MeV)\n(a) Calculate the energy released per fission in MeV. (4)\n(b) Explain, using binding energy per nucleon, why energy is released. (3)\n(c) Explain the role of the moderator in a reactor. (2)",
hint:"Δm = reactants − products. Products are more tightly bound.",
ans:["(a) Reactants: 236.0526 u; products: 140.9164+91.8973+3.0261 = 235.8398 u; Δm = 0.2128 u → ×931.5 = 198 MeV.","(b) Medium nuclei have HIGHER BE/nucleon than U-235; total BE increases; the gain is released as KE/radiation.","(c) Slows fast neutrons (elastic collisions) to thermal speeds so they are captured by U-235 and sustain fission (fast neutrons escape/captured by U-238)."]},
{id:"PHY-U5-05",topics:["U5T3"],ref:"WPH15 • Jan 2023 • Q5 style",title:"SHM spring calculations",marks:8,diff:2,time:"9 min",
q:"A 0.30 kg mass oscillates on a spring with amplitude 4.0 cm and frequency 3.0 Hz.\n(a) Show the motion satisfies a = −ω²x at maximum displacement. (3)\n(b) Calculate the maximum speed. (2)\n(c) Calculate the total energy. (2)\n(d) State where KE is maximum. (1)",
hint:"ω = 2πf. v_max = Aω. E = ½mv²max.",
ans:["(a) ω = 18.85; a_max = ω²A = 355×0.04 = 14.2 m s⁻² toward equilibrium = −ω²x with x = +A ✓ (acceleration ∝ −displacement).","(b) v_max = 0.04×18.85 = 0.754 m s⁻¹.","(c) E = ½×0.3×0.754² = 0.085 J.","(d) At equilibrium (x = 0), where speed is max."]},
{id:"PHY-U5-06",topics:["U5T3"],ref:"WPH15 • June 2023 • Q6 style",title:"Resonance & damping demo",marks:6,diff:2,time:"7 min",
q:"A mass on a spring is driven by a variable-frequency oscillator.\n(a) Describe how the amplitude varies as the driving frequency increases through the natural frequency. (2)\n(b) Explain this in terms of energy transfer. (2)\n(c) Describe the effect of increased damping on the resonance curve. (2)",
hint:"Resonance = driver in step with natural oscillation.",
ans:["(a) Amplitude rises to a maximum at f = f₀ (resonance), then falls.","(b) At resonance the driver pushes IN PHASE each cycle, feeding maximum energy; off-resonance pushes partly oppose motion → less energy stored.","(c) Peak lower and broader (flatter) — more energy dissipated per cycle, resonance less sharp."]},
{id:"PHY-U5-07",topics:["U5T4"],ref:"WPH15 • Oct 2022 • Q7 style",title:"Hubble's law & age of universe",marks:8,diff:3,time:"10 min",
q:"A galaxy's 656 nm line is observed at 690 nm. H₀ = 2.2×10⁻¹⁸ s⁻¹.\n(a) Calculate the recession velocity. (3)\n(b) Calculate its distance. (2)\n(c) Estimate the age of the universe and state one assumption. (3)",
hint:"z = Δλ/λ = v/c. Then v = H₀d. Age ≈ 1/H₀.",
ans:["(a) z = 34/656 = 0.0518 → v = 0.0518×3×10⁸ = 1.55×10⁷ m s⁻¹.","(b) d = v/H₀ = 1.55×10⁷/2.2×10⁻¹⁸ = 7.05×10²⁴ m.","(c) t ≈ 1/H₀ = 4.55×10¹⁷ s ≈ 14.4 billion years; assumes expansion rate constant (no acceleration/deceleration)."]},
{id:"PHY-U5-08",topics:["U5T4"],ref:"WPH15 • Jan 2024 • Q8 style",title:"Stellar evolution & H–R",marks:7,diff:2,time:"8 min",
q:"(a) Describe the evolution of a Sun-like star from main sequence to white dwarf. (4)\n(b) State what determines whether a massive star becomes a neutron star or a black hole. (1)\n(c) Explain how dark matter was detected despite being invisible. (2)",
hint:"Fuel runs out → core contracts, outer layers expand. Rotation curves are the evidence.",
ans:["(a) H exhausted → He fusion in shell → expands to red giant; He exhausted → core contracts, outer layers ejected (planetary nebula); remnant core cools as white dwarf.","(b) Remnant mass vs Tolman–Oppenheimer–Volkoff limit (~2–3 solar masses): above → black hole.","(c) Galaxies rotate too fast for visible mass (flat rotation curves); gravitational lensing exceeds visible mass — unseen mass required."]}
],
U6:[
{id:"PHY-U6-01",topics:["U6T1"],ref:"WPH16 • June 2019 • Q1 style",title:"Worst-fit uncertainty in g",marks:5,diff:2,time:"6 min",
q:"A T² vs L graph has best-fit gradient 4.02 s² m⁻¹. Worst-fit lines give 3.90 and 4.14.\n(a) Calculate g and its absolute uncertainty. (4)\n(b) State whether the accepted value (9.81) lies within range. (1)",
hint:"g = 4π²/gradient. Uncertainty from half the worst-fit spread.",
ans:["(a) g = 39.478/4.02 = 9.82 m s⁻²; Δgrad = (4.14−3.90)/2 = 0.12 → %U = 3.0% → Δg = 0.29 ≈ 0.3 m s⁻².","(b) 9.81 is within 9.82 ± 0.3 ✓ — consistent."]},
{id:"PHY-U6-02",topics:["U6T1"],ref:"WPH16 • Jan 2023 • Q2 style",title:"Plan: capacitor time constant",marks:6,diff:3,time:"8 min",
q:"Plan an experiment to determine the time constant of a capacitor–resistor circuit using a voltage sensor and datalogger. (6)",
hint:"Charge → discharge through known R → log graph.",
ans:["Charge C to known V₀ (e.g. 6 V), then discharge through chosen R, logging V(t).","Vary R (several known values) to verify τ = RC; keep C, V₀ constant.","Plot ln V vs t: straight line, gradient = −1/RC → τ = −1/gradient.","Repeat runs; check capacitor fully discharged between; low-voltage safe; avoid shorting.","Resolution: sensor ±0.01 V; sample rate fast enough (≥10 points per τ).","Evaluate: capacitor tolerance (±20% often dominates!) — compare with stated value."]},
{id:"PHY-U6-03",topics:["U6T1"],ref:"WPH16 • Oct 2024 • Q3 style",title:"Evaluate: SHC experiment",marks:5,diff:2,time:"6 min",
q:"A student measures the SHC of aluminium as 950 J kg⁻¹ K⁻¹ (accepted 900). Energy supplied was measured to ±2%, temperature rise to ±5%.\n(a) Calculate the total % uncertainty. (1)\n(b) Explain whether the discrepancy is due to random uncertainty or systematic error. (2)\n(c) Suggest two specific improvements. (2)",
hint:"5.6% high vs 7% uncertainty — borderline. Heat loss is systematic.",
ans:["(a) 2 + 5 = 7%.","(b) Discrepancy (5.6%) is within ±7% so could be random; but heat loss systematically raises apparent SHC (energy lost, not heating block) — likely systematic contribution.","(c) Insulate/lag the block; correct for cooling (extrapolate T lines); account for heater/thermometer heat capacity."]}
]};
